Repository TrinityCore/TrinityCore, pull requests merged in 2018-12, with the labels that each got.

#22806 Quest: Ruthless Cunning and Returning the Favor
  sql/updates/world/3.3.5/2018_12_03_00_word.sql
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Outland/zone_nagrand.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix

#22849 Core/DataStores: check loaded DB2 8.0.1 28153
  src/server/game/DataStores/DB2Stores.cpp
Labels: Branch-bfa

#22800 [Bfa] HotfixBlob for more client support
  sql/updates/hotfixes/master/2018_12_07_00_hotfixes.sql
  src/server/game/DataStores/DB2Stores.cpp
  src/server/game/DataStores/DB2Stores.h
  src/server/game/Handlers/HotfixHandler.cpp
  src/server/game/World/World.cpp
Labels: Branch-bfa, Feedback-FixOutdatedMissingWIP

#22783 Core/Misc: Log more information in asserts
  src/common/Debugging/Errors.cpp
  src/common/Debugging/Errors.h
  src/server/game/AI/CoreAI/UnitAI.cpp
  src/server/game/AI/CoreAI/UnitAI.h
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Creature/TemporarySummon.cpp
  src/server/game/Entities/Creature/TemporarySummon.h
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/GameObject/GameObject.h
  src/server/game/Entities/Item/Container/Bag.cpp
  src/server/game/Entities/Item/Container/Bag.h
  src/server/game/Entities/Item/Item.cpp
  src/server/game/Entities/Item/Item.h
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Entities/Object/Position.cpp
  src/server/game/Entities/Object/Position.h
  src/server/game/Entities/Pet/Pet.cpp
  src/server/game/Entities/Pet/Pet.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Transport/Transport.cpp
  src/server/game/Entities/Transport/Transport.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
  src/server/game/Spells/Auras/SpellAuras.cpp
  src/server/game/Spells/Auras/SpellAuras.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-FixOutdatedMissingWIP, Priority-FutureFeatureRequest

#22872 Core/Player: update player phase before updating area depending auras
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#22298 Core/Handlers: fix ".whisper on" with opposite faction/low level
  src/server/game/Handlers/ChatHandler.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Chat

#22878 Scripts/Nagrand: Fix crash added in PR #22806
  src/server/scripts/Outland/zone_nagrand.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Quests

#22727 Spell/Script: Scourge Disguise and Haunting Phantoms
  sql/updates/world/3.3.5/2018_12_31_00_world.sql
  src/server/scripts/EasternKingdoms/Stratholme/stratholme.cpp
  src/server/scripts/Northrend/zone_zuldrak.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix
