Repository TrinityCore/TrinityCore, pull requests merged in 2018-11, with the labels that each got.

#22014 Core/Entities: Handle partial state change for pets
  src/server/game/Entities/Creature/TemporarySummon.cpp
  src/server/game/Entities/Creature/TemporarySummon.h
  src/server/game/Handlers/PetHandler.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-PetMinion

#22382 Core/Spells: fix issues with delayed spells and auras
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells

#22728 Spell/Script: Curse of agony
  sql/updates/world/3.3.5/2018_11_04_00_world.sql
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#22759 Core/Unit: Patch 3.0.8 tagging
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#22768 [3.3.5] SmartEnum (again)
  contrib/enumutils_describe.py
  dep/CMakeLists.txt
  dep/smart_enum/CMakeLists.txt
  dep/smart_enum/LICENSE_1_0.txt
  dep/smart_enum/smart_enum.hpp
  src/common/CMakeLists.txt
  src/common/Utilities/IteratorPair.h
  src/common/Utilities/SmartEnum.h
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
  src/server/game/Entities/Unit/UnitDefines.h
  src/server/game/Entities/Unit/enuminfo_UnitDefines.cpp
  src/server/scripts/Commands/cs_npc.cpp
  src/server/shared/SharedDefines.h
  src/server/shared/enuminfo_SharedDefines.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#22804 Core/Vehicles: define and implement VEHICLE_SEAT_FLAG_DISABLE_GRAVITY
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Entities/Vehicle/Vehicle.cpp
  src/server/game/Entities/Vehicle/VehicleDefines.h
Labels: Branch-master, Comp-Core, Feedback-PatchFix, Sub-Vehicles

#22828 Core/Scripts: The Eye: Kael'thas Sunstrider MC - limit MaxAffectedTargets to 3
  src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-FixOutdatedMissingWIP, Sub-Instances, Sub-Spells

#22836 Scripts/movement: spline - velocity
  src/server/game/Movement/Spline/MoveSpline.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix

#17782 Core/GameEvent: weekend xp rate
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/scripts/World/boosted_xp.cpp
  src/server/scripts/World/world_script_loader.cpp
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a, Comp-Core, Feedback-FixOutdatedMissingWIP
