Repository TrinityCore/TrinityCore, pull requests merged in 2019-12, with the labels that each got.

#23953 Scripts/ScarletEnclave: reworked Eye of Acherus script
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Labels: Branch-3.3.5a

#23961 Scripts/VioletHold: Minor improvements
  src/server/scripts/Northrend/VioletHold/instance_violet_hold.cpp
  src/server/scripts/Northrend/VioletHold/violet_hold.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#23924 Core/Battleground: Extra check on disabled battleground
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Handlers/BattleGroundHandler.cpp
Labels: Branch-master

#23976 Boss/Script: Fix Mechano-Lord Capacitus's Nether Charges
  sql/updates/world/3.3.5/2019_12_19_00_world.sql
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix, Sub-Instances

#23991 Core/Movement: Add more LoS checks
  src/server/game/Movement/MovementGenerators/ConfusedMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
Labels: Branch-3.3.5a

#23992 Core/Spells: Fix Spellsteal stealing Silence buff of Arcane Torrent
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#23999 Core/Creatures: Fix spell_school_immune_mask being applied against positive spells too
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#23858 Scritps/ICC: Fixed resistance calculation for Mutated Transformation (Professor Putricide)
  sql/updates/world/3.3.5/2019_12_26_00_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances, Sub-Spells

#24000 Core/Movement: Fix stunned falling units freezing the client
  src/server/game/Movement/MotionMaster.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#24006 additional output for additem command
  sql/updates/world/3.3.5/2019_12_28_01_world.sql
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Miscellaneous/Language.h
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a

#24007 Spell/Script: Egg Nog
  sql/updates/world/3.3.5/2019_12_29_00_world.sql
  src/server/scripts/Spells/spell_item.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#23986 Core/Movement: Fix wrong orientation set when pausing movement
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Movement/Spline/MoveSpline.h
Labels: Branch-3.3.5a

#24002 Scripts/Spells: Fixed Black Magic proc with some druid spells
  sql/updates/world/3.3.5/2019_12_30_00_world.sql
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#23985 Core/Spells: Fix Power Word: Shield (Priest) absorb amount
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#24010 Core/MMaps: Fix charge underwater/falling
  src/server/game/Movement/PathGenerator.cpp
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a
