Repository TrinityCore/TrinityCore, pull requests merged in 2019-10, with the labels that each got.

#23840 Core/Pet: Fix guardians low damage
  src/server/game/Entities/Pet/Pet.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Creature

#23846 Scripts/ICC: Fixed Tear Gas not getting removed of Abomination in phase change of PP
  src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances, Sub-Spells

#23843 Scripts/Forge of Souls: Fixed spell Soul Sickness
  sql/updates/world/3.3.5/2019_10_03_00_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/forge_of_souls.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances, Sub-Spells

#23847 Scripts/ICC: Fixed Death Plague (Frost Giant)
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances, Sub-Spells

#23845 Scripts/ICC: Fixed some issues with Rotface Oozes
  src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#23862 Core/LFG: Fix re-queueing while in a dungeon
  src/server/game/DungeonFinding/LFGMgr.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Instances

#23835 Core/Taxis: teleport players to the destination taxi node location instead of their current ground position
  src/server/game/Movement/MovementGenerators/FlightPathMovementGenerator.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#23844 Core/Achievements: fixed bug with counting honorless units for achievement type ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL
  src/server/game/Entities/Player/KillRewarder.cpp
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a, Feedback-FixOutdatedMissingWIP

#23866 Scripts/Kologarn: Fix "stuck in combat" issues
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Instances

#23630 Core/Defines: define UNIT_FLAG_SWIMMING
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/UnitDefines.h
  src/server/game/Entities/Unit/enuminfo_UnitDefines.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
  src/server/scripts/Northrend/Nexus/Oculus/boss_varos.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#23877 Core/Spells - Rogue: Fix Unfair Advantage range
  src/server/game/Spells/SpellMgr.cpp
Labels: Branch-3.3.5a

#23889 Scripts/ScarletMonastery; instance script cleanup
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Maps/MapRefManager.h
  src/server/game/Scripting/ScriptMgr.h
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_arcanist_doan.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_azshir_the_sleepless.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_bloodmage_thalnos.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_headless_horseman.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_herod.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_high_inquisitor_fairbanks.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_houndmaster_loksey.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_interrogator_vishas.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_mograine_and_whitemane.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_scorn.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/instance_scarlet_monastery.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/scarlet_monastery.h
  src/server/shared/Dynamic/LinkedReference/RefManager.h
Labels: Branch-3.3.5a

#23898 Core: added aarch64 definition for jemalloc
  dep/jemalloc/CMakeLists.txt
  dep/jemalloc/jemalloc_internal_defs.h.in.cmake
Labels: Branch-3.3.5a
