Repository TrinityCore/TrinityCore, pull requests merged in 2019-06, with the labels that each got.

#23345 Core/SAI: add action_param3 to SMART_ACTION_REMOVEAURASFROMSPELL to allow it to remove only auras from spells that were cast by the entity itself
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#23344 Script/Creature: calculate Traveler's Tundra Mammoth's NPCs' exit position based on current player's position
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-3.3.5a

#23349 Script/Creature: implement spell effect for the item Prototype Neural Needler used on Imprisoned Beryl Sorcerer
  sql/updates/world/3.3.5/2019_06_03_02_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23346 Script/Quest: implement event for the quest Orabus the Helmsman
  sql/updates/world/3.3.5/2019_06_04_04_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23180 Core/Logging: Split logs for unknown and zero triggered spells
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-FixOutdatedMissingWIP, Sub-Spells

#23358 Script/ZulGurub: fix the RP texts triggered when players reach certain areas
  sql/updates/world/3.3.5/9999_99_99_99_world.sql
  src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/zulgurub.h
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#23379 Scripts/Icecrown Citadel: Fixed Heroic Attempts logic
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#23394 Core/Misc: Implemented Icecrown Citadel buff disable
  sql/updates/world/3.3.5/2040_48_33_00_world.sql
  src/server/game/Entities/Pet/Pet.cpp
  src/server/game/Spells/Auras/SpellAuras.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.h
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Core, Feedback-PatchFix, Sub-Instances

#23400 Core/Player: allow AutoStoreLoot to specify if the looted item shouldbe shown as if created by the player
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
Labels: Branch-3.3.5a

#23401 Core/Spell: allow Northrend Inscription Research to unlock three recipes the first time it is cast
  src/server/game/Skills/SkillDiscovery.cpp
  src/server/game/Skills/SkillDiscovery.h
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#23391 3.3.5 game event respawn
  src/server/game/Events/GameEventMgr.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Creature

#23410 Core/Loot: fix some issues with master loot and don't allow players to see soulbound recipes that they already learned in the loot window
  src/server/game/Handlers/LootHandler.cpp
  src/server/game/Loot/Loot.cpp
  src/server/game/Loot/Loot.h
Labels: Comp-Core, Sub-Loot

#23398 Core/Group: implement automatic party/raid leader change when the leader has been offline for two minutes
  src/server/game/Groups/Group.cpp
  src/server/game/Groups/Group.h
  src/server/game/Groups/GroupMgr.cpp
  src/server/game/Groups/GroupMgr.h
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Server/WorldSession.cpp
  src/server/game/World/World.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Groups

#23343 Core/CreatureTemplate: Outsourced resistances and spells into creatur…
  sql/updates/world/3.3.5/2019_06_15_01_world.sql
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
Labels: Branch-3.3.5a, Comp-Core, Comp-Database, Sub-Creature, Sub-Database

#23367 Core/Creature: prevent dead creatures from setting a focus target.
  src/server/game/Entities/Creature/Creature.cpp
Labels: Branch-3.3.5a

#23403 Core/Entities: fix excessive damage of exotic pets and some creatures
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-PetMinion

#23404 Core/Spells: don't allow spells with SPELL_EFFECT_CREATE_ITEM_2 to be cast if there isn't enough space in inventory
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells

#23413 Core/Loot: implement automatic pass in group loot for items that cannot be looted
  src/server/game/Groups/Group.cpp
  src/server/game/Groups/Group.h
Labels: Branch-3.3.5a

#23408 Core/Loot: make Loot::AddItem() honor LootItem::AllowedForPlayer()
  src/server/game/Loot/Loot.cpp
  src/server/game/Loot/Loot.h
Labels: Branch-3.3.5a, Comp-Core, Sub-Loot

#23415 Core/Creatures: fix some other cases where a creature should not be able to set focus
  src/server/game/Entities/Creature/Creature.cpp
Labels: Comp-Core, Sub-Spells

#23418 Core/RDF: fix counting issue with the achievement Looking for More (and similar)
  src/server/game/Achievements/AchievementMgr.cpp
  src/server/game/DungeonFinding/LFGMgr.cpp
  src/server/game/DungeonFinding/LFGPlayerData.cpp
  src/server/game/DungeonFinding/LFGPlayerData.h
Labels: Comp-Core, Sub-Achievements

#23416 Core/Commands: implement commands to look up a map/item/quest name for a given id
  sql/base/auth_database.sql
  sql/updates/auth/3.3.5/2019_06_16_00_auth.sql
  src/server/game/Accounts/RBAC.h
  src/server/scripts/Commands/cs_lookup.cpp
Labels: Comp-Core, Sub-Commands

#23421 Core/SAI: don't allow to start a new SAI actionlist while the entity is already running one
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Comp-Core, Sub-ScriptingEngine

#23420 Core/Creature: drop current target when evading while a spell cast is in progress
  src/server/game/Entities/Creature/Creature.h
Labels: Comp-Core, Sub-Entities

#23422 Core/SAI: add cooldownMin (event_param2) and cooldownMax (event_param3) to SMART_EVENT_ACCEPTED_QUEST and SMART_EVENT_REWARD_QUEST
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Comp-Core, Sub-ScriptingEngine

#23237 Scripts/Spells: Gordunni Trap
  src/server/scripts/Kalimdor/zone_feralas.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix, Sub-Quests

#23382 Scripts/Isle of Quel'Danas: Thalorien Dawnseeker
  sql/updates/world/3.3.5/9999_99_99_99_world.sql
  src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
  src/server/scripts/EasternKingdoms/zone_isle_of_queldanas.cpp
Labels: Branch-3.3.5a, Feedback-FixOutdatedMissingWIP

#23397 Scripts/Icecrown Citadel: Fixed Blood Orb Game Object
  sql/updates/world/3.3.5/2019_06_17_01_world.sql
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.h
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#23434 Core/Packet: send SMSG_QUESTGIVER_STATUS_MULTIPLE when the player levels up
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#23437 Core/Misc: don't allow FindNearestCreature() and FindNearestGameObject() searches to return the entity that called them
  src/server/game/Grids/Notifiers/GridNotifiers.h
Labels: Branch-3.3.5a

#22886 Core/Spell: Jump Speed Calculations
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Movement

#23439 [master] Fix DB2 Structures
  sql/updates/hotfixes/master/2019_06_18_00_hotfixes.sql
  src/server/database/Database/Implementation/HotfixDatabase.cpp
  src/server/game/DataStores/DB2LoadInfo.h
  src/server/game/DataStores/DB2Structure.h
Labels: Branch-master, Comp-Core, Sub-DataStores

#23426 Core/SAI: allow to start waypoint movement for a creature that is in combat
  src/server/game/AI/SmartScripts/SmartAI.cpp
Labels: Comp-Core, Sub-Movement

#23428 Core/FlightPath: teleport players at destination on floor Z when the flight ends
  src/server/game/Movement/MovementGenerators/FlightPathMovementGenerator.cpp
Labels: Branch-3.3.5a

#23438 Core/Conditions: implement CONDITION_QUEST_OBJECTIVE_PROGRESS to allow to apply conditions based on the player's quest objective progress
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Conditions/ConditionMgr.h
Labels: Branch-3.3.5a

#23449 Core/Loot: don't allow to regenerate chest loot inside instances and raids
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#23448 Spell/Fishing: fix some Fishing bugs
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a

#23455 Scripts/Spells: Migrate Lightwell to Script
  sql/updates/world/3.3.5/2019_06_21_01_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23458 Scripts/Spells: Migrate Teleporting to Script
  sql/updates/world/3.3.5/2019_06_21_02_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23456 Scripts/Spells: Ultra-Advanced Proto-Typical Shortening Blaster
  sql/updates/world/3.3.5/2019_06_22_00_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23463 Scripts/Spells: Portal to Orgrimmar & Portal to Stormwind
  sql/updates/world/3.3.5/2019_06_22_01_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23263 Core/Instance : Fix instance resetting exploit
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/database/Database/Implementation/CharacterDatabase.h
  src/server/game/Groups/Group.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#23466 Core/AI: Fix Guardians not following the owner after finishing combat
  src/server/game/AI/CreatureAI.cpp
  src/server/game/AI/CreatureAI.h
Labels: Branch-3.3.5a, Comp-Core, Sub-AI

#23388 Script/CoS: full instance rewrite - partial merge
  sql/updates/world/3.3.5/2019_06_25_01_world.sql
  src/server/game/AI/ScriptedAI/ScriptedCreature.h
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_chrono_lord_epoch.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_infinite_corruptor.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_mal_ganis.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_meathook.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_salramm_the_fleshcrafter.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.h
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/instance_culling_of_stratholme.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/npc_arthas.cpp
  src/server/scripts/Kalimdor/kalimdor_script_loader.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#23514 Coding standards
  src/server/game/AuctionHouse/AuctionHouseMgr.h
  src/server/game/Battlegrounds/BattlegroundQueue.cpp
  src/server/game/Entities/Item/Item.cpp
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Grids/GridStates.cpp
  src/server/game/Handlers/LFGHandler.cpp
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellMgr.h
  src/server/scripts/Commands/cs_gm.cpp
  src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
  src/server/scripts/Outland/zone_nagrand.cpp
Labels: Branch-3.3.5a

#23496 Core/Spells: define and implement TARGET_UNIT_CONE_ENTRY_129
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-master

#23493 Core/SAI: do not pass old creatureData to UpdateEntry() and keep current health when changing a NPC's entry
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/Entities/Creature/Creature.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-ScriptingEngine

#23492 Core/SAI: allow creatures to handle gameobject spellhit SAI events
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/game/AI/SmartScripts/SmartAI.h
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-ScriptingEngine

#23479 Core/Spell: allow damage from binary spells to go through elemental resistance's damage reduction
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells

#23469 Core/GameObject: don't allow non-consumable goobers to despawn on use
  src/server/game/Entities/GameObject/GameObject.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-GameObject

#23526 Core/GameObject: implement restock mechanic for non-consumable gameobjects
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/GameObject/GameObject.h
Labels: Branch-3.3.5a, Comp-Core, Priority-Low, Sub-GameObject, Sub-Loot

#23429 Script/ZulGurub: rewrite High Priest Thekal's encounter script
  sql/updates/world/3.3.5/2019_06_27_03_world.sql
  src/server/game/Spells/SpellInfo.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_thekal.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23500 Core/Mail: include 100g in the mail sent after turning in the quest The Wrath of Neptulon
  src/server/game/Mails/Mail.cpp
Labels: Branch-3.3.5a

#23425 Core/Spell: fix some issues with taunt spells
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a

#23505 Scripts/Spells: Dimensional Ripper - Area 52
  sql/updates/world/3.3.5/2019_06_28_00_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_item.cpp
Labels: Branch-3.3.5a

#23531 Scripts/Spells: Deathbolt
  sql/updates/world/3.3.5/2019_06_28_01_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Northrend/zone_sholazar_basin.cpp
Labels: Branch-3.3.5a

#23533 Scripts/Spells: Remove Collapsing Cave Aura
  sql/updates/world/3.3.5/2019_06_29_00_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Northrend/zone_storm_peaks.cpp
Labels: Branch-3.3.5a

#23537 Scripts/Spells: Ultrasafe Transporter: Toshley's Station
  sql/updates/world/3.3.5/2019_06_29_01_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_item.cpp
Labels: Branch-3.3.5a
