Repository TrinityCore/TrinityCore, pull requests merged in 2019-08, with the labels that each got.

#23216 Core/Spells: fixed root behaivior of creatures that are being rooted via movement template while getting a root aura removed
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix, Sub-Miscellaneous

#23271 3.3.5 Don't allow to summon dead hunter pets
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Spells/SpellEffects.cpp
  src/server/shared/SharedDefines.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-FixOutdatedMissingWIP, Sub-PetMinion

#23660 Scripts/Spells: Devour Humanoid
  sql/updates/world/3.3.5/2019_08_02_02_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter2.cpp
Labels: Branch-3.3.5a

#23579 Core/Spell: honor IsStackableOnOneSlotWithDifferentCasters() when deciding if an aura should stack from different casters or not.
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a, Comp-Core, Priority-Low, Sub-Spells

#23646 Core/Vehicle: Change vehicle accessories' phase according to the player on the vehicle
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
Labels: Branch-3.3.5a

#23627 [3.3.5] Quest pooling rewrite
  sql/updates/world/3.3.5/2019_08_04_00_world.sql
  src/common/Utilities/Util.cpp
  src/common/Utilities/Util.h
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/database/Database/Implementation/CharacterDatabase.h
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/database/Database/Implementation/WorldDatabase.h
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Events/GameEventMgr.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Pools/PoolMgr.cpp
  src/server/game/Pools/PoolMgr.h
  src/server/game/Pools/QuestPools.cpp
  src/server/game/Pools/QuestPools.h
  src/server/game/Quests/QuestDef.cpp
  src/server/game/Quests/QuestDef.h
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/scripts/Commands/cs_debug.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Pools, Sub-Quests

#23691 Scripts/Spells: Port Part of Druid Scripts to New Script Registration
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-3.3.5a

#23690 Scripts/Spells: Runic Healing Injector
  sql/updates/world/3.3.5/2019_08_08_00_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_item.cpp
Labels: Branch-3.3.5a

#23633 [3.3.5] Somewhat more secure storage of TOTP PSK
  dep/CMakeLists.txt
  dep/PackageList.txt
  dep/argon2/CMakeLists.txt
  dep/argon2/LICENSE
  dep/argon2/argon2/argon2.c
  dep/argon2/argon2/argon2.h
  dep/argon2/argon2/blake2/blake2-impl.h
  dep/argon2/argon2/blake2/blake2.h
  dep/argon2/argon2/blake2/blake2b.c
  dep/argon2/argon2/blake2/blamka-round-opt.h
  dep/argon2/argon2/blake2/blamka-round-ref.h
  dep/argon2/argon2/core.c
  dep/argon2/argon2/core.h
  dep/argon2/argon2/encoding.c
  dep/argon2/argon2/encoding.h
  dep/argon2/argon2/opt.c
  sql/base/auth_database.sql
  sql/updates/auth/3.3.5/2019_08_10_00_auth.sql
  sql/updates/auth/3.3.5/2019_08_10_01_auth.sql
  sql/updates/world/3.3.5/2019_08_10_01_world.sql
  src/common/CMakeLists.txt
  src/common/Cryptography/AES.cpp
  src/common/Cryptography/AES.h
  src/common/Cryptography/Argon2.cpp
  src/common/Cryptography/Argon2.h
  src/common/Cryptography/BigNumber.cpp
  src/common/Cryptography/BigNumber.h
  src/common/Cryptography/CryptoGenerics.h
  src/common/Cryptography/TOTP.cpp
  src/common/Cryptography/TOTP.h
  src/common/Encoding/Base32.cpp
  src/common/Encoding/Base32.h
  src/common/Encoding/Base64.cpp
  src/common/Encoding/Base64.h
  src/common/Encoding/BaseEncoding.h
  src/common/Utilities/advstd.h
  src/server/authserver/Authentication/TOTP.cpp
  src/server/authserver/Main.cpp
  src/server/authserver/Server/AuthSession.cpp
  src/server/authserver/Server/AuthSession.h
  src/server/authserver/authserver.conf.dist
  src/server/database/Database/Implementation/LoginDatabase.cpp
  src/server/database/Database/Implementation/LoginDatabase.h
  src/server/scripts/Commands/cs_account.cpp
  src/server/shared/Secrets/SecretMgr.cpp
  src/server/shared/Secrets/SecretMgr.h
  src/server/shared/SharedDefines.cpp
  src/server/shared/SharedDefines.h
  src/server/worldserver/Main.cpp
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Database

#23710 Core/Spells: Fixed SPELL_EFFECT_DISPEL when target has 2 spells with same ID
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells

#23714 Scripts/Spells: Port druid scripts to new script registration syntax (3 of 3)
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-3.3.5a

#23467 Core/Spells: implement SPELL_AURA_OVERRIDE_AUTOATTACK_WITH_MELEE_SPELL
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-master, Comp-Core, Feedback-PatchFix, Sub-Spells

#22954 Core/Misc: Wisp Spirit minor edit
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#23696 Scripts/Spells: Port druid scripts to new script registration syntax (2 of 3)
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-3.3.5a

#23725 Scripts/Spells: Code style adjustments for druid scripts
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-3.3.5a

#23726 Scripts/Spells: Code style adjustments for druid scripts (final?)
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-3.3.5a

#23697 Core/Spells: Fixed warlock's Banish cancel if target was already banished
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellScript.cpp
  src/server/game/Spells/SpellScript.h
  src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_forgemaster_garfrost.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp
  src/server/scripts/Spells/spell_rogue.cpp
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-3.3.5a

#23636 Core/PacketIO: updated SMSG_PLAY_SOUND, SMSG_PLAY_MUSIC and SMSG_PLAY_OBJECT_SOUND
  src/server/game/Battlefield/Battlefield.cpp
  src/server/game/Battlefield/Battlefield.h
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Battlegrounds/Battleground.h
  src/server/game/Battlegrounds/BattlegroundMgr.cpp
  src/server/game/Battlegrounds/BattlegroundMgr.h
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Maps/Map.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Spells/SpellEffects.cpp
  src/server/game/Texts/CreatureTextMgr.cpp
  src/server/game/Texts/CreatureTextMgr.h
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#19902 Scripts/Broken Isles: Warrior Order Hall - some NPC spawns and scripts
  sql/updates/world/master/2019_08_25_00_world.sql
  src/server/game/Entities/Unit/Unit.h
  src/server/scripts/BrokenIsles/broken_isles_script_loader.cpp
  src/server/scripts/BrokenIsles/zone_orderhall_warrior.cpp
Labels: Branch-master, Comp-C++Script, Feedback-PatchFix, Sub-Spawns

#23719 [3.3.5] Fix spell_area not checking for zoneID for quests
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Spells/SpellMgr.cpp
  src/server/game/Spells/SpellMgr.h
Labels: Branch-3.3.5a

#21316 Core/Player: implement QUEST_FLAGS_PLAYER_CAST_ON_ACCEPT/_COMPLETE
  src/server/game/Entities/Creature/GossipDef.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Handlers/QuestHandler.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellInfo.h
Labels: Branch-master, Comp-Core, Feedback-PatchFix, Sub-Player

#21336 Core/SmartScripts: new SAI action SMART_ACTION_SET_MOVEMENT_SPEED
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master, Comp-Core, Feedback-PatchFix, Sub-ScriptingEngine
