Repository TrinityCore/TrinityCore, pull requests merged in 2019-07, with the labels that each got.

#23547 Scripts/Spells: Dimensional Ripper - Everlook
  sql/updates/world/3.3.5/9999_99_99_99_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_item.cpp
Labels: Branch-3.3.5a

#23520 Core/Player: add helper methods GetNativeGender/SetNativeGender/SetGender
  src/server/game/Achievements/AchievementMgr.cpp
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Entities/Pet/Pet.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Guilds/Guild.cpp
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/SpellMgr.cpp
  src/server/game/Storages/WhoListStorage.cpp
  src/server/scripts/Commands/cs_character.cpp
  src/server/scripts/Commands/cs_misc.cpp
  src/server/scripts/Commands/cs_modify.cpp
  src/server/scripts/Commands/cs_titles.cpp
  src/server/scripts/Spells/spell_generic.cpp
  src/server/scripts/Spells/spell_holiday.cpp
  src/server/scripts/Spells/spell_item.cpp
  src/server/scripts/Spells/spell_quest.cpp
  src/server/scripts/World/go_scripts.cpp
Labels: Branch-3.3.5a

#23552 Core/Reputation: don't allow quests to reward Honor Hold/Alliance Vanguard reputation to Horde players or Thrallmar reputation to Alliance players
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Reputation/ReputationMgr.cpp
  src/server/game/Reputation/ReputationMgr.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-FixHack, Priority-Low, Sub-Quests

#23495 Core/Quest: fix money reward for quests turned in at level cap
  src/server/game/Entities/Creature/GossipDef.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Handlers/LFGHandler.cpp
  src/server/game/Quests/QuestDef.cpp
  src/server/game/Quests/QuestDef.h
  src/server/scripts/Commands/cs_quest.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Priority-Low, Sub-Quests

#23338 Core/Quest: Fix repeatable quest mark
  src/server/game/Entities/Creature/GossipDef.cpp
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Priority-Cosmetic, Sub-Quests

#23546 Local-only mode fix
  src/common/Asio/Resolver.h
Labels: Branch-3.3.5a

#23555 Core/Unit: Implement more helper methods
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Pet/Pet.cpp
  src/server/game/Entities/Pet/Pet.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Handlers/SpellHandler.cpp
  src/server/scripts/Commands/cs_character.cpp
  src/server/scripts/Commands/cs_reset.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a

#23527 Core/Conditions: allow spellclick conditions to properly work for aura apply/remove
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Conditions/ConditionMgr.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Groups/Group.cpp
Labels: Branch-3.3.5a

#21816 Scripts/BlackrockDepths: fix Ironhand Guardian
  sql/updates/world/3.3.5/2019_07_05_03_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_magmus.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-FixOutdatedMissingWIP, Sub-Instances

#21754 Core/Battleground: implement previous opponent timer on Arena queue
  src/server/game/Battlegrounds/Arena.cpp
  src/server/game/Battlegrounds/ArenaTeam.cpp
  src/server/game/Battlegrounds/ArenaTeam.h
  src/server/game/Battlegrounds/BattlegroundQueue.cpp
  src/server/game/Battlegrounds/BattlegroundQueue.h
  src/server/game/Handlers/BattleGroundHandler.cpp
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a, Comp-Core, Feedback-FixOutdatedMissingWIP, Sub-PvP-Zones

#23519 Core/Misc: More coding standards
  src/server/game/AuctionHouseBot/AuctionHouseBotBuyer.h
  src/server/game/Battlefield/Battlefield.cpp
  src/server/game/Battlegrounds/ArenaTeam.h
  src/server/game/Battlegrounds/Battleground.h
  src/server/game/Battlegrounds/BattlegroundQueue.h
  src/server/game/Battlegrounds/Zones/BattlegroundAV.h
  src/server/game/Chat/Chat.h
  src/server/game/DungeonFinding/LFGMgr.h
  src/server/game/Entities/Item/Item.h
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Grids/Notifiers/GridNotifiers.h
  src/server/game/Groups/Group.h
  src/server/game/Guilds/Guild.h
  src/server/game/Loot/LootMgr.h
  src/server/game/Mails/Mail.h
  src/server/game/Movement/MovementGenerators/FlightPathMovementGenerator.cpp
  src/server/game/Movement/PathGenerator.h
  src/server/game/Movement/Spline/MoveSplineInitArgs.h
  src/server/game/OutdoorPvP/OutdoorPvPMgr.h
  src/server/game/Pools/PoolMgr.cpp
  src/server/game/Pools/PoolMgr.h
  src/server/game/Quests/QuestDef.h
  src/server/game/Reputation/ReputationMgr.h
  src/server/game/Server/WorldSession.cpp
  src/server/game/Spells/Auras/SpellAuras.h
  src/server/game/Spells/Spell.h
  src/server/game/Texts/CreatureTextMgr.h
  src/server/game/World/World.h
Labels: Branch-3.3.5a

#23566 Scripts/Commands: update wp commands to use orientation field from DB
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/scripts/Commands/cs_debug.cpp
  src/server/scripts/Commands/cs_wp.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Commands

#23300 Scripts/Blood Furnace: Broggok improvements
  src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp
  src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix, Sub-Instances

#23591 [3.3.5] Unified respawn table
  sql/base/characters_database.sql
  sql/updates/characters/3.3.5/2019_07_14_00_characters.sql
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/database/Database/Implementation/CharacterDatabase.h
  src/server/game/Instances/InstanceSaveMgr.cpp
  src/server/game/Maps/Map.cpp
  src/server/game/World/World.cpp
Labels: Branch-3.3.5a, Comp-Database, Sub-Spawns

#23575 Core/Movement: add a velocity argument for the spline chain meta table
  sql/updates/world/3.3.5/2019_07_18_00_world.sql
  src/server/game/Movement/MovementGenerators/SplineChainMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/SplineChainMovementGenerator.h
  src/server/game/Movement/Spline/SplineChain.h
  src/server/game/Scripting/ScriptSystem.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Movement

#23607 Core/Misc: added new files for future global predicates and implement…
  src/server/game/Miscellaneous/CommonPredicates.cpp
  src/server/game/Miscellaneous/CommonPredicates.h
Labels: Branch-3.3.5a

#23540 Core/Misc: Handle timezones for hour-specific events specifieds in worldserver.conf
  src/common/Utilities/Util.cpp
  src/common/Utilities/Util.h
  src/server/game/Instances/InstanceSaveMgr.cpp
  src/server/game/World/World.cpp
  src/server/scripts/World/boosted_xp.cpp
Labels: Branch-3.3.5a, Comp-Core

#23592 Core/Spells: Fixed SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK stacking
  sql/updates/world/3.3.5/2019_07_24_00_world.sql
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells

#23583 Core/Totems: update select display for shaman totems
  sql/updates/world/3.3.5/2019_XX_XX_00_world.sql
  src/server/game/Entities/Totem/Totem.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Spells/SpellEffects.cpp
  src/server/game/World/World.cpp
  src/server/scripts/Spells/spell_shaman.cpp
  src/server/shared/SharedDefines.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#23635 Core/PacketIO: Updated SMSG_OVERRIDE_LIGHT
  src/server/game/Maps/Map.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
Labels: Branch-3.3.5a

#23631 Scripts/Defines: cleanup some magic numbers in factions
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.h
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
  src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp
  src/server/scripts/EasternKingdoms/Uldaman/instance_uldaman.cpp
  src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp
  src/server/scripts/Kalimdor/zone_darkshore.cpp
  src/server/scripts/Kalimdor/zone_stonetalon_mountains.cpp
  src/server/scripts/Kalimdor/zone_tanaris.cpp
  src/server/scripts/Kalimdor/zone_the_barrens.cpp
  src/server/scripts/Kalimdor/zone_ungoro_crater.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Outland/BlackTemple/black_temple.h
  src/server/shared/SharedDefines.h
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23606 Core/Arenas: Remove doors in RL, NA and BE when arena has begun
  src/server/game/Battlegrounds/Zones/BattlegroundBE.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundBE.h
  src/server/game/Battlegrounds/Zones/BattlegroundNA.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundNA.h
  src/server/game/Battlegrounds/Zones/BattlegroundRL.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundRL.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#23619 Spells/Priest: Fix Power Infusion, shouldn't stack with Arcane Power (Mage)
  sql/updates/world/3.3.5/2019_07_25_00_world_335.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#23637 MSVC build error
  src/common/Utilities/TaskScheduler.h
Labels: Branch-3.3.5a

#23652 Client inspect
  src/server/game/Server/Packets/InspectPackets.cpp
  src/server/game/Server/Packets/InspectPackets.h
Labels: Branch-master

#23662 Core/RBAC: Fix changing security level
  src/server/game/Accounts/AccountMgr.cpp
Labels: Branch-3.3.5a
