Repository TrinityCore/TrinityCore, pull requests merged in 2020-01, with the labels that each got.

#24025 Fix fleeing speed to 66% run speed
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Movement/MotionMaster.cpp
  src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/PointMovementGenerator.h
  src/server/game/Movement/Spline/MoveSplineInit.cpp
Labels: Branch-3.3.5a

#24023 Core/Spells: Fix Sacred Shield (Paladin) absorb amount with ICC buff
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-3.3.5a

#24036 Core/PathGenerator: Fix path generator returning shortcuts when start and end are on the same polygon
  src/server/game/Movement/PathGenerator.cpp
  src/server/game/Spells/Spell.cpp
  src/tools/mmaps_generator/MapBuilder.cpp
  src/tools/mmaps_generator/MapBuilder.h
Labels: Branch-3.3.5a, Comp-Core, Sub-Maps/MMaps/Vmaps

#24046 Core/DynamicObjects: Restore the ability of DynamicObjects to be world objects
  src/server/game/Maps/Map.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#24048 Scripts/Spells: fix Turkey Timer duration
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a

#24055 Scripts/Ulduar: Attempt to fix Yogg-Saron not evading on wipe
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_yogg_saron.cpp
Labels: Branch-3.3.5a, Sub-Instances

#24059 Core/SAI: Fix SMART_ACTION_SET_MOVEMENT_SPEED behavior
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Branch-3.3.5a

#24058 Fixed PvP Combat timer never getting refreshed
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#24054 Core/Spells: SPELL_AURA_48 implementation
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Handlers/PetHandler.cpp
  src/server/game/Handlers/SpellHandler.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellMgr.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells

#24082 Scripts/Transitus Shield: Warmages
  sql/updates/world/3.3.5/2020_01_19_01_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix

#24084 Scripts/Violet Stand: Warmages
  sql/updates/world/3.3.5/2020_01_19_02_world.sql
  src/server/scripts/Northrend/northrend_script_loader.cpp
  src/server/scripts/Northrend/zone_crystalsong_forest.cpp
Labels: Branch-3.3.5a

#24075 Scripts/Quests: Reports from the Field
  src/server/scripts/Northrend/zone_howling_fjord.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Quests

#24062 Core/Gameobject: Rename GO_STATE_ACTIVE_ALTERNATIVE to GO_STATE_DESTROYED
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/scripts/EasternKingdoms/Deadmines/instance_deadmines.cpp
  src/server/scripts/Northrend/Gundrak/instance_gundrak.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
  src/server/shared/SharedDefines.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-GameObject

#24083 Core/PathGenerator: Fix path generator returning shortcuts when start and end are on the same polygon
  src/server/game/Movement/MovementGenerators/ConfusedMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
  src/server/game/Movement/PathGenerator.cpp
  src/server/game/Movement/PathGenerator.h
Labels: Branch-3.3.5a, Comp-Core, Sub-Maps/MMaps/Vmaps

#24068 Core/Movement: properly fix aura interrupts during movement
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
Labels: Branch-3.3.5a

#24093 Core/Movement: improved random movement pause handling to get closer to retail behaivior
  src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/RandomMovementGenerator.h
Labels: Branch-3.3.5a, Sub-Movement

#24074 Core/Object: Add infinite gob check
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/GameObject/GameObjectData.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#24085 Scripts/Borean Tundra: Plug the Sinkholes
  sql/updates/world/3.3.5/2020_01_26_03_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/World/item_scripts.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix

#24090 Scripts/Ebon Hold: How To Win Friends And Influence Enemies
  sql/updates/world/3.3.5/2020_01_26_04_world.sql
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter2.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix, Sub-Quests

#24052 Core/Players: properly re-use skills when re-learning a skill
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master
