Repository TrinityCore/TrinityCore, pull requests merged in 2020-03, with the labels that each got.

#24195 Core/AI: Make charmed creatures follow their owner
  src/server/game/AI/CoreAI/PetAI.cpp
  src/server/game/AI/CoreAI/PetAI.h
  src/server/game/AI/SmartScripts/SmartAI.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Movement

#24178 Core/Spell: Proper SPELL_EFFECT_PULL_TOWARDS_DEST implementation for players
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells

#24216 Core: build on aarch64 with gcc
  cmake/compiler/gcc/settings.cmake
  src/common/Utilities/SFMTRand.cpp
Labels: Branch-3.3.5a

#24221 Core/AI: Allow creatures to evade
  src/server/game/AI/CreatureAI.cpp
Labels: Branch-3.3.5a, Priority-High, help wanted

#24232 Core/Objects: MovePositonToFirstCollision will now use detour raycasts to determine terrain obstacles
  src/server/game/Entities/Object/Object.cpp
Labels: Branch-3.3.5a

#24248 Core/Database: Fix build with Maria DB on some distros
  src/server/database/Database/DatabaseWorkerPool.cpp
  src/server/database/Database/MySQLThreading.cpp
  src/server/database/Database/MySQLThreading.h
  src/server/scripts/Commands/cs_server.cpp
Labels: Branch-3.3.5a

#24063 Core/Spells: Pets need reset cooldown when summoned
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-PetMinion

#24223 Scripts/Ebon Hold: Improve cosmetics for q. The Gift That Keeps On Giving
  sql/updates/world/3.3.5/2020_03_07_03_world.sql
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Labels: Branch-3.3.5a

#24266 Core/Combat: Improve sanctuary combat stop
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#24215 Add bash script for extracting client files
  contrib/extractor.sh
Labels: Branch-3.3.5a

#24236 Core/PacketIO: update some combat packets to new system
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Handlers/CombatHandler.cpp
  src/server/game/Server/Packets/AllPackets.h
  src/server/game/Server/Packets/CombatPackets.cpp
  src/server/game/Server/Packets/CombatPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/Protocol/Opcodes.h
  src/server/game/Server/WorldSession.cpp
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a

#24278 Core/PacketIO: Updated and enabled CMSG_WORLD_TELEPORT (GM opcode)
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a

#24285 Scripts/BlackfathomDeeps: Summons of Blackfathom Deeps Events will now attack again.
  src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.cpp
Labels: Branch-3.3.5a

#24298 Scripts/BlackfathomDeeps: Morridune will now start his pathaction again.
  src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#24289 Core/Spells - DK: Fix Icy Clutch dispel
  sql/updates/world/3.3.5/2020_03_14_04_world.sql
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#24323 Scripts/Deadmines: Remove wrong spawn from Cannon Event
  src/server/scripts/EasternKingdoms/Deadmines/instance_deadmines.cpp
Labels: Branch-3.3.5a

#24320 Core/AI: Make critters flee as soon as engaged in combat and make them evade after they stop running in fear
  src/server/game/AI/CoreAI/PassiveAI.cpp
  src/server/game/AI/CoreAI/PassiveAI.h
  src/server/game/AI/CoreAI/UnitAI.h
  src/server/game/Movement/MotionMaster.cpp
  src/server/game/Movement/MovementGenerator.cpp
  src/server/game/Movement/MovementGenerator.h
Labels: Branch-3.3.5a

#24251 Core/Spell: SPELL_EFFECT_PULL_TOWARDS correction
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a, Feedback-FixOutdatedMissingWIP

#24327 Scripts/Blackwing Lair - Doors correction
  sql/updates/world/3.3.5/2020_03_20_00_world.sql
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/blackwing_lair.h
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_chromaggus.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#24345 Core/AI: Fix reset and interruption of non melee spells
  src/server/game/AI/CreatureAI.cpp
  src/server/game/AI/CreatureAI.h
Labels: Branch-3.3.5a, Comp-Core, Sub-AI

#24365 Core/Spells: fixed a possible client crash when casting pull towards dest spells with misc value 0
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a

#24312 Core/Packets: Updated SMSG_WORLD_STATE_UI_TIMER_UPDATE
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
Labels: Branch-3.3.5a

#24342 Core/PacketIO: updated "cancel" opcodes to new packet class
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Handlers/SpellHandler.cpp
  src/server/game/Server/Packets/SpellPackets.cpp
  src/server/game/Server/Packets/SpellPackets.h
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a

#24371 Make system notes in action_ip_logger.cpp user-friendly
  src/server/scripts/World/action_ip_logger.cpp
Labels: Branch-3.3.5a
