Repository TrinityCore/TrinityCore, pull requests merged in 2020-07, with the labels that each got.

#24900 Core/Spells: SPELL_AURA_MOD_MELEE_RANGED_HASTE should be negative if Basepoints are negative
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#24901 Core/Spells: SPELL_AURA_MELEE_SLOW should be negative if TargetType is enemy or Basepoints are negative
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#24902 Core/Spells: SPELL_AURA_MOD_HEALTH_REGEN_PERCENT should be negative if TargetType is enemy and Basepoints are negative
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#24911 Core/Gameobjects: Traps shouldn't ignore IsImmuneToNPC/IsImmuneToPC and IsInSanctuary rules if have owner
  src/server/game/Entities/Object/Object.cpp
Labels: Branch-3.3.5a

#24930 Core/Spells: Check a few aura effects for determining if should be negative
  sql/updates/world/3.3.5/2020_07_04_00_world.sql
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#24931 Core/Gameobjects: Improve IsValidAttackTarget faction check for traps that haven't owner or have NPC owner
  src/server/game/Entities/Object/Object.cpp
Labels: Branch-3.3.5a

#24913 Add locales to hotfix_blob
  sql/updates/hotfixes/master/2020_07_04_00_hotfixes.sql
  src/server/game/DataStores/DB2Stores.cpp
  src/server/game/DataStores/DB2Stores.h
  src/server/game/Handlers/HotfixHandler.cpp
Labels: Branch-master

#24895 Core/Unit: disable player skill upgrades in pvp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#24949 Core/Pools: Attempt to workaround pools being broken since 2015
  src/server/game/Pools/PoolMgr.cpp
Labels: Branch-3.3.5a

#24964 Core/Events: refactored battleground holiday assignments.
  sql/updates/world/3.3.5/2020_07_07_01_world.sql
  src/server/game/Battlegrounds/BattlegroundMgr.cpp
  src/server/game/Battlegrounds/BattlegroundMgr.h
  src/server/game/Events/GameEventMgr.cpp
  src/server/game/Events/GameEventMgr.h
Labels: Branch-3.3.5a

#24981 Core/Spells: implement GetHitCorpse helper for spell scripts
  src/server/game/Spells/SpellScript.cpp
  src/server/game/Spells/SpellScript.h
Labels: Branch-3.3.5a

#24969 Creature/Script: npc_blackfathom_deeps_event
  src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.cpp
  src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.h
Labels: Branch-3.3.5a

#24989 Core/Player: Limit leveling for expansions
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Handlers/ArenaTeamHandler.cpp
  src/server/game/Handlers/PetitionsHandler.cpp
  src/server/game/Quests/QuestDef.cpp
  src/server/shared/SharedDefines.h
Labels: Branch-3.3.5a

#25008 Core/Spells: Use correct SpellEntry field for Amplitude
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#25007 Fix some compiler warnings reported by GCC
  src/server/game/AI/ScriptedAI/ScriptedEscortAI.cpp
  src/server/game/AI/ScriptedAI/ScriptedFollowerAI.cpp
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_salramm_the_fleshcrafter.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/npc_arthas.cpp
  src/server/scripts/Northrend/FrozenHalls/PitOfSaron/instance_pit_of_saron.cpp
  src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp
  src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp
Labels: Branch-3.3.5a

#24997 Core/Spells: Implement SPELL_EFFECT_ACTIVATE_OBJECT. (#23)
  sql/updates/world/3.3.5/2020_99_99_00_world.sql
  sql/updates/world/3.3.5/2020_99_99_01.sql
  src/server/game/DataStores/DBCStores.cpp
  src/server/game/DataStores/DBCStores.h
  src/server/game/Entities/GameObject/GameObject.h
  src/server/game/Entities/GameObject/GameObjectData.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
  src/server/shared/DataStores/DBCStructure.h
  src/server/shared/DataStores/DBCfmt.h
Labels: Branch-3.3.5a

#25004 Core/Spells: Check a few aura effects for determining if should be negative
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#24998 Scripts/Kologarn: Fix another "stuck in combat" issue
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
Labels: Branch-3.3.5a

#25015 Core/BG: Use std::chrono::duration overloads of EventMap
  src/server/game/Battlegrounds/Zones/BattlegroundBE.h
  src/server/game/Battlegrounds/Zones/BattlegroundDS.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundDS.h
  src/server/game/Battlegrounds/Zones/BattlegroundNA.h
  src/server/game/Battlegrounds/Zones/BattlegroundRL.h
Labels: Branch-3.3.5a

#25016 Scripts/Kalimdor: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_chrono_lord_epoch.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp
  src/server/scripts/Kalimdor/OnyxiasLair/boss_onyxia.cpp
  src/server/scripts/Kalimdor/RazorfenDowns/boss_mordresh_fire_eye.cpp
  src/server/scripts/Kalimdor/RazorfenDowns/razorfen_downs.cpp
  src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_buru.cpp
  src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_skeram.cpp
  src/server/scripts/Kalimdor/boss_azuregos.cpp
  src/server/scripts/Kalimdor/zone_bloodmyst_isle.cpp
  src/server/scripts/Kalimdor/zone_moonglade.cpp
  src/server/scripts/Kalimdor/zone_orgrimmar.cpp
Labels: Branch-3.3.5a

#25018 Scripts/BlackrockMountain: Use std::chrono::duration overloads of Eve…
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_general_angerforge.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_magmus.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_drakkisath.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_highlord_omokk.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_mother_smolderweb.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_pyroguard_emberseer.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_rend_blackhand.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_shadow_hunter_voshgajin.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_warmaster_voone.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_chromaggus.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_vaelastrasz.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_majordomo_executus.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_ragnaros.cpp
Labels: Branch-3.3.5a

#25019 Scripts/EasternKingdoms: Use std::chrono::duration overloads of EventMap
  src/server/scripts/EasternKingdoms/AlteracValley/boss_drekthar.cpp
  src/server/scripts/EasternKingdoms/AlteracValley/boss_galvangar.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_doctor_theolen_krastinov.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_kirtonos_the_herald.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_ras_frostwhisper.cpp
  src/server/scripts/EasternKingdoms/Stratholme/boss_maleki_the_pallid.cpp
  src/server/scripts/EasternKingdoms/Stratholme/boss_postmaster_malown.cpp
  src/server/scripts/EasternKingdoms/Stratholme/instance_stratholme.cpp
  src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
  src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_marli.cpp
  src/server/scripts/EasternKingdoms/zone_duskwood.cpp
  src/server/scripts/EasternKingdoms/zone_undercity.cpp
Labels: Branch-3.3.5a

#25020 Scripts/ToC: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp
Labels: Branch-3.3.5a

#25021 Scripts/Northrend: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/zone_dragonblight.cpp
  src/server/scripts/Northrend/zone_grizzly_hills.cpp
  src/server/scripts/Northrend/zone_howling_fjord.cpp
  src/server/scripts/Northrend/zone_icecrown.cpp
  src/server/scripts/Northrend/zone_storm_peaks.cpp
  src/server/scripts/Northrend/zone_zuldrak.cpp
Labels: Branch-3.3.5a

#25022 Scripts/Outland: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Outland/boss_doomlord_kazzak.cpp
  src/server/scripts/Outland/boss_doomwalker.cpp
  src/server/scripts/Outland/zone_hellfire_peninsula.cpp
Labels: Branch-3.3.5a

#25023 Scripts/Auchindoun: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Outland/Auchindoun/ManaTombs/boss_nexusprince_shaffar.cpp
  src/server/scripts/Outland/Auchindoun/ManaTombs/boss_pandemonius.cpp
  src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_darkweaver_syth.cpp
  src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_blackheart_the_inciter.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_grandmaster_vorpil.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
Labels: Branch-3.3.5a

#25026 Scripts/AzjolNerub: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/AzjolNerub/Ahnkahet/boss_prince_taldaram.cpp
  src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_anubarak.cpp
Labels: Branch-3.3.5a

#25024 Scripts/HellfireCitadel: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_the_maker.cpp
  src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_watchkeeper_gargolmar.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp
Labels: Branch-3.3.5a

#25025 Scripts/CoilfangReservoir: Use std::chrono::duration overloads of Eve…
  src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_hydromancer_thespia.cpp
  src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_quagmirran.cpp
Labels: Branch-3.3.5a

#25027 Scripts/ChamberOfAspects: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp
  src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/obsidian_sanctum.cpp
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/ruby_sanctum.cpp
Labels: Branch-3.3.5a

#25028 Scripts/DraktharonKeep: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/DraktharonKeep/boss_king_dred.cpp
Labels: Branch-3.3.5a

#25029 Scripts/FrozenHalls: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_devourer_of_souls.cpp
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/forge_of_souls.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp
  src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_forgemaster_garfrost.cpp
  src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp
  src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_scourgelord_tyrannus.cpp
  src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp
Labels: Branch-3.3.5a

#25030 Scripts/Gundrak: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/Gundrak/boss_eck.cpp
  src/server/scripts/Northrend/Gundrak/gundrak.h
Labels: Branch-3.3.5a

#25031 Scripts/IoC: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/IsleOfConquest/boss_ioc_horde_alliance.cpp
Labels: Branch-3.3.5a

#25032 Scripts/Naxxramas: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp
Labels: Branch-3.3.5a

#25033 Scripts/Nexus: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
  src/server/scripts/Northrend/Nexus/Nexus/boss_keristrasza.cpp
  src/server/scripts/Northrend/Nexus/Nexus/boss_nexus_commanders.cpp
  src/server/scripts/Northrend/Nexus/Oculus/boss_drakos.cpp
  src/server/scripts/Northrend/Nexus/Oculus/boss_urom.cpp
  src/server/scripts/Northrend/Nexus/Oculus/instance_oculus.cpp
  src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp
Labels: Branch-3.3.5a

#25035 Scripts/Ulduar: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_loken.cpp
  src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_volkhan.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_freya.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_hodir.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_yogg_saron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
Labels: Branch-3.3.5a

#25037 Core/CombatAI: Use std::chrono::duration overloads of EventMap
  src/server/game/AI/CoreAI/CombatAI.cpp
Labels: Branch-3.3.5a

#25038 Scripts/MagistersTerrace: Use std::chrono::duration overloads of Even…
  src/server/scripts/EasternKingdoms/MagistersTerrace/boss_selin_fireheart.cpp
Labels: Branch-3.3.5a

#25039 Scripts/UtgardeKeep: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_ingvar_the_plunderer.cpp
  src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp
  src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_ymiron.cpp
Labels: Branch-3.3.5a

#25040 Scripts/TempestKeep: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
  src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_gyrokill.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_ironhand.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_wrath_scryer_soccothrates.cpp
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_zereketh_the_unbound.cpp
  src/server/scripts/Outland/TempestKeep/botanica/boss_commander_sarannis.cpp
  src/server/scripts/Outland/TempestKeep/botanica/boss_thorngrin_the_tender.cpp
Labels: Branch-3.3.5a

#25036 Scripts/ICC: Use std::chrono::duration overloads of EventMap (Part 1)
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_festergut.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_sister_svalna.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
Labels: Branch-3.3.5a

#25041 Scripts/ICC: Use std::chrono::duration overloads of EventMap (Part 2)
  src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp
Labels: Branch-3.3.5a

#25017 Scripts/World+Pet: Use std::chrono::duration overloads of EventMap
  src/server/scripts/Pet/pet_shaman.cpp
  src/server/scripts/World/boss_emerald_dragons.cpp
  src/server/scripts/World/go_scripts.cpp
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-3.3.5a

#24922 Core/PacketIO: Updated corpse related packet structures
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a, Feedback-FixOutdatedMissingWIP

#25049 Core/Util: Remove EventMap's non-std::chrono::duration based interface
  src/common/Utilities/EventMap.cpp
  src/common/Utilities/EventMap.h
Labels: Branch-3.3.5a

#25047 Core/Misc: Replace boost::optional with std::optional
  dep/boost/CMakeLists.txt
  src/common/Collision/DynamicTree.cpp
  src/common/Collision/Management/VMapManager2.cpp
  src/common/Utilities/Optional.h
  src/common/Utilities/OptionalFwd.h
  src/common/Utilities/TaskScheduler.cpp
  src/common/Utilities/TaskScheduler.h
  src/server/game/Chat/ChatCommands/ChatCommand.h
  src/server/game/Entities/Object/Object.h
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Maps/Map.cpp
  src/server/game/Movement/MovementGenerators/ChaseMovementGenerator.cpp
  src/server/game/Spells/Spell.cpp
  src/server/scripts/Commands/cs_account.cpp
  src/server/scripts/Commands/cs_debug.cpp
  src/server/scripts/Commands/cs_go.cpp
Labels: Branch-3.3.5a

#25051 Misc: Remove some unneeded/duplicated includes
  src/server/game/Handlers/NPCHandler.cpp
  src/server/game/Maps/MapManager.cpp
  src/server/game/Spells/SpellScript.cpp
  src/server/game/Tools/PlayerDump.cpp
  src/server/scripts/World/npcs_special.cpp
  src/tools/map_extractor/System.cpp
Labels: Branch-3.3.5a

#24260 doc(AUTHORS): fix SD2 link and add UDB
  AUTHORS
Labels: Branch-master

#25045 Core/Time: Rename GetGameTime{System, Steady}Point methods
  src/common/Metric/Metric.h
  src/common/Utilities/Duration.h
  src/server/game/Achievements/AchievementMgr.cpp
  src/server/game/Achievements/AchievementMgr.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Server/WorldPacket.h
  src/server/game/Server/WorldSocket.h
  src/server/game/Spells/Auras/SpellAuras.cpp
  src/server/game/Spells/Auras/SpellAuras.h
  src/server/game/Spells/SpellHistory.cpp
  src/server/game/Spells/SpellHistory.h
  src/server/game/Time/GameTime.cpp
  src/server/game/Time/GameTime.h
  src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
  src/server/scripts/Spells/spell_druid.cpp
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-3.3.5a

#25067 Core/Metric: Log Map::Update() times
  contrib/grafana/1_General.json
  src/common/Metric/Metric.cpp
  src/common/Metric/Metric.h
  src/server/game/Maps/MapUpdater.cpp
Labels: Branch-3.3.5a

#25072 Core/Battlefield: Fix a crash when initializing the map
  src/server/game/Battlefield/Zones/BattlefieldWG.cpp
Labels: Branch-master

#25069 Dep/Boost: Set boost version to 1.67 on *nix and 1.70 on Windows
  dep/boost/CMakeLists.txt
Labels: Branch-3.3.5a

#24328 Core/Misc: Replace boost::shared_mutex with std::shared_mutex
  src/server/game/Globals/ObjectAccessor.cpp
  src/server/game/Globals/ObjectAccessor.h
  src/server/game/Loot/LootItemStorage.cpp
  src/server/game/Loot/LootItemStorage.h
  src/server/game/Warden/WardenCheckMgr.cpp
  src/server/game/Warden/WardenCheckMgr.h
  src/server/game/Warden/WardenWin.cpp
  src/server/scripts/Commands/cs_gm.cpp
  src/server/scripts/Commands/cs_reset.cpp
Labels: Branch-3.3.5a

#25054 Misc: Use [[fallthrough]] attribute instead of comment to mark intentional fallthroughs
  src/common/Logging/AppenderConsole.cpp
  src/server/database/Database/MySQLConnection.cpp
  src/server/database/Updater/UpdateFetcher.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/DungeonFinding/LFGGroupData.cpp
  src/server/game/DungeonFinding/LFGMgr.cpp
  src/server/game/DungeonFinding/LFGPlayerData.cpp
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Handlers/LFGHandler.cpp
  src/server/game/Handlers/PetHandler.cpp
  src/server/game/Spells/Auras/SpellAuras.cpp
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/SpellEffects.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_salramm_the_fleshcrafter.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
  src/server/scripts/Kalimdor/zone_azuremyst_isle.cpp
  src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_general_zarithrian.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/instance_halls_of_reflection.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_sister_svalna.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
  src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
  src/server/scripts/Northrend/VioletHold/instance_violet_hold.cpp
  src/server/scripts/Northrend/zone_sholazar_basin.cpp
  src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.cpp
Labels: Branch-3.3.5a

#15782 Core/Threads: Replace Boost TLS with C++11 one
  src/common/Utilities/Random.cpp
Labels: Branch-3.3.5a

#25076 Dep/Boost: Remove unused thread library
  dep/boost/CMakeLists.txt
Labels: Branch-3.3.5a

#25088 TaskScheduler: use randtime instead of custom implementation
  src/common/Utilities/TaskScheduler.h
Labels: Branch-3.3.5a

#25090 Core/Scripts: Fix timing issue of EVENT_FLY_TO_RANDOM_PILLAR during Illidan encounter
  src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
Labels: Branch-3.3.5a

#25092 EventMap: Remove GetNextEventTime and GetTimer methods
  src/common/Utilities/EventMap.cpp
  src/common/Utilities/EventMap.h
Labels: Branch-3.3.5a

#25086 Core/Combat: Disable triggers entering combat
  sql/updates/world/3.3.5/2020_07_22_00_world.sql
  src/server/game/Combat/CombatManager.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
Labels: Branch-3.3.5a

#25096 Updated CONTRIBUTING.md to fix broken links.
  CONTRIBUTING.md
Labels: Branch-master

#25098 Core/Metric: Add more metrics about World::Update() loop
  cmake/options.cmake
  cmake/showoptions.cmake
  contrib/grafana/4_Performance_profiling.json
  sql/updates/world/3.3.5/2020_07_24_00_world.sql
  src/common/Metric/Metric.cpp
  src/common/Metric/Metric.h
  src/server/game/Accounts/RBAC.h
  src/server/game/Time/UpdateTime.cpp
  src/server/game/Time/UpdateTime.h
  src/server/game/World/World.cpp
  src/server/scripts/Commands/cs_server.cpp
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a

#25102 Scripts/Borean Tundra: duplicate comment text
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a

#25110 common/Crypto: ifdef OpenSSL thread locking code
  src/common/Cryptography/OpenSSLCrypto.cpp
  src/common/Cryptography/OpenSSLCrypto.h
Labels: Branch-3.3.5a

#25109 Build: Add option to use gold linker
  cmake/options.cmake
  cmake/platform/unix/settings.cmake
Labels: Branch-3.3.5a

#25117 Core/Utilities: Add custom _days chrono literal
  src/common/Utilities/Duration.h
Labels: Branch-3.3.5a

#25118 Core/InstanceScript: std::chrono-ify DoRespawnGameObject
  src/server/game/Instances/InstanceScript.cpp
  src/server/game/Instances/InstanceScript.h
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_tomb_of_seven.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/instance_molten_core.cpp
  src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp
Labels: Branch-3.3.5a

#25119 Core/BossAI: Remove _DespawnAtEvade(uint32, Creature*) overload
  src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
  src/server/game/AI/ScriptedAI/ScriptedCreature.h
  src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
Labels: Branch-3.3.5a

#25120 Core/ScriptedAI: std::chrono-ify DoSpawnCreature
  src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
  src/server/game/AI/ScriptedAI/ScriptedCreature.h
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_ambassador_flamelash.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_general_angerforge.cpp
  src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_headless_horseman.cpp
  src/server/scripts/EasternKingdoms/Stratholme/boss_nerubenkan.cpp
  src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
  src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp
  src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
  src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
  src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
  src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp
  src/server/scripts/Kalimdor/Maraudon/boss_noxxion.cpp
  src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp
  src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_fankriss.cpp
  src/server/scripts/Kalimdor/zone_darkshore.cpp
  src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_sjonnir.cpp
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_hydross_the_unstable.cpp
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp
  src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_mekgineer_steamrigger.cpp
  src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
  src/server/scripts/Outland/zone_hellfire_peninsula.cpp
  src/server/scripts/Outland/zone_shadowmoon_valley.cpp
Labels: Branch-3.3.5a

#25132 Handle GAMEOBJECT_TYPE_UI_LINK spellFocus
  src/server/game/Entities/GameObject/GameObjectData.h
  src/server/game/Grids/Notifiers/GridNotifiers.h
Labels: Branch-master

#25124 Scripts/EasternKingdoms: Use std::chrono overload of Creature::DespawnOrUnsummon
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_rend_blackhand.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_kirtonos_the_herald.cpp
  src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp
  src/server/scripts/EasternKingdoms/zone_isle_of_queldanas.cpp
Labels: Branch-3.3.5a

#25127 Core/Misc: Use std::chrono overload of Creature::DespawnOrUnsummon
  src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
  src/server/game/AI/ScriptedAI/ScriptedEscortAI.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Maps/MapScripts.cpp
Labels: Branch-3.3.5a

#25128 Scripts/Northrend: Use std::chrono overload of Creature::DespawnOrUnsummon
  src/server/scripts/Northrend/AzjolNerub/Ahnkahet/boss_prince_taldaram.cpp
  src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/obsidian_sanctum.cpp
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/instance_halls_of_reflection.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_sister_svalna.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
  src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp
  src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp
  src/server/scripts/Northrend/Naxxramas/boss_maexxna.cpp
  src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp
  src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp
  src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
  src/server/scripts/Northrend/Nexus/Oculus/boss_drakos.cpp
  src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_freya.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_hodir.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_yogg_saron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.h
  src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_ingvar_the_plunderer.cpp
  src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_keleseth.cpp
  src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp
  src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp
  src/server/scripts/Northrend/VioletHold/boss_ichoron.cpp
  src/server/scripts/Northrend/VioletHold/boss_xevozz.cpp
  src/server/scripts/Northrend/VioletHold/violet_hold.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Northrend/zone_dragonblight.cpp
  src/server/scripts/Northrend/zone_grizzly_hills.cpp
  src/server/scripts/Northrend/zone_icecrown.cpp
  src/server/scripts/Northrend/zone_zuldrak.cpp
Labels: Branch-3.3.5a

#25125 Scripts/World+Outland+Spells:: Use std::chrono overload of Creature::DespawnOrUnsummon
  src/server/scripts/Outland/zone_blades_edge_mountains.cpp
  src/server/scripts/Outland/zone_shadowmoon_valley.cpp
  src/server/scripts/Spells/spell_dk.cpp
  src/server/scripts/Spells/spell_quest.cpp
  src/server/scripts/World/boss_emerald_dragons.cpp
  src/server/scripts/World/go_scripts.cpp
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-3.3.5a

#25126 Scripts/Kalimdor: Use std::chrono overload of Creature::DespawnOrUnsummon
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_infinite_corruptor.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/instance_culling_of_stratholme.cpp
  src/server/scripts/Kalimdor/RazorfenDowns/razorfen_downs.cpp
  src/server/scripts/Kalimdor/zone_desolace.cpp
  src/server/scripts/Kalimdor/zone_orgrimmar.cpp
  src/server/scripts/Kalimdor/zone_winterspring.cpp
Labels: Branch-3.3.5a

#25140 Core/Creature: Remove non-std::chrono overload of DespawnOrUnsummon
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/npc_arthas.cpp
  src/server/scripts/Outland/zone_netherstorm.cpp
Labels: Branch-3.3.5a

#25136 Core/Metric: Add new cmake option WITH_DETAILED_METRICS to enable more metrics
  cmake/options.cmake
  cmake/showoptions.cmake
  contrib/grafana/4_Performance_profiling.json
  src/common/Metric/Metric.h
  src/server/game/World/World.cpp
Labels: Branch-3.3.5a

#25145 Core/WorldObject: Replace non-std::chrono SummonTrigger overloads
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/scripts/EasternKingdoms/Gnomeregan/gnomeregan.cpp
  src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
  src/server/scripts/Northrend/zone_wintergrasp.cpp
Labels: Branch-3.3.5a

#25144 Core/WorldObject: Replace non-std::chrono SummonGameObject overloads
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/scripts/Commands/cs_gobject.cpp
  src/server/scripts/EasternKingdoms/Gnomeregan/gnomeregan.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
  src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
  src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
  src/server/scripts/Events/fireworks_show.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
  src/server/scripts/Kalimdor/RazorfenDowns/razorfen_downs.cpp
  src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp
  src/server/scripts/Kalimdor/zone_bloodmyst_isle.cpp
  src/server/scripts/Kalimdor/zone_silithus.cpp
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp
  src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp
  src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Northrend/zone_sholazar_basin.cpp
  src/server/scripts/Northrend/zone_storm_peaks.cpp
  src/server/scripts/Outland/BlackTemple/boss_warlord_najentus.cpp
  src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_ahune.cpp
  src/server/scripts/Outland/zone_blades_edge_mountains.cpp
  src/server/scripts/Spells/spell_item.cpp
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-3.3.5a

#25153 Core/Metric: Log detailed metrics about each opcode handler
  contrib/grafana/2_Maps.json
  contrib/grafana/3_Network.json
  contrib/grafana/4_Performance_profiling.json
  src/common/Metric/Metric.cpp
  src/common/Metric/Metric.h
  src/server/game/Server/WorldSession.cpp
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a

#25155 Core/CreatureAI: std::chrono-ify DoSummon* methods
  src/server/game/AI/CreatureAI.cpp
  src/server/game/AI/CreatureAI.h
  src/server/scripts/EasternKingdoms/Deadmines/boss_vancleef.cpp
  src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp
  src/server/scripts/EasternKingdoms/Stratholme/stratholme.cpp
  src/server/scripts/EasternKingdoms/zone_hinterlands.cpp
  src/server/scripts/EasternKingdoms/zone_undercity.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.cpp
  src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_anubarak.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp
  src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp
  src/server/scripts/Northrend/Naxxramas/boss_maexxna.cpp
  src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp
  src/server/scripts/Northrend/VioletHold/violet_hold.cpp
  src/server/scripts/Outland/zone_shadowmoon_valley.cpp
Labels: Branch-3.3.5a

#24807 Scripts/Quest: Force of Neltharaku quest credit
  sql/updates/world/3.3.5/2020_07_29_00_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Outland/zone_shadowmoon_valley.cpp
Labels: Branch-3.3.5a

#25084 Core/Loot: Prevent loot already looted item
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#25108 Core/SAI: Ignore SAI while evading
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Branch-3.3.5a

#25107 Scripts/Deadmines: Doors after Rhahk'Zor, Sneed and Gilnid
  sql/updates/world/3.3.5/2020_07_30_00_world.sql
  src/server/scripts/EasternKingdoms/Deadmines/boss_vancleef.cpp
  src/server/scripts/EasternKingdoms/Deadmines/deadmines.h
  src/server/scripts/EasternKingdoms/Deadmines/instance_deadmines.cpp
Labels: Branch-3.3.5a

#25174 Log sync db queries in World::Update() loop
  src/server/database/Database/DatabaseWorkerPool.cpp
  src/server/database/Database/DatabaseWorkerPool.h
  src/server/game/Maps/MapUpdater.cpp
  src/server/worldserver/Main.cpp
Labels: Branch-3.3.5a

#25175 CI/CircleCI: Move codestyle and sql checks to their own step
  .circleci/config.yml
Labels: Branch-3.3.5a

#25177 Scripts/BlackrockSprie: Small correction to Blackhand Incarcerator Creaturescript
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_pyroguard_emberseer.cpp
Labels: Branch-3.3.5a

#25137 Allow config settings to be optional
  src/common/Configuration/Config.cpp
  src/common/Configuration/Config.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#25178 Core/Misc: Fix static analysis issues
  src/common/Logging/Log.cpp
  src/common/Logging/Log.h
  src/common/Utilities/StartProcess.cpp
  src/server/game/Calendar/CalendarMgr.cpp
  src/server/game/Instances/InstanceScript.h
  src/server/game/Maps/Map.cpp
  src/server/game/Movement/MovementGenerators/FlightPathMovementGenerator.cpp
  src/server/game/Warden/WardenCheckMgr.cpp
  src/server/scripts/Commands/cs_server.cpp
  src/server/scripts/EasternKingdoms/Gnomeregan/gnomeregan.cpp
  src/server/scripts/EasternKingdoms/MagistersTerrace/instance_magisters_terrace.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.h
  src/server/scripts/Outland/zone_nagrand.cpp
  src/server/scripts/Outland/zone_shadowmoon_valley.cpp
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-3.3.5a
