Repository TrinityCore/TrinityCore, pull requests merged in 2020-06, with the labels that each got.

#24634 Core/Units: creatures will now also consider manually set movement flags for CanFly and CanHover
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Movement/PathGenerator.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-3.3.5a, Sub-Movement

#24736 Core/Spells: Fix ammo consumption
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#24717 Core/Misc: Fixed resistance calculate for Mutated Transformation and Twilight Bloodbolt
  sql/updates/world/3.3.5/2020_06_03_00_world.sql
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellMgr.cpp
  src/server/game/Spells/SpellScript.cpp
  src/server/game/Spells/SpellScript.h
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Core, Feedback-PatchFix

#24724 Scripts/Naxxramas: Noth the Plaguebringer improvements
  src/server/scripts/Northrend/Naxxramas/boss_noth.cpp
Labels: Branch-3.3.5a

#24763 Scripts/Naxxramas: Fix Kel'thuzad evade mode when he dies
  src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp
Labels: Branch-3.3.5a

#24783 Fix some hotfix code
  src/server/game/DataStores/DB2Stores.cpp
Labels: Branch-master

#24810 CMake: Prepare for target_precompile_headers
  CMakeLists.txt
  cmake/macros/FindPCHSupport.cmake
Labels: Branch-master

#24816 CP of CMake: Prepare for target_precompile_headers (#24810) for 3.3.5
  CMakeLists.txt
  cmake/macros/FindPCHSupport.cmake
Labels: Branch-3.3.5a

#24813 CMake: removed unused code for LIBSDIR entry
  cmake/platform/unix/settings.cmake
  cmake/showoptions.cmake
  doc/UnixInstall.txt
Labels: Branch-3.3.5a

#24821 Script/Spell: properly round damage of Seal of Righteousness (on-hit proc)
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-3.3.5a

#24817 Core/SmartAI: allow AreaTrigger SAI scripts to use the player triggering it as base object for actions and targeting
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
Labels: Branch-3.3.5a

#24802 Worldserver/CLI: console printf fix
  src/server/worldserver/CommandLine/CliRunnable.cpp
Labels: Branch-3.3.5a

#24765 Handle different slopes in mmaps
  dep/recastnavigation/Recast/Include/Recast.h
  dep/recastnavigation/Recast/Source/Recast.cpp
  src/common/Collision/Maps/MapDefines.h
  src/server/game/Movement/PathGenerator.cpp
  src/tools/mmaps_generator/MapBuilder.cpp
  src/tools/mmaps_generator/MapBuilder.h
  src/tools/mmaps_generator/PathGenerator.cpp
Labels: Branch-3.3.5a, Sub-Maps/MMaps/Vmaps, Sub-Movement

#24836 Core/Unit: SPELL_INTERRUPT_FLAG_ABORT_ON_DMG should only affect player spells
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#24837 Core/Spells: SPELL_AURA_MOD_ATTACK_POWER_PCT should be negative if TargetType or Basepoints are negative
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#24838 Core/Spells: Fix Shadowstep (Rogue), remove 4yd forced radius
  src/server/game/Spells/SpellMgr.cpp
Labels: Branch-3.3.5a

#24809 Log number of Creatures and GameObject per map
  contrib/grafana/1_General.json
  contrib/grafana/2_Maps.json
  contrib/grafana/3_Network.json
  src/common/Metric/Metric.cpp
  src/common/Metric/Metric.h
  src/server/game/Maps/Map.cpp
Labels: Branch-3.3.5a

#24788 DB/Account: update account_access table
  sql/base/auth_database.sql
  sql/updates/auth/3.3.5/2020_06_20_00_auth.sql
  sql/updates/world/3.3.5/2020_06_20_06_world.sql
  src/server/authserver/Server/AuthSession.cpp
  src/server/database/Database/Implementation/LoginDatabase.cpp
  src/server/database/Database/Implementation/LoginDatabase.h
  src/server/game/Accounts/RBAC.h
  src/server/game/Server/WorldSocket.cpp
  src/server/scripts/Commands/cs_account.cpp
Labels: Branch-3.3.5a

#24862 Core/Spells: SPELL_AURA_MOD_HEALING should be negative if TargetType is negative
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#24725 Script/ScarletEnclave: Eye of acherus now rooted at spawn
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Labels: Branch-3.3.5a

#24865 Core/EscortAI: set maximum distance allowed between player and escortee to default vision range
  src/server/game/AI/ScriptedAI/ScriptedEscortAI.h
Labels: Branch-3.3.5a

#24869 Replace Trinity::make_unique with std
  src/common/Common.h
  src/common/DataStores/DB2FileLoader.cpp
  src/common/Logging/Log.cpp
  src/common/Metric/Metric.cpp
  src/server/bnetserver/REST/LoginRESTService.cpp
  src/server/database/Database/DatabaseWorkerPool.cpp
  src/server/database/Database/MySQLConnection.cpp
  src/server/database/Updater/UpdateFetcher.cpp
  src/server/game/Entities/AreaTrigger/AreaTrigger.cpp
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/Player/CollectionMgr.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Groups/Group.cpp
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/game/Scripting/ScriptReloadMgr.cpp
  src/server/game/Server/Packets/AuthenticationPackets.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/WorldSession.cpp
  src/server/game/Spells/Spell.cpp
  src/server/shared/Realm/RealmList.cpp
  src/server/worldserver/Main.cpp
  src/tools/vmap4_extractor/wdtfile.cpp
Labels: Branch-master

#24879 CP of Core/Misc: Replace Trinity::make_unique with std (#24869)
  src/common/Common.h
  src/common/Logging/Log.cpp
  src/common/Metric/Metric.cpp
  src/server/database/Database/DatabaseWorkerPool.cpp
  src/server/database/Database/MySQLConnection.cpp
  src/server/database/Updater/UpdateFetcher.cpp
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Maps/Map.cpp
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/game/Scripting/ScriptReloadMgr.cpp
  src/server/game/Spells/Spell.cpp
  src/server/shared/DataStores/DBCDatabaseLoader.cpp
  src/server/shared/Realm/RealmList.cpp
  src/server/worldserver/Main.cpp
Labels: Branch-3.3.5a

#24872 CMake: indentation unification
  CMakeLists.txt
  PreLoad.cmake
  cmake/compiler/clang/settings.cmake
  cmake/compiler/gcc/settings.cmake
  cmake/compiler/icc/settings.cmake
  cmake/compiler/mingw/settings.cmake
  cmake/compiler/msvc/settings.cmake
  cmake/macros/AutoCollect.cmake
  cmake/macros/CheckBuildDir.cmake
  cmake/macros/ConfigureScripts.cmake
  cmake/macros/EnsureVersion.cmake
  cmake/macros/FindGit.cmake
  cmake/macros/FindMySQL.cmake
  cmake/macros/FindOpenSSL.cmake
  cmake/macros/FindPCHSupport.cmake
  cmake/macros/GroupSources.cmake
  cmake/options.cmake
  cmake/platform/unix/settings.cmake
  cmake/platform/win/settings.cmake
  cmake/showoptions.cmake
  dep/CMakeLists.txt
  src/common/CMakeLists.txt
  src/server/authserver/CMakeLists.txt
  src/server/database/CMakeLists.txt
  src/server/game/CMakeLists.txt
  src/server/scripts/CMakeLists.txt
  src/server/shared/CMakeLists.txt
  src/server/worldserver/CMakeLists.txt
  src/tools/map_extractor/CMakeLists.txt
  src/tools/mmaps_generator/CMakeLists.txt
  src/tools/vmap4_assembler/CMakeLists.txt
  src/tools/vmap4_extractor/CMakeLists.txt
Labels: Branch-3.3.5a

#24819 Core/Spell: fix ammo consumption for Hunter's non-damaging spells
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#24864 Core/Spells: SPELL_AURA_PERIODIC_DUMMY should be negative if TargetType is enemy
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#24885 Script/Spell: fix Midsummer's Juggling Torch
  sql/updates/world/3.3.5/2020_06_24_01_world.sql
  src/server/scripts/Spells/spell_holiday.cpp
Labels: Branch-3.3.5a

#24874 Core/SAI: implement SMART_EVENT_SUMMONED_UNIT_DIES (82), useable by creatures and gameobjects
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/game/AI/SmartScripts/SmartAI.h
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#24877 Core/SAI: do not allow the waypoint pause timer to update while in combat
  src/server/game/AI/SmartScripts/SmartAI.cpp
Labels: Branch-3.3.5a

#24884 Core/Player: do not consider FLAG_EXTRA_NO_XP_AT_KILL or pet status when deciding if a creature counts as a "gives experience or honor" target
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#24871 Script/Creature: script Terokk's encounter
  sql/updates/world/3.3.5/2020_06_24_02_world.sql
  src/server/scripts/Outland/zone_terokkar_forest.cpp
Labels: Branch-3.3.5a

#24921 Core/Spells: implement corpse target type support and properly fix resurrections
  src/server/game/Entities/Object/Object.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a

#24886 Core/Skill: properly scale current value of hidden skills with player level
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a
