Repository TrinityCore/TrinityCore, pull requests merged in 2020-10, with the labels that each got.

#25518 Core/Units: prevent units z offset from dropping below map surface when disabling hovering
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#25524 Core/Aura: Fixed unsafe return from Aura::GetCaster()
  src/server/game/Spells/Auras/SpellAuras.cpp
Labels: Branch-3.3.5a

#25522 Core/Spells: unify OnSpellCastInterrupt and OnSuccessfulSpellCast hooks
  src/server/game/AI/CreatureAI.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
Labels: Branch-3.3.5a

#25520 Tools/MMapsGenerator: Add some more input parameters to improve mmaps load performances
  src/tools/mmaps_generator/MapBuilder.cpp
  src/tools/mmaps_generator/MapBuilder.h
  src/tools/mmaps_generator/PathGenerator.cpp
Labels: Branch-3.3.5a, Comp-Tools, Sub-Maps/MMaps/Vmaps

#25539 Core/PacketIO : add SMSG_INTERRUPT_POWER_REGEN
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/Protocol/Opcodes.h
Labels: Branch-master

#25530 Scripts/Ulduar: Implemented Realm First! Death's Demise
  sql/updates/world/3.3.5/2020_10_08_01_world.sql
  src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.h
Labels: Branch-3.3.5a

#25511 Core/Spells: Aura refresh improvements
  src/server/game/Spells/Auras/SpellAuras.cpp
  src/server/game/Spells/Auras/SpellAuras.h
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#25556 Scripts/IcecrownCitadel: Implemented Vampiric Might spell
  sql/updates/world/3.3.5/2020_10_11_00_world.sql
  src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#25557 Scripts/UtgardPinnacle: Implemented Beast's Mark
  sql/updates/world/3.3.5/2020_10_11_01_world.sql
  src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/utgarde_pinnacle.cpp
  src/server/scripts/Northrend/northrend_script_loader.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#25560 Script/Commands: .character changeaccount now kick the player before being transferred in case of being online
  src/server/scripts/Commands/cs_character.cpp
Labels: Branch-3.3.5a

#25565 Scripts/ICC: Fixed Chocking Gas killing Abomination
  sql/updates/world/3.3.5/2020_10_12_00_world.sql
  src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#25572 Scripts/ICC: Some fixes in Valkyr Shadowguard
  sql/updates/world/3.3.5/2020_10_14_00_world.sql
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#25581 CI/CircleCI: Authenticate to DockerHub when pulling the docker image
  .circleci/config.yml
Labels: Branch-3.3.5a

#25564 Game/Player: Fixed Backlash/Backdraft priority
  sql/updates/world/3.3.5/2040_18_51_00_world.sql
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells

#25613 Scripts/Stormwind City: Tyrion talks to player
  src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
Labels: Branch-3.3.5a

#25610 CI/GitHub: Switch to GCC 8
  .github/workflows/gcc-build.yml
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
Labels: Branch-3.3.5a

#25614 Scripts/ScarletMonastery: Headless Horseman Rewrite
  sql/updates/world/3.3.5/2020_10_26_00_world.sql.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_headless_horseman.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/instance_scarlet_monastery.cpp
  src/server/scripts/EasternKingdoms/ScarletMonastery/scarlet_monastery.h
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances
