Repository TrinityCore/TrinityCore, pull requests merged in 2020-02, with the labels that each got.

#24124 Scripts/The Barrens: Beaten Corpse
  sql/updates/world/3.3.5/2020_02_01_00_world.sql
  src/server/scripts/Kalimdor/zone_the_barrens.cpp
Labels: Branch-3.3.5a, Comp-Database, Feedback-PatchFix

#24117 Scripts/Borean Tundra: Iruk
  sql/updates/world/3.3.5/2020_02_01_01_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Comp-Database, Feedback-PatchFix

#24113 Core/Items: implement some helper methods for easier readability
  src/server/game/AuctionHouseBot/AuctionHouseBotSeller.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Item/Item.cpp
  src/server/game/Entities/Item/Item.h
  src/server/game/Entities/Item/ItemTemplate.cpp
  src/server/game/Entities/Item/ItemTemplate.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Groups/Group.cpp
  src/server/game/Handlers/AuctionHouseHandler.cpp
  src/server/game/Handlers/ItemHandler.cpp
  src/server/game/Handlers/LootHandler.cpp
  src/server/game/Handlers/MailHandler.cpp
  src/server/game/Handlers/SpellHandler.cpp
  src/server/game/Handlers/TradeHandler.cpp
  src/server/game/Loot/Loot.cpp
  src/server/game/Loot/LootMgr.cpp
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a

#24005 Core/Movement: Fix WaypointMovementGenerator ignoring EscortAI::SetEscortPaused() on Gossip Hello
  src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
Labels: Branch-3.3.5a

#24100 Core/PacketIO: convert some packets to to new packet class
  src/server/game/Cache/CharacterCache.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/Protocol/Opcodes.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a

#24102 Sync broadcast_text naming
  sql/updates/world/3.3.5/2020_02_01_02_world_335.sql
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Texts/ChatTextBuilder.cpp
Labels: Branch-3.3.5a

#24111 Scripts/Spells: Gift of the Harvester
  sql/updates/world/3.3.5/2020_02_01_03_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Labels: Branch-3.3.5a

#23868 Build: Enable and require c++17
  cmake/compiler/gcc/settings.cmake
  cmake/compiler/msvc/settings.cmake
  cmake/macros/ConfigureBaseTargets.cmake
  cmake/macros/FindPCHSupport.cmake
Labels: Branch-3.3.5a, Comp-Build, Feedback-PatchFix, Priority-FutureFeatureRequest

#23676 [3.3.5] More refactors from the pooling rewrite
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Events/GameEventMgr.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Grids/ObjectGridLoader.cpp
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
  src/server/game/Maps/MapManager.h
  src/server/game/Maps/SpawnData.h
  src/server/game/Pools/PoolMgr.cpp
  src/server/scripts/Commands/cs_go.cpp
  src/server/scripts/Commands/cs_list.cpp
  src/server/scripts/Commands/cs_npc.cpp
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spawns

#24128 Sync npc_text naming
  sql/updates/world/3.3.5/2020_02_08_00_world_335.sql
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-3.3.5a, Comp-Core, Comp-Database, Sub-Gossips/Texts

#24134 Use boost::optional and boost::none instead of smelly pointer
  src/server/game/AI/CoreAI/GameObjectAI.h
  src/server/game/AI/CreatureAI.h
  src/server/game/Cache/CharacterCache.cpp
  src/server/game/Cache/CharacterCache.h
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Scripting/ScriptReloadMgr.cpp
Labels: Branch-3.3.5a

#24127 Core/Scripting: fixed hourly bell sounds
  src/server/scripts/World/go_scripts.cpp
Labels: Branch-3.3.5a

#24135 Core/PacketIO: update cinematic packets to new system. Implement CMSG_OPENING_CINEMATIC and CMSG_COMPLETE_MOVIE
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/game/Scripting/ScriptMgr.h
  src/server/game/Server/Packets/AllPackets.h
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a

#24112 Core/Vehicles: implement vehicle seat addon table to specify seat ori…
  sql/updates/world/3.3.5/2020_02_08_01_world.sql
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Vehicle/Vehicle.cpp
  src/server/game/Entities/Vehicle/Vehicle.h
  src/server/game/Entities/Vehicle/VehicleDefines.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/World/World.cpp
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-3.3.5a

#24057 Scripts/Spells: Nourish
  sql/updates/world/3.3.5/2020_02_08_02_world.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-3.3.5a

#24141 Scripts/Kalimdor: Move script of Hand of Iruxos Crystal to database.
  sql/updates/world/3.3.5/2020_02_11_00_world.sql
  src/server/scripts/Kalimdor/zone_desolace.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix

#24151 Implement previously implicit ctor explicitly
  src/server/game/Entities/Object/Position.h
Labels: Branch-3.3.5a

#24140 clang-tidy readability-delete-null-pointer
  src/server/game/Guilds/Guild.cpp
  src/tools/map_extractor/loadlib.cpp
  src/tools/map_extractor/mpq_libmpq.cpp
  src/tools/vmap4_extractor/mpq_libmpq.cpp
Labels: Branch-3.3.5a

#24150 Scripts/Gameobject: Remove deprecated script for Cat Figurine
  sql/updates/world/3.3.5/2020_02_14_03_world.sql
  src/server/scripts/World/go_scripts.cpp
Labels: Branch-3.3.5a

#24157 Scripts/Gameobject: Journal of Jandice Barov- Convert script to SAI.
  sql/updates/world/3.3.5/9999_99_99_99_world.sql
  src/server/scripts/EasternKingdoms/Scholomance/boss_jandice_barov.cpp
  src/server/scripts/World/go_scripts.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix

#24159 Remove dependency on undefined behaviour
  src/common/Collision/BoundingIntervalHierarchy.h
Labels: Branch-3.3.5a

#24147 Scripts/World: Hourly Bell sound, further improvements
  src/server/scripts/World/go_scripts.cpp
Labels: Branch-3.3.5a

#24133 Core/Creature: Use proper name for wander distance.
  sql/updates/world/3.3.5/2020_02_16_01_world.sql
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/database/Database/Implementation/WorldDatabase.h
  src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Miscellaneous/Language.h
  src/server/game/Movement/MotionMaster.cpp
  src/server/game/Movement/MotionMaster.h
  src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
  src/server/scripts/Commands/cs_npc.cpp
Labels: Branch-3.3.5a, Comp-Core

#24121 [WIP] Core/AI: Pets musn't attack civilian NPC in aggressive mode
  src/server/game/AI/CoreAI/PetAI.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Grids/Notifiers/GridNotifiers.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-AI

#24116 Core/Players: re-organize SetSkill method to handle initialized skills correctly
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#24106 Scripts/Ebon Hold: Massacre At Light's Point
  sql/updates/world/3.3.5/2020_02_22_00_world.sql
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix

#24146 Core/SmartAI: implement SMART_ACTION_OVERRIDE_LIGHT and SMART_ACTION_OVERRIDE_WEATHER
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
  src/server/game/DataStores/DBCStores.h
Labels: Branch-3.3.5a

#24181 Core/Server: correct timestamp format for shutdown/restart notification broadcasts
  src/common/Utilities/Util.cpp
  src/common/Utilities/Util.h
  src/server/game/Tickets/TicketMgr.cpp
  src/server/game/Warden/Warden.cpp
  src/server/game/World/World.cpp
  src/server/scripts/Commands/cs_ban.cpp
  src/server/scripts/Commands/cs_gobject.cpp
  src/server/scripts/Commands/cs_list.cpp
  src/server/scripts/Commands/cs_misc.cpp
  src/server/scripts/Commands/cs_npc.cpp
Labels: Branch-3.3.5a

#23885 Core: Build on ARM64 - Raspberry Pi (preferable 4)
  dep/g3dlite/include/G3D/AtomicInt32.h
  dep/g3dlite/include/G3D/System.h
  dep/g3dlite/include/G3D/platform.h
  dep/g3dlite/source/System.cpp
  src/common/Utilities/SFMTRand.cpp
Labels: Branch-3.3.5a

#24049 Core/Movement: Implement MoveSplineFlag::Enter_Cycle flag
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Movement/MotionMaster.cpp
  src/server/game/Movement/Spline/MoveSpline.cpp
  src/server/game/Movement/Spline/MoveSplineInit.cpp
  src/server/game/Movement/Spline/MovementPacketBuilder.cpp
  src/server/game/Movement/Spline/MovementPacketBuilder.h
Labels: Branch-3.3.5a, Feedback-FixOutdatedMissingWIP

#24189 Scripts/Gameobject: Move Orb of Command script to SAI.
  sql/updates/world/3.3.5/2020_02_28_03_world.sql
  src/server/scripts/World/go_scripts.cpp
Labels: Branch-3.3.5a, Comp-Database, Feedback-PatchFix

#24190 Core/Units: UNIT_FLAG_PACIFIED will no longer block victim updates
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix

#24192 Core/DynamicInfo: rename some parameters according packet definitions
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
  src/server/game/Weather/Weather.cpp
  src/server/game/Weather/Weather.h
Labels: Branch-3.3.5a

#24193 Core/Server: improve timestamp format output for large time values
  src/common/Utilities/Util.cpp
Labels: Branch-3.3.5a

#24206 Core/PathFinding: Return raycast hitpoint when specifying straightLine
  src/server/game/Movement/PathGenerator.cpp
Labels: Branch-3.3.5a

#24207 Core/PathFinding: Add support to WorldObject pathfinding
  src/server/game/Movement/PathGenerator.cpp
  src/server/game/Movement/PathGenerator.h
Labels: Branch-3.3.5a

#24209 Core/Misc: Moved CanSpeak() method to WorldSession class
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Handlers/ChatHandler.cpp
  src/server/game/Server/WorldSession.cpp
  src/server/game/Server/WorldSession.h
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a

#24126 Scripts/Ebon Hold: Bloody Breakout
  sql/updates/world/3.3.5/2020_02_28_04_world.sql
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter2.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix, Sub-Quests

#24164 Modernize codebase with Clang-Tidy range based loops, part 1
  src/common/Collision/Management/MMapManager.cpp
  src/common/Collision/Management/VMapManager2.cpp
  src/common/Collision/Maps/MapTree.cpp
  src/common/Collision/Maps/TileAssembler.cpp
  src/common/Logging/Log.cpp
  src/common/Logging/Logger.cpp
  src/common/Utilities/EventMap.cpp
  src/common/Utilities/Util.cpp
  src/server/database/Database/QueryHolder.cpp
  src/server/game/AI/CoreAI/CombatAI.cpp
Labels: Branch-3.3.5a

#24165 Modernize codebase with Clang-Tidy range based loops, part 2
  src/server/game/AI/CoreAI/PetAI.cpp
  src/server/game/AI/CoreAI/UnitAI.cpp
  src/server/game/AI/PlayerAI/PlayerAI.cpp
  src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/Accounts/AccountMgr.cpp
  src/server/game/Accounts/RBAC.cpp
  src/server/game/Achievements/AchievementMgr.cpp
Labels: Branch-3.3.5a

#24158 Replace MySQL prepared statement union with std::variant
  src/server/database/Database/MySQLPreparedStatement.cpp
  src/server/database/Database/MySQLPreparedStatement.h
  src/server/database/Database/PreparedStatement.cpp
  src/server/database/Database/PreparedStatement.h
Labels: Branch-3.3.5a, Feedback-FixOutdatedMissingWIP
