Repository TrinityCore/TrinityCore, pull requests merged in 2020-12, with the labels that each got.

#25625 Improve multithreading of mmaps_generator
  cmake/compiler/clang/settings.cmake
  cmake/showoptions.cmake
  src/tools/mmaps_generator/MapBuilder.cpp
  src/tools/mmaps_generator/MapBuilder.h
  src/tools/mmaps_generator/PathGenerator.cpp
Labels: Branch-3.3.5a, Comp-Tools

#25521 Core/Spells: Fixed fallback values for EquippedItemSubClassMask and EquippedItemInventoryTypeMask
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-master

#25680 Scripts/Spells: Mage Ice Lance, Splitting Ice, Thermal Void
  sql/updates/world/master/2020_12_24_01_world.sql
  sql/updates/world/master/9999_99_99_30455_world.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-master

#25765 Core/Spells: Implemented personal summons (#19231)
  src/server/game/Combat/ThreatManager.cpp
  src/server/game/Entities/Creature/TemporarySummon.cpp
  src/server/game/Entities/Creature/TemporarySummon.h
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Maps/Map.h
  src/server/game/Spells/SpellEffects.cpp
  src/server/shared/DataStores/DBCEnums.h
Labels: Branch-3.3.5a

#25690 Core/Visibility: Split BG/Arena visibility settings
  src/server/game/Maps/Map.cpp
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a

#25623 Core/SAI: implement new smart actions to change AI Animkits and to enable/disable hover movement
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#25599 Core/Units: do not send power update packets when gaining power via energize spell effects
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
Labels: Branch-3.3.5a

#25773 Core/Auras: vehicles should not despawn during seat change
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-3.3.5a

#25771 Core/Maps: Attempt to fix picking the wrong min height
  src/server/game/Maps/Map.cpp
Labels: Branch-3.3.5a

#25785 Core/Maps: move pooling hand-off outside of Map::CheckRespawn
  src/server/game/Maps/Map.cpp
  src/server/game/Pools/PoolMgr.cpp
  src/server/game/Pools/PoolMgr.h
Labels: Branch-3.3.5a, Feedback-PatchFix, Priority-High, Sub-Pools, Sub-Spawns

#25778 Core/SAI: Fix SMART_EVENT_FLAG_NOT_REPEATABLE flag being ignored when specifying a chance (and other SMART_ACTION_CAST fixes)
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#24927 Adjust comment about can fly movement flag
  src/server/game/Entities/Unit/UnitDefines.h
Labels: Branch-master
