Repository TrinityCore/TrinityCore, pull requests merged in 2020-09, with the labels that each got.

#25375 [For CI] Random property/suffix unit tests, also more DBC std::array-fication
  src/server/game/AuctionHouse/AuctionHouseMgr.cpp
  src/server/game/Chat/HyperlinkTags.cpp
  src/server/game/Chat/Hyperlinks.cpp
  src/server/game/Chat/Hyperlinks.h
  src/server/shared/DataStores/DBCStructure.h
  tests/DummyData.cpp
  tests/game/Hyperlinks.cpp
Labels: Branch-3.3.5a, Sub-UnitTests

#25376 [for CI] |Hspell and |Htalent unit testing
  src/server/game/Chat/HyperlinkTags.cpp
  src/server/game/Chat/Hyperlinks.cpp
  src/server/game/Chat/Hyperlinks.h
  src/server/game/Spells/SpellMgr.h
  src/server/shared/DataStores/DBCStructure.h
  tests/DummyData.cpp
  tests/DummyData.h
  tests/game/Hyperlinks.cpp
Labels: Branch-3.3.5a, Sub-UnitTests

#25326 Core/Totem: Immune to all positive spells.
  src/server/game/Entities/Totem/Totem.cpp
  src/server/game/Entities/Totem/Totem.h
Labels: Branch-3.3.5a

#25380 [for CIs] custom link color support + quest-level-in-title link support
  src/common/Utilities/Util.cpp
  src/server/game/Chat/Hyperlinks.cpp
  src/server/game/Entities/Creature/GossipDef.cpp
  src/server/game/Quests/QuestDef.cpp
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a, Comp-Core, Sub-Chat, Sub-Quests

#25364 Trinity::StringTo<double> support
  src/common/Utilities/StringConvert.h
  src/server/game/Chat/ChatCommands/ChatCommandArgs.h
  tests/common/StringConvert.cpp
  tests/game/ChatCommand.cpp
Labels: Branch-3.3.5a, Comp-Core

#25386 [for CI] .gobj command port
  src/server/game/Chat/ChatCommands/ChatCommand.h
  src/server/game/Chat/ChatCommands/ChatCommandArgs.h
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
  src/server/scripts/Commands/cs_gobject.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Commands

#25388 [CI] .npc command conversion
  contrib/enumutils_describe.py
  src/server/game/AI/CreatureAI.h
  src/server/game/AI/enuminfo_CreatureAI.cpp
  src/server/game/Chat/ChatCommands/ChatCommand.h
  src/server/game/Chat/ChatCommands/ChatCommandArgs.cpp
  src/server/game/Chat/ChatCommands/ChatCommandArgs.h
  src/server/game/Chat/ChatCommands/ChatCommandHelpers.h
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
  src/server/game/Chat/Hyperlinks.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Globals/ObjectAccessor.cpp
  src/server/game/Globals/ObjectAccessor.h
  src/server/game/Movement/MovementDefines.h
  src/server/game/Movement/enuminfo_MovementDefines.cpp
  src/server/game/Texts/ChatTextBuilder.h
  src/server/scripts/Commands/cs_gobject.cpp
  src/server/scripts/Commands/cs_npc.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Commands

#25389 Scripts/ICC: update Blood Council scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
Labels: Branch-3.3.5a

#25390 Scripts/ICC: update Valithria Dreamwalker scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
Labels: Branch-3.3.5a

#25391 Scripts/ICC: update Festergut scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_festergut.cpp
Labels: Branch-3.3.5a

#25392 Scripts/ICC: update Rotface scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp
Labels: Branch-3.3.5a

#25393 Scripts/ICC: update Lady Deathwhisper scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
Labels: Branch-3.3.5a

#25394 Scripts/ICC: update Professor Putricide scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
Labels: Branch-3.3.5a

#25395 Scripts/ICC: update Sindragosa scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp
Labels: Branch-3.3.5a

#25398 Core/SAI: Reduce the chance of infinite loops/stack overflows
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
Labels: Branch-3.3.5a

#25401 Execute OnStartup before log
  src/server/worldserver/Main.cpp
Labels: Branch-master

#25404 Core/Unit: Fix units on vehicles not dismounting on death
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#25156 Authserver cleanup phase 5 - removal of sha_pass_hash
  sql/base/auth_database.sql
  sql/updates/auth/3.3.5/2020_09_06_00_auth.sql
  src/common/Cryptography/Authentication/SRP6.cpp
  src/common/Cryptography/Authentication/SRP6.h
  src/server/authserver/Main.cpp
  src/server/authserver/Server/AuthSession.cpp
  src/server/authserver/Server/AuthSession.h
  src/server/database/Database/Implementation/LoginDatabase.cpp
  src/server/database/Database/Implementation/LoginDatabase.h
  src/server/game/Accounts/AccountMgr.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#25406 Core/Maps: Always update the grid of player summons even if far away
  src/server/game/Maps/Map.cpp
Labels: Branch-3.3.5a

#25407 [3.3.5] .arena command conversion
  src/server/game/Battlegrounds/ArenaTeam.cpp
  src/server/game/Battlegrounds/ArenaTeam.h
  src/server/game/Battlegrounds/ArenaTeamMgr.cpp
  src/server/game/Battlegrounds/ArenaTeamMgr.h
  src/server/game/Battlegrounds/enuminfo_ArenaTeam.cpp
  src/server/game/Chat/Chat.cpp
  src/server/game/Chat/Chat.h
  src/server/game/Chat/ChatCommands/ChatCommandTags.cpp
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
  src/server/game/Miscellaneous/Language.h
  src/server/scripts/Commands/cs_arena.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Core, Sub-Commands

#25413 Core/ChatCommands: Move ostream operator into Variant class so we don't pollute std::
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
Labels: Branch-3.3.5a

#25418 [for CI] .character command conversion
  src/server/database/Database/PreparedStatement.cpp
  src/server/database/Database/PreparedStatement.h
  src/server/game/Accounts/AccountMgr.cpp
  src/server/game/Accounts/AccountMgr.h
  src/server/game/Chat/ChatCommands/ChatCommandTags.cpp
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
  src/server/scripts/Commands/cs_character.cpp
  src/server/shared/DataStores/DBCEnums.h
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Commands

#24875 Core/Movement: Corrected Animation Tier handling
  sql/updates/world/3.3.5/2020_08_xx_xx_world.sql
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Entities/Unit/UnitDefines.h
  src/server/game/Movement/MotionMaster.cpp
  src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
  src/server/game/Movement/Spline/MoveSpline.h
  src/server/game/Movement/Spline/MoveSplineFlag.h
  src/server/game/Movement/Spline/MoveSplineInit.h
  src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp
  src/server/scripts/Kalimdor/OnyxiasLair/boss_onyxia.cpp
  src/server/scripts/Northrend/AzjolNerub/Ahnkahet/boss_jedoga_shadowseeker.cpp
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_saviana_ragefire.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
  src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp
  src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/utgarde_keep.cpp
  src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp
  src/server/scripts/Outland/zone_shadowmoon_valley.cpp
Labels: Branch-3.3.5a

#25410 Scripts/Icecrown: Small event of the down Nerub'ar Broodkeep
  sql/updates/world/3.3.5/2020_09_08_00_world.sql
  sql/updates/world/3.3.5/2020_09_08_01_world.sql
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.h
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#25419 Scripts/VoA: Moved scripts to SAI.
  sql/updates/world/3.3.5/2020_09_08_02_world.sql
  src/server/scripts/Northrend/VaultOfArchavon/boss_archavon.cpp
  src/server/scripts/Northrend/VaultOfArchavon/boss_koralon.cpp
  src/server/scripts/Northrend/VaultOfArchavon/boss_toravon.cpp
Labels: Branch-3.3.5a

#25416 Little CombatAI refactor
  src/server/game/AI/CoreAI/CombatAI.cpp
  src/server/game/AI/CoreAI/CombatAI.h
Labels: Branch-3.3.5a

#25424 Core/Addon: Correct Banned Addon length in SMSG_ADDON_INFO packet
  src/server/game/Server/WorldSession.cpp
Labels: Branch-3.3.5a

#25427 [for CI] remove ChatHandler::extractOptFirstArg
  src/server/game/Chat/Chat.cpp
  src/server/game/Chat/Chat.h
  src/server/game/Chat/ChatCommands/ChatCommandArgs.cpp
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
  src/server/game/Guilds/Guild.cpp
  src/server/game/Guilds/Guild.h
  src/server/scripts/Commands/cs_guild.cpp
  src/server/scripts/Commands/cs_misc.cpp
  src/server/scripts/Commands/cs_tele.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Core, Sub-Commands

#25422 [3.3.5] Guild cleanup
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Guilds/Guild.cpp
  src/server/game/Guilds/Guild.h
  src/server/game/Guilds/GuildMgr.cpp
  src/server/game/Guilds/GuildMgr.h
  src/server/game/Handlers/GuildHandler.cpp
  src/server/game/Server/Packets/GuildPackets.cpp
  src/server/game/Server/Packets/GuildPackets.h
  src/server/game/Server/Packets/PacketUtilities.h
Labels: Branch-3.3.5a, Comp-Core

#25428 [for CI] DatabaseTransaction by value
  src/server/game/Achievements/AchievementMgr.cpp
  src/server/game/Achievements/AchievementMgr.h
  src/server/game/AuctionHouse/AuctionHouseMgr.cpp
  src/server/game/AuctionHouse/AuctionHouseMgr.h
  src/server/game/Calendar/CalendarMgr.cpp
  src/server/game/Calendar/CalendarMgr.h
  src/server/game/Entities/Corpse/Corpse.cpp
  src/server/game/Entities/Corpse/Corpse.h
  src/server/game/Entities/Item/Container/Bag.cpp
  src/server/game/Entities/Item/Container/Bag.h
  src/server/game/Entities/Item/Item.cpp
  src/server/game/Entities/Item/Item.h
  src/server/game/Entities/Pet/Pet.cpp
  src/server/game/Entities/Pet/Pet.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Guilds/Guild.cpp
  src/server/game/Guilds/Guild.h
  src/server/game/Loot/LootItemStorage.cpp
  src/server/game/Loot/LootItemStorage.h
  src/server/game/Mails/Mail.cpp
  src/server/game/Mails/Mail.h
  src/server/game/Reputation/ReputationMgr.cpp
  src/server/game/Reputation/ReputationMgr.h
  src/server/game/Server/WorldSession.cpp
  src/server/game/Server/WorldSession.h
  src/server/game/Spells/SpellHistory.cpp
  src/server/game/Spells/SpellHistory.h
  src/server/game/Tickets/TicketMgr.cpp
  src/server/game/Tickets/TicketMgr.h
Labels: Branch-3.3.5a, Comp-Core, Sub-Database

#25429 Scripts/Commands: Convert remaining debug commands
  sql/updates/world/3.3.5/2020_09_10_00_world.sql
  src/server/game/Chat/Channels/Channel.h
  src/server/game/Chat/Channels/enuminfo_Channel.cpp
  src/server/game/Entities/Item/ItemDefines.h
  src/server/game/Entities/Item/enuminfo_ItemDefines.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Handlers/QuestHandler.cpp
  src/server/game/Quests/QuestDef.h
  src/server/game/Quests/enuminfo_QuestDef.cpp
  src/server/scripts/Commands/cs_debug.cpp
  src/server/shared/SharedDefines.h
  src/server/shared/enuminfo_SharedDefines.cpp
Labels: Branch-3.3.5a

#25430 Scripts/Commands: Convert argument parsing of lfg commands to new system
  src/server/scripts/Commands/cs_lfg.cpp
Labels: Branch-3.3.5a

#25431 Core/ChatCommands: Drop PlayerIdentifier's cast operators which could return nullptr
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
  src/server/scripts/Commands/cs_character.cpp
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a

#25437 [for CI] make ExactSequence more readable
  src/common/Utilities/Util.cpp
  src/common/Utilities/Util.h
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
  src/server/scripts/Commands/cs_ahbot.cpp
  src/server/scripts/Commands/cs_debug.cpp
  src/server/scripts/Commands/cs_gobject.cpp
  src/server/scripts/Commands/cs_message.cpp
  src/server/scripts/Commands/cs_misc.cpp
  src/server/scripts/Commands/cs_npc.cpp
  src/server/scripts/Commands/cs_tele.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Core, Sub-Commands

#25447 Dep/Fmt: update fmt library to 7.0.3
  dep/PackageList.txt
  dep/fmt/CMakeLists.txt
  dep/fmt/CONTRIBUTING.md
  dep/fmt/CONTRIBUTING.rst
  dep/fmt/ChangeLog.rst
  dep/fmt/LICENSE.rst
  dep/fmt/README.rst
  dep/fmt/fmt/container.h
  dep/fmt/fmt/format.cc
  dep/fmt/fmt/format.h
  dep/fmt/fmt/ostream.cc
  dep/fmt/fmt/ostream.h
  dep/fmt/fmt/posix.cc
  dep/fmt/fmt/posix.h
  dep/fmt/fmt/printf.cc
  dep/fmt/fmt/printf.h
  dep/fmt/fmt/string.h
  dep/fmt/fmt/time.h
  dep/fmt/include/fmt/chrono.h
  dep/fmt/include/fmt/color.h
  dep/fmt/include/fmt/compile.h
  dep/fmt/include/fmt/core.h
  dep/fmt/include/fmt/format-inl.h
  dep/fmt/include/fmt/format.h
  dep/fmt/include/fmt/locale.h
  dep/fmt/include/fmt/os.h
  dep/fmt/include/fmt/ostream.h
  dep/fmt/include/fmt/posix.h
  dep/fmt/include/fmt/printf.h
  dep/fmt/include/fmt/ranges.h
  dep/fmt/src/format.cc
  dep/fmt/src/os.cc
  src/common/Utilities/StringFormat.h
Labels: Branch-3.3.5a

#24492 Game/AI: Implement option to move a creature back to Homeposition on Evade.
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a, Feedback-FixOutdatedMissingWIP

#25434 Scripts/ICC: update Blood Queen Lana'thel scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
Labels: Branch-3.3.5a

#25436 Scripts/ICC: update Lord Marrowgar scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp
Labels: Branch-3.3.5a

#25449 Core/Maps: Fixed map min height calculation
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
Labels: Branch-3.3.5a

#25443 [3.3.5] Error messages from Chat command argument parsing
  sql/updates/world/3.3.5/2020_09_12_04_world.sql
  src/common/Define.h
  src/common/Utilities/Util.cpp
  src/common/Utilities/Util.h
  src/server/game/Chat/Chat.cpp
  src/server/game/Chat/Chat.h
  src/server/game/Chat/ChatCommands/ChatCommand.h
  src/server/game/Chat/ChatCommands/ChatCommandArgs.cpp
  src/server/game/Chat/ChatCommands/ChatCommandArgs.h
  src/server/game/Chat/ChatCommands/ChatCommandHelpers.cpp
  src/server/game/Chat/ChatCommands/ChatCommandHelpers.h
  src/server/game/Chat/ChatCommands/ChatCommandTags.cpp
  src/server/game/Chat/ChatCommands/ChatCommandTags.h
  src/server/game/Miscellaneous/Language.h
  src/server/game/World/World.h
  src/server/scripts/Commands/cs_gobject.cpp
  src/server/scripts/Commands/cs_npc.cpp
  src/server/worldserver/CommandLine/CliRunnable.cpp
  src/server/worldserver/RemoteAccess/RASession.cpp
  src/server/worldserver/RemoteAccess/RASession.h
  src/server/worldserver/TCSoap/TCSoap.h
  tests/game/ChatCommand.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Commands

#25423 Core/Spells: Do not reset periodic timer for stacking DoTs
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells

#25435 Scripts/ICC: update Deathbringer Saurfang scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp
Labels: Branch-3.3.5a

#25440 Core/Spells: Cleaned up and improved spell focusing behavior
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#25462 Fix small file matching error in enumutils_describe.py
  contrib/enumutils_describe.py
Labels: Branch-3.3.5a

#25455 Script/Commands: Add ".pdump copy" command
  sql/base/auth_database.sql
  sql/updates/auth/3.3.5/2020_09_17_00_auth.sql
  sql/updates/world/3.3.5/2020_09_17_00_world.sql
  src/server/game/Accounts/RBAC.h
  src/server/game/Tools/PlayerDump.cpp
  src/server/game/Tools/PlayerDump.h
  src/server/scripts/Commands/cs_character.cpp
Labels: Branch-3.3.5a

#25438 Scripts/ICC: update Gunship Battle scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
Labels: Branch-3.3.5a

#25439 Scripts/ICC: update Icecrown Citadel scripts to new model
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
Labels: Branch-3.3.5a

#25468 Core/PacketIO: Updated SMSG_CHAT_SERVER_MESSAGE
  src/server/game/Server/Packets/ChatPackets.cpp
  src/server/game/Server/Packets/ChatPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/Protocol/Opcodes.h
  src/server/game/World/World.cpp
  src/server/game/World/World.h
Labels: Branch-3.3.5a

#25471 Core/SAI: Fix SMART_ACTION_WP_PAUSE with 0 delay pausing the path only for 1 world loop update
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Branch-3.3.5a

#25472 Core/SAI: Add orientation and delay columns to waypoints table
  sql/updates/world/3.3.5/2020_09_19_00_world.sql
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
Labels: Branch-3.3.5a

#25463 [3.3.5] ChatCommands, the other half: chat command resolution refactor
  sql/updates/world/3.3.5/2020_09_20_00_world.sql
  src/server/game/Accounts/RBAC.h
  src/server/game/Chat/Chat.cpp
  src/server/game/Chat/Chat.h
  src/server/game/Chat/ChatCommands/ChatCommand.cpp
  src/server/game/Chat/ChatCommands/ChatCommand.h
  src/server/game/Chat/ChatCommands/ChatCommandArgs.h
  src/server/game/Miscellaneous/Language.h
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/game/Scripting/ScriptMgr.h
  src/server/game/World/World.cpp
  src/server/scripts/Commands/cs_account.cpp
  src/server/scripts/Commands/cs_achievement.cpp
  src/server/scripts/Commands/cs_ahbot.cpp
  src/server/scripts/Commands/cs_arena.cpp
  src/server/scripts/Commands/cs_ban.cpp
  src/server/scripts/Commands/cs_bf.cpp
  src/server/scripts/Commands/cs_cast.cpp
  src/server/scripts/Commands/cs_character.cpp
  src/server/scripts/Commands/cs_cheat.cpp
  src/server/scripts/Commands/cs_debug.cpp
  src/server/scripts/Commands/cs_deserter.cpp
  src/server/scripts/Commands/cs_disable.cpp
  src/server/scripts/Commands/cs_event.cpp
  src/server/scripts/Commands/cs_gm.cpp
  src/server/scripts/Commands/cs_go.cpp
  src/server/scripts/Commands/cs_gobject.cpp
  src/server/scripts/Commands/cs_group.cpp
  src/server/scripts/Commands/cs_guild.cpp
  src/server/scripts/Commands/cs_honor.cpp
  src/server/scripts/Commands/cs_instance.cpp
  src/server/scripts/Commands/cs_learn.cpp
  src/server/scripts/Commands/cs_lfg.cpp
  src/server/scripts/Commands/cs_list.cpp
  src/server/scripts/Commands/cs_lookup.cpp
  src/server/scripts/Commands/cs_message.cpp
  src/server/scripts/Commands/cs_misc.cpp
  src/server/scripts/Commands/cs_mmaps.cpp
  src/server/scripts/Commands/cs_modify.cpp
  src/server/scripts/Commands/cs_npc.cpp
  src/server/scripts/Commands/cs_pet.cpp
  src/server/scripts/Commands/cs_quest.cpp
  src/server/scripts/Commands/cs_rbac.cpp
  src/server/scripts/Commands/cs_reload.cpp
  src/server/scripts/Commands/cs_reset.cpp
  src/server/scripts/Commands/cs_send.cpp
  src/server/scripts/Commands/cs_server.cpp
  src/server/scripts/Commands/cs_tele.cpp
  src/server/scripts/Commands/cs_ticket.cpp
  src/server/scripts/Commands/cs_titles.cpp
  src/server/scripts/Commands/cs_wp.cpp
  src/server/worldserver/CommandLine/CliRunnable.cpp
  tests/game/ChatCommand.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Commands

#25479 [for CI] enable trinity_string support for help text
  sql/updates/world/3.3.5/2020_09_21_00_world.sql
  src/server/game/Chat/ChatCommands/ChatCommand.cpp
  src/server/game/Chat/ChatCommands/ChatCommand.h
  src/server/game/Miscellaneous/Language.h
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/scripts/Commands/cs_achievement.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-Commands

#25477 Core/Quest: Fix wrong feedback sent to the quest sharing sender with auto-accept quests
  src/server/game/Handlers/QuestHandler.cpp
Labels: Branch-3.3.5a

#25490 Core/Spells: SPELL_AURA_MOD_HEALING_PCT should be negative if TargetType is enemy or BasePoints are negative
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a
