Repository TrinityCore/TrinityCore, pull requests merged in 2020-04, with the labels that each got.

#24384 Core/Spell: Remove duplicate handlers
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-3.3.5a

#24378 Scripts/Spells: prevent Drain Soul from cancelling prematurely
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#24383 Update AuctionBucketKey field declaration
  src/server/game/Server/Packets/AuctionHousePackets.h
Labels: Branch-master

#24388 CI/Circle CI: Prevent conflict with diff branches
  .circleci/config.yml
Labels: Branch-3.3.5a

#24386 CI/Circle CI: Prepare master for circle ci
  .circleci/config.yml
  .travis.yml
  contrib/check_updates.sh
Labels: Branch-master

#24385 Core/Locales: Optimize locale loading - move the strings
  src/server/game/Achievements/AchievementMgr.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Texts/CreatureTextMgr.cpp
Labels: Branch-3.3.5a

#24379 Core/Movement: Formation Rewrite
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Creature/CreatureGroups.cpp
  src/server/game/Entities/Creature/CreatureGroups.h
  src/server/game/Movement/MotionMaster.cpp
  src/server/game/Movement/MotionMaster.h
  src/server/game/Movement/MovementGenerators/FormationMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/FormationMovementGenerator.h
  src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
  src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
  src/server/game/Movement/Spline/MoveSpline.cpp
  src/server/game/Movement/Spline/MoveSpline.h
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Movement, Sub-Waypoints

#24375 Core/DB: Add DB error for missing gossip npcflag
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-3.3.5a

#24349 Scripts/Pet: Baby Blizzard Bear & Egbert
  sql/updates/world/3.3.5/2020_04_04_00_world.sql
  src/server/scripts/Pet/pet_generic.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Sub-PetMinion

#24338 Core/Spell: Lich King Necrotic Plague stacking
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#24300 Scripts/BlackfathomDeeps: Kelris will now channel his spell
  src/server/scripts/Kalimdor/BlackfathomDeeps/boss_kelris.cpp
Labels: Branch-3.3.5a

#24364 Core/PacketIO: Handle CMSG_REQUEST_PET_INFO for more cases
  src/server/game/Handlers/PetHandler.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-PetMinion

#24348 Added the ability to use TLS when connecting to a database.
  src/server/authserver/authserver.conf.dist
  src/server/database/Database/MySQLConnection.cpp
  src/server/database/Database/MySQLConnection.h
  src/server/database/Updater/DBUpdater.cpp
  src/server/database/Updater/DBUpdater.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a, Feedback-PatchFix

#24253 Missing rbac permissions
  sql/base/auth_database.sql
  sql/updates/auth/3.3.5/2020_04_07_00_auth.sql
Labels: Branch-3.3.5a

#24399 Core/Objects: reduce unnecessary vmap lookups by using cached liquid status data pulled from position updates
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
Labels: Branch-3.3.5a

#24416 Core/SAI: Allow SMART_TARGET_ACTION_INVOKER to target GameObjects
  src/common/Utilities/Util.h
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
Labels: Branch-3.3.5a, Sub-ScriptingEngine

#24422 Core/Pooling: Remove respawn times from the database when despawning a pool
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
  src/server/game/Pools/PoolMgr.cpp
  src/server/game/Pools/PoolMgr.h
Labels: Branch-3.3.5a, Comp-Core, Sub-Pools

#24420 Core/PacketIO: Updated CMSG_REQUEST_PET_INFO
  src/server/game/Handlers/PetHandler.cpp
  src/server/game/Server/Packets/PetPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a

#24431 Scripts/Pets: Mojo
  sql/updates/world/3.3.5/2020_04_11_01_world.sql
  src/server/scripts/Pet/pet_generic.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Database, Feedback-PatchFix, Sub-PetMinion

#24393 Core/Opcodes: updated CMSG_SET_SHEATHED to new packet class
  src/server/game/Handlers/CombatHandler.cpp
  src/server/game/Server/Packets/CombatPackets.cpp
  src/server/game/Server/Packets/CombatPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/Protocol/Opcodes.h
  src/server/game/Server/WorldSession.cpp
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a

#24405 Improvements to Pyroguard Emberseer (UBRS) script
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/blackrock_spire.h
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_pyroguard_emberseer.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix

#24417 Core/Gameobjects: Improve stealth detection
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Grids/Notifiers/GridNotifiers.h
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#24442 Core/PacketIO: updated SMSG_DURABILITY_DAMAGE_DEATH
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a

#24440 Core/Packets: updated SMSG_LEVELUP_INFO
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
Labels: Branch-3.3.5a

#24441 Core/Packets: updated mirror timer packets
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
Labels: Branch-3.3.5a

#24459 Scripts/Quest: The Exorcism of Colonel Jules
  src/server/scripts/Outland/zone_hellfire_peninsula.cpp
Labels: Branch-3.3.5a

#24435 Core/Players: Improve trade exchange calculations
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#24470 Scripts/Naxxramas: Fix Heigan Eruption spell
  src/server/scripts/Northrend/Naxxramas/boss_heigan.cpp
Labels: Branch-3.3.5a

#24453 Add realm ID for actions based ip logging
  sql/base/auth_database.sql
  sql/updates/auth/3.3.5/2020_04_18_00_auth.sql
  src/server/database/Database/Implementation/LoginDatabase.cpp
  src/server/scripts/World/action_ip_logger.cpp
Labels: Branch-3.3.5a

#24457 Core/Packets: updated MSG_RANDOM_ROLL
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Groups/Group.cpp
  src/server/game/Groups/Group.h
  src/server/game/Handlers/GroupHandler.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a

#24460 Core/Unit: Improve HitInfo absorb and resist flags logic in Unit::CalculateMeleeDamage
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#24465 Core/Spells: Fixed Ice Block / Divine Shield cast in Cyclone
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells

#24467 Core/Spells: Improve check for non damage/heal spells in Spell::TargetInfo::DoDamageAndTriggers
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#24197 Boss/Script: Vazruden_Fix
  src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp
Labels: Branch-3.3.5a, Feedback-FixOutdatedMissingWIP

#24475 Core/PacketIO: updated SMSG_CROSSED_INEBRIATION_THRESHOLD
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
Labels: Branch-3.3.5a

#24489 Game/SmartScripts: Reset counter in SAI only on Initialize.
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Branch-3.3.5a

#24487 Core/Database: fix wrong password logging
  src/server/database/Database/Implementation/LoginDatabase.cpp
Labels: Branch-3.3.5a

#24404 Core/Spells: implement SMSG_MOUNT_RESULT and use it for transformed mounting cases
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Server/Packets/SpellPackets.cpp
  src/server/game/Server/Packets/SpellPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
Labels: Branch-master

#24499 Scripts/Antorus: implement Garothi Worldbreaker encounter (redux)
  sql/updates/world/master/2020_04_25_00_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Argus/AntorusTheBurningThrone/antorus_the_burning_throne.h
  src/server/scripts/Argus/AntorusTheBurningThrone/boss_garothi_worldbreaker.cpp
  src/server/scripts/Argus/AntorusTheBurningThrone/instance_antorus_the_burning_throne.cpp
  src/server/scripts/Argus/argus_script_loader.cpp
Labels: Branch-master, Comp-C++Script

#24472 Scripts/OnyxiasLair: Fix Onyxia Eruption spell
  src/server/scripts/Kalimdor/OnyxiasLair/instance_onyxias_lair.cpp
Labels: Branch-3.3.5a

#24480 Core/GameObject: Remove linked traps when the main GameObject is remo…
  src/server/game/Entities/GameObject/GameObject.cpp
Labels: Branch-3.3.5a, Comp-Core, Sub-GameObject, Sub-Spawns

#24493 Game/AI: Enable check for SMART_TARGET_GAMEOBJECT_RANGE
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Branch-3.3.5a

#24494 Game/AI: Implement new targettype SMART_TARGET_CLOSEST_UNSPAWNED_GAMEOBJECT
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Grids/Notifiers/GridNotifiers.h
Labels: Branch-3.3.5a

#24502 Core/Spells: Crystallize should not use DIMINISHING
  src/server/game/Spells/SpellInfo.cpp
  src/server/scripts/Northrend/Nexus/Nexus/boss_keristrasza.cpp
Labels: Branch-3.3.5a

#24476 Core/PacketIO: updated CMSG_TOGGLE_PVP opcode
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/WorldSession.h
Labels: Branch-3.3.5a

#24496 Scripts/Spells: Fixed Mages 2P T10 proc delay
  sql/updates/world/3.3.5/2020_04_26_04_world.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#22614 Core/Packets Fix SMSG_START_TIMER struct & update to new packet system
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
Labels: Branch-master, Comp-Core, Feedback-PatchFix

#24463 Core/Spells: Scrolls should not be consumed, when they fail to apply
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#24514 Scripts/IcecrownCitadel: Adding IsAlive check to avoid crash in Event
  src/server/scripts/Northrend/IcecrownCitadel/boss_sister_svalna.cpp
Labels: Branch-3.3.5a

#24506 Core\GameObject: corrected check for IsWithinDistInMap
  src/server/game/Entities/GameObject/GameObject.cpp
Labels: Branch-3.3.5a

#24507 Core/Spells: implement SMSG_MOUNT_RESULT and use it
  src/server/game/Server/Packets/SpellPackets.cpp
  src/server/game/Server/Packets/SpellPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/Protocol/Opcodes.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/shared/SharedDefines.h
Labels: Branch-3.3.5a

#24511 Core/Player: add helper methods for PLAYER_FLAGS_DEVELOPER
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a
