Repository TrinityCore/TrinityCore, pull requests merged in 2021-05, with the labels that each got.

#26508 Core/SAI: Prevent loading invalid smart_scripts entry
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
Labels: Branch-3.3.5a

#26494 Core/Game: Fix dynamic library cache path with git flow branches
  src/server/game/Scripting/ScriptReloadMgr.cpp
Labels: Branch-3.3.5a

#26482 Core/Vehicle: Setting home position of creature passenger on AtEngage
  src/server/game/Entities/Creature/Creature.cpp
Labels: Branch-3.3.5a

#26486 Core/Map: Added Map::SetZoneOverrideLight std::chrono overload
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
  src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
Labels: Branch-3.3.5a

#26348 Core/Movement: Improve client control logic
  src/server/game/AI/CreatureAISelector.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Handlers/MovementHandler.cpp
  src/server/game/Handlers/SpellHandler.cpp
  src/server/game/Handlers/TaxiHandler.cpp
  src/server/game/Server/GameClient.cpp
  src/server/game/Server/GameClient.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/WorldSession.cpp
  src/server/game/Server/WorldSession.h
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix

#26538 Core/Movement: Hotfix the crashes that can occur in the movement handlers
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Server/GameClient.cpp
  src/server/game/Server/WorldSession.cpp
Labels: Branch-3.3.5a

#26541 Fixed player_choice_response the reading structure is now correct work
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#26554 Scripts/Quest: Rework cocooned creatures
  sql/updates/world/3.3.5/2021_05_27_00_world.sql
  src/server/scripts/Kalimdor/zone_bloodmyst_isle.cpp
  src/server/scripts/Northrend/zone_howling_fjord.cpp
  src/server/scripts/Northrend/zone_zuldrak.cpp
  src/server/scripts/Outland/zone_terokkar_forest.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Quests, Sub-Spells

#26564 Added "thread" library in file RASession.cpp to fix the build issue in GCC glibc
  src/server/worldserver/RemoteAccess/RASession.cpp
Labels: Branch-3.3.5a

#26565 Fixed libstdc++ version 11 future lib removal of thread
  src/server/worldserver/RemoteAccess/RASession.cpp
Labels: Branch-master
