Repository TrinityCore/TrinityCore, pull requests merged in 2021-08, with the labels that each got.

#26771 fix missing header when building with dynamic script reloader
  src/server/game/Scripting/ScriptReloadMgr.cpp
Labels: Branch-3.3.5a

#26775 Core/Spell: Fix Mage Frostfire bolt, now it will not put target into combat at expire
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-3.3.5a

#26773 Core/Combat: Allow refresh pvp combat when assisting a unit that is in pvp combat
  src/server/game/Combat/CombatManager.cpp
Labels: Branch-3.3.5a

#26765 Core/Authserver: Remove redundant conversion during Reconnect Proof cmd
  src/server/authserver/Server/AuthSession.cpp
Labels: Branch-3.3.5a

#26702 Core/Objects: Units possessing another ones must use the detection of the latter
  src/server/game/Entities/Object/Object.cpp
Labels: Branch-3.3.5a

#26783 Core/SAI: Remove SMART_ACTION_SET_DYNAMIC_FLAG
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#26759 Core/Battlegrounds: Remove duplicate info from GroupQueueInfo
  src/server/game/Battlegrounds/BattlegroundQueue.cpp
  src/server/game/Battlegrounds/BattlegroundQueue.h
  src/server/game/Handlers/BattleGroundHandler.cpp
Labels: Branch-master

#26790 Scripts/Spells: Update quest spell scripts to new register model
  src/server/scripts/Spells/spell_quest.cpp
Labels: Branch-3.3.5a

#26791 Scripts/BFD: Update scripts to new register model
  src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.cpp
  src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.h
  src/server/scripts/Kalimdor/BlackfathomDeeps/boss_aku_mai.cpp
  src/server/scripts/Kalimdor/BlackfathomDeeps/boss_gelihast.cpp
  src/server/scripts/Kalimdor/BlackfathomDeeps/boss_kelris.cpp
Labels: Branch-3.3.5a

#26792 Scripts/BM: Update scripts to new register model
  src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_aeonus.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_chrono_lord_deja.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_temporus.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.h
Labels: Branch-3.3.5a

#26793 Scripts/SWP: Update M'uru to new register model
  src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
Labels: Branch-3.3.5a

#26795 Core/Item: Fixed another possible container exploit due to invalid lo…
  src/server/game/Loot/LootItemStorage.cpp
  src/server/game/Loot/LootItemStorage.h
Labels: Branch-3.3.5a

#26778 Scripts/World: improve Training Dummy script
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-3.3.5a

#26789 Scripts/Spells: Fix support for 'Teleport This!' (10857)
  sql/updates/world/3.3.5/2021_08_09_55_world.sql
  src/server/scripts/Outland/zone_netherstorm.cpp
Labels: Branch-3.3.5a

#26797 Core/SAI: Remove SMART_ACTION_INSTALL_AI_TEMPLATE
  sql/updates/world/3.3.5/2021_08_12_06_world.sql
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#26804 Server/Config - Change default settings for saving gm logs.
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a

#26808 Core/Script: fix Silithus Wind Stone exploit
  src/server/scripts/Kalimdor/zone_silithus.cpp
Labels: Branch-3.3.5a

#26630 Scripts/Commands: Convert title commands to new system
  src/server/game/Accounts/RBAC.h
  src/server/scripts/Commands/cs_titles.cpp
Labels: Branch-3.3.5a

#26806 Core/Battlegrounds: Change Battleground* argument to BattlegroundQueueTypeId
  src/server/game/Battlegrounds/BattlegroundMgr.cpp
  src/server/game/Battlegrounds/BattlegroundMgr.h
  src/server/game/Handlers/BattleGroundHandler.cpp
Labels: Branch-master

#26772 Core/AreaTrigger Update box searching to handle oriented boxes
  src/server/game/Entities/AreaTrigger/AreaTrigger.cpp
Labels: Branch-master

#26786 Core/Spells Implement target 135 : TARGET_UNIT_FIRST_IN_LINE
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Entities/Object/Position.cpp
  src/server/game/Entities/Object/Position.h
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellInfo.h
  src/server/game/Spells/SpellMgr.cpp
  src/server/game/Spells/SpellScript.cpp
Labels: Branch-master

#26816 deps/fmt: Upgrade to 7.1.3
  dep/PackageList.txt
  dep/fmt/CONTRIBUTING.md
  dep/fmt/ChangeLog.rst
  dep/fmt/README.rst
  dep/fmt/include/fmt/chrono.h
  dep/fmt/include/fmt/color.h
  dep/fmt/include/fmt/compile.h
  dep/fmt/include/fmt/core.h
  dep/fmt/include/fmt/format-inl.h
  dep/fmt/include/fmt/format.h
  dep/fmt/include/fmt/locale.h
  dep/fmt/include/fmt/os.h
  dep/fmt/include/fmt/ostream.h
  dep/fmt/include/fmt/printf.h
  dep/fmt/include/fmt/ranges.h
  dep/fmt/src/format.cc
  dep/fmt/src/os.cc
Labels: Branch-3.3.5a

#26817 Scripts/Commands: Convert argument parsing of instance commands to new system
  src/server/game/Accounts/RBAC.h
  src/server/scripts/Commands/cs_instance.cpp
Labels: Branch-3.3.5a

#26819 Core/Battlegrounds: Update BattlemasterListFlags
  src/server/game/Achievements/CriteriaHandler.cpp
  src/server/game/DataStores/DB2Structure.h
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Handlers/BattleGroundHandler.cpp
Labels: Branch-master

#26825 Scripts/Commands: Avoid copies of RBACCommandData
  src/server/scripts/Commands/cs_rbac.cpp
Labels: Branch-3.3.5a

#26834 Core/DB: Updated missing check
  src/server/database/Database/DatabaseWorkerPool.cpp
Labels: Branch-3.3.5a

#26833 Core/SAI: Remove no longer used event types & params
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#26840 Revert "Core/SAI: Remove no longer used event types & params"
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#26837 Don't count character pending deletion towards character per account limit
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Server/WorldSession.h
  src/server/game/World/World.cpp
Labels: Branch-3.3.5a

#26811 Core/Config: Implement config override with env vars
  src/common/Configuration/Config.cpp
  src/common/Configuration/Config.h
  src/server/authserver/Main.cpp
  src/server/worldserver/Main.cpp
  tests/common/Config.cpp
Labels: Branch-3.3.5a

#26841 Scripts/Pet: implement Dance Rune Weapon
  sql/updates/world/3.3.5/2021_08_19_03_world.sql
  src/server/game/Globals/ObjectAccessor.cpp
  src/server/scripts/Pet/pet_dk.cpp
  src/server/scripts/Pet/pet_mage.cpp
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-3.3.5a

#26839 Core/Achievements: Several criteria fixes
  src/server/game/Achievements/CriteriaHandler.cpp
  src/server/game/DataStores/DB2Structure.h
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Handlers/LootHandler.cpp
Labels: Branch-master

#26769 Core/Quests: check PreviousQuestID values as well when trying to make quest groups available to players
  src/server/game/Globals/ObjectMgr.cpp
Labels: Sub-Quests, Branch-3.3.5a

#26849 Core/Unit: improve SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL immunities
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#26848 Core/SAI: Change error to warning for unused parameters
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
Labels: Branch-3.3.5a

#26860 Core/Combat Fix first autoattack being skipped after charging
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#26836 Remove combo points on a creature when it evades
  src/server/game/AI/CreatureAI.cpp
Labels: Branch-3.3.5a

#26846 Handle deprecated SAI actions and events
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a
