Repository TrinityCore/TrinityCore, pull requests merged in 2021-02, with the labels that each got.

#26029 Core/Spells Add EffectAttributesFlags with NoScaleWithStack (0x40
  src/server/game/DataStores/DB2Structure.h
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellInfo.h
Labels: Branch-master

#26028 Core/Spells Adding object_type to checker to early-eliminate alive units
  sql/updates/world/master/2021_02_05_00_world_remove_pet_carrion.sql
  src/server/game/Grids/Notifiers/GridNotifiers.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellMgr.h
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp
  src/server/scripts/Spells/spell_generic.cpp
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#26019 Core/Spells: Fix Seed of Corruption (Warlock) target selection
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-3.3.5a

#26011 Core/DataStores: Update check loaded DB2 9.0.2 37176
  src/server/game/DataStores/DB2Stores.cpp
Labels: Branch-master

#25988 Core/Auras: Implement SPELL_AURA_397 & SPELL_AURA_398
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Battlegrounds/Battleground.h
  src/server/game/Battlegrounds/Zones/BattlegroundEY.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundEY.h
  src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundWS.h
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
Labels: Branch-master

#26056 Scripts/Spells: Druid TravelForm freeze fix
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#25997 Scripts/UtgardePinnacle: Svala Sorrowgrave Ritual improvements
  src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp
Labels: Branch-3.3.5a

#26036 Core/Spells - Checking Exile's Reach spell reward
  src/server/game/DataStores/DB2Structure.h
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellInfo.h
Labels: Branch-master

#26055 Core/SmartScripts: new FlagsArgument for SmartActionSummonCreature
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#26065 Core/SmartAI: AI change on charmed
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
Labels: Branch-3.3.5a

#26088 Scripts/Spells: Casting druid spell Prowl auto shapeshifts to cat form
  sql/updates/world/master/2021_02_15_00_world_druid_prowl.sql
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#26102 Core/Conditions: CONDITION_NEAR_CREATURE will exclude other's personal spawns
  src/server/game/Entities/Creature/TemporarySummon.cpp
  src/server/game/Entities/Creature/TemporarySummon.h
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Grids/Notifiers/GridNotifiers.h
Labels: Branch-master

#26104 Scripts/Spells: Implemented druid's Gore
  sql/updates/world/master/2021_02_17_00_world_druid_gore.sql
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#26083 Scripts/Events: Fix achievement in Love is in the air: "Lonely?"
  src/server/scripts/Spells/spell_holiday.cpp
Labels: Branch-3.3.5a

#26100 Core/Unit: Improve Glancing Blow calculation
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#26122 Core/Misc: Updated current expansion config 9.0.2
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-master

#26120 Core/Unit: Fix glancing blow calculation
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#26092 Core/Maps: Use a fixed offset instead of full collision height when retrieving floor Z
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Maps/Map.cpp
  src/server/shared/SharedDefines.h
Labels: Branch-3.3.5a

#26109 Core/Spells: Modable max stack amount
  src/server/game/Spells/Auras/SpellAuras.cpp
  src/server/game/Spells/Auras/SpellAuras.h
Labels: Branch-master

#26020 Scripts/Spells: Prayer of Mending
  sql/updates/world/master/2021_02_21_00_world_priest_prayer_of_mending.sql
  src/server/game/Spells/SpellScript.h
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#26119 CMake: Add WITH_BOOST_STACKTRACE option to use libbacktrace
  cmake/showoptions.cmake
  dep/boost/CMakeLists.txt
Labels: Branch-3.3.5a

#26118 Core/Spells: Warlock Death Coil shouldn't be able to crit
  src/server/game/Spells/SpellMgr.cpp
Labels: Branch-3.3.5a

#26085 Core/Auras: implement mana cost modification aura
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-master

#26103 Scripts/Spells: Implemented druid's Skull Bash
  sql/updates/world/master/2021_02_22_00_world_druid_skull_bash.sql
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#26097 Core/Spells: POWER_BURN should not cancel when target isn't caster
  src/server/game/Spells/Spell.cpp
Labels: Branch-master

#26132 Core/Spells: Apply power pct mod aura when modifying power
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
Labels: Branch-master

#26093 Scripts/Spells: Ferocious bite implemented
  sql/updates/world/master/2021_02_23_00_world_druid_ferocious_bite.sql
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#26134 Core/Spells: Clear the actionbar even when there aren't any results
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#26140 Core/Spells: Corrected the spell id source used in the learn spells map
  src/server/game/Spells/SpellMgr.cpp
Labels: Branch-master

#26145 Core/LFG: Fixed a bug where rolecheck timer was milliseconds
  src/server/game/DungeonFinding/LFGMgr.h
Labels: Branch-3.3.5a

#26148 Scripts/Spells: Remove unused paladin spells
  sql/updates/world/master/2021_02_24_01_world_paladin_spells_remove_unused.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#26149 Scripts/Spells: Changed spells to use RegisterSpellScript and RegisterAuraScript
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#26163 Core/ThreadManager: delete double include "TemporarySummon.h"
  src/server/game/Combat/ThreatManager.cpp
Labels: Branch-3.3.5a

#26169 Core/SAI: Add SAI action to create a conversation
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#26153 Scripts/Spells: Removed unused priest spells
  sql/updates/world/master/2021_02_27_00_world_priest_spells_remove_unused.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#26155 Scripts/Spells: Removed unused hunter spells
  sql/updates/world/master/2021_02_27_01_world_hunter_spells_remove_unused.sql
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#26157 Scripts/Spells: Removed unused rogue spells
  sql/updates/world/master/2021_02_27_02_world_rogue_spells_remove_unused.sql
  src/server/scripts/Spells/spell_rogue.cpp
Labels: Branch-master

#26158 Scripts/Spells: Removed unused shaman spells
  sql/updates/world/master/2021_02_27_03_world_shaman_spells_remove_unused.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#26159 Scripts/Spells: Removed unused warlock spells
  sql/updates/world/master/2021_02_27_04_world_warlock_spells_remove_unused.sql
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-master

#26127 Revive all command
  src/server/scripts/Commands/cs_group.cpp
Labels: Branch-3.3.5a

#26154 Scripts/Spells: Removed unused dk spells
  sql/updates/world/master/2021_02_27_05_world_dk_spells_remove_unused.sql
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-master

#26160 Scripts/Spells: Removed unused warrior spells
  sql/updates/world/master/2021_02_27_06_world_warrior_spells_remove_unused.sql
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#26176 Core/Spells: implement SPELL_AURA_MOD_HEALING_DONE_PCT_VERSUS_TARGET_HEALTH
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-master

#26172 Core/Spells: Add itemTarget check in Spell::EffectEnchantItemTmp
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master

#26141 Core/Scripts: Add SpellInfo argument to ScriptMgr::ModifySpellDamageTaken
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/game/Scripting/ScriptMgr.h
Labels: Branch-master

#26076 Spells/Auras: Dont save SPELL_AURA_BATTLEGROUND_PLAYER_POSITION auras
  src/server/game/Spells/Auras/SpellAuras.cpp
Labels: Branch-master

#26184 Script/Ulduar: Fixed conflict with Random Aggro Periodic spell
  sql/updates/world/3.3.5/2021_02_28_00_world.sql
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_auriaya.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp
  src/server/scripts/Northrend/northrend_script_loader.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances, Sub-Spells
