Repository TrinityCore/TrinityCore, pull requests merged in 2021-03, with the labels that each got.

#26196 Core/AuctionHouse: Fix overflow in item ordering.
  src/server/game/AuctionHouse/AuctionHouseMgr.cpp
Labels: Branch-master

#26205 Core/Spells: Implement aura allow swapping talents
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
Labels: Branch-master

#26151 Core/Unit: Handle SPELLMOD_CRIT_DAMAGE_BONUS also in Unit::SpellCriticalHealingBonus
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-master

#26177 Push docker images to DockerHub
  .circleci/config.yml
  contrib/Docker/README.md
Labels: Branch-3.3.5a

#26200 Scripts/Spells: Refactored dh & dk spells to use the new macros
  src/server/scripts/Spells/spell_dh.cpp
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-master

#26170 Core/SAI: Implement quest source for SAI
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#26206 Core/Spells: Don't save druid various flight forms to db
  src/server/game/Spells/Auras/SpellAuras.cpp
Labels: Branch-master

#26209 Core/SAI: Don't require BaseObject when creating conversation from smart scripts
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Branch-master

#26111 Added druid's guardian spells
  sql/updates/world/master/2021_03_08_00_world_druid_guardian_spells.sql
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#26187 Core/Spells: Apply UNIT_FLAG_IMMUNE after applying SPELL_AURA_DAMAGE_IMMUNITY
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-3.3.5a

#26190 Scripts/The Eye: Update instance script
  sql/updates/world/3.3.5/2021_03_11_06_world.sql
  src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
  src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
  src/server/scripts/Outland/TempestKeep/Eye/instance_the_eye.cpp
  src/server/scripts/Outland/TempestKeep/Eye/the_eye.h
Labels: Branch-3.3.5a

#26198 Scripts/Spells: Feign Death & 'prevent emotes flag' spell scripts
  sql/updates/world/3.3.5/2021_03_11_07_world.sql
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a

#26044 Core/GameObjects: Add GameObjectPlaySpellVisual
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/GameObject/GameObject.h
  src/server/game/Server/Packets/GameObjectPackets.cpp
  src/server/game/Server/Packets/GameObjectPackets.h
Labels: Branch-master

#26215 Core/Player: Update location of cinematic camera only if there is an active cinematic
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#26082 Scripts/Spells: corrections to Death Knight spell Blood Mastery
  sql/updates/world/master/2021_03_15_00_world_dk_blood_mastery.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-master

#26139 Group level up
  src/server/scripts/Commands/cs_group.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix

#26202 Scripts/Ahn'kahet: Herald Volazj texts
  sql/updates/world/3.3.5/2021_03_20_00_world.sql
  src/server/scripts/Northrend/AzjolNerub/Ahnkahet/boss_herald_volazj.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix

#26090 Scripts/Spells: Implemented druid eclipse system
  sql/updates/world/master/2021_03_23_00_world_druid_eclipse.sql
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#26116 Core/Spells: Implement CalcCritChance hooks
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuras.cpp
  src/server/game/Spells/Auras/SpellAuras.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellScript.cpp
  src/server/game/Spells/SpellScript.h
Labels: Branch-master

#26321 Core/Maps: increase value of fixed offset when retrieving floor Z
  src/server/shared/SharedDefines.h
Labels: Branch-3.3.5a

#26165 Core/Spells: Added argument to stop recursive infinite loops
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
Labels: Branch-master

#26217 Core/Spells: Implement SPELL_EFFECT_TELEPORT_TO_RETURN_POINT
  sql/base/characters_database.sql
  sql/updates/characters/master/2021_03_27_00_characters_aura_stored_location.sql
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/database/Database/Implementation/CharacterDatabase.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master

#26231 Core/Maps: Removed duplicate code
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
Labels: Branch-master

#26308 Core/PowerRegen: Reorder CenterPower regen
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master
