Repository TrinityCore/TrinityCore, pull requests merged in 2021-06, with the labels that each got.

#26549 Core/Movement: Add new flag MOVEMENTGENERATOR_FLAG_PERSIST_ON_DEATH
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Movement/MotionMaster.cpp
  src/server/game/Movement/MotionMaster.h
  src/server/game/Movement/MovementGenerator.h
Labels: Branch-3.3.5a

#26568 Scripts/Instances: Update Slave Pens scripts to new register model
  src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_ahune.cpp
  src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_mennu_the_betrayer.cpp
  src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_quagmirran.cpp
  src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_rokmar_the_crackler.cpp
  src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/the_slave_pens.h
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26569 Scripts/Instances: Update Mechanar scripts to new register model
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_pathaleon_the_calculator.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26570 Scripts/Zone: Update Blasted Lands scripts to new register model
  src/server/scripts/EasternKingdoms/zone_blasted_lands.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#26571 Scripts/Zone: Update IoC scripts to new register model
  src/server/scripts/Northrend/IsleOfConquest/boss_ioc_horde_alliance.cpp
  src/server/scripts/Northrend/IsleOfConquest/isle_of_conquest.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#26580 Scripts/Instances/DK: Update Novos to new register model
  src/server/scripts/Northrend/DraktharonKeep/boss_novos.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26581 Scripts/Instances/DK: Update Tharon'ja to new register model
  src/server/scripts/Northrend/DraktharonKeep/boss_tharon_ja.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26582 Scripts/Instances/DK: Update Trollgore to new register model
  src/server/scripts/Northrend/DraktharonKeep/boss_trollgore.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26583 Scripts/Instances/EoE: Update Malygos to new register model
  src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
  src/server/scripts/Northrend/Nexus/EyeOfEternity/eye_of_eternity.h
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26579 Core/SAI: Add support to friendly+hostile to SMART_EVENT_OOC_LOS and SMART_EVENT_IC_LOS
  sql/updates/world/3.3.5/2021_06_08_00_world.sql
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#26567 Scripts/Instances/Underbog: Rework Hungarfen
  sql/updates/world/3.3.5/2021_06_09_00_world.sql
  src/server/scripts/Outland/CoilfangReservoir/TheUnderbog/boss_hungarfen.cpp
  src/server/scripts/Outland/CoilfangReservoir/TheUnderbog/the_underbog.h
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26578 Scripts/Quest: Rework 'Taken by the Scourge' (11611)
  sql/updates/world/3.3.5/2021_06_09_01_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a, Feedback-PatchFix, Sub-Quests, Sub-Spells

#26598 Only complain about missing BOOST_ROOT when Boost is not found
  dep/boost/CMakeLists.txt
Labels: Branch-3.3.5a

#26584 Core/Loot: Allow master looter to see all quest items
  src/server/game/Loot/Loot.cpp
Labels: Branch-3.3.5a

#26561 Core/Movement: Implement proper player speed change
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Entities/Unit/UnitDefines.h
  src/server/game/Handlers/MovementHandler.cpp
  src/server/game/Movement/MovementPacketSender.cpp
  src/server/game/Movement/MovementPacketSender.h
  src/server/game/Server/GameClient.cpp
  src/server/game/Server/GameClient.h
  src/server/game/Server/WorldSession.cpp
  src/server/game/Server/WorldSession.h
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Movement

#26606 Remove now unused CONFIG_SET_SHAPASSHASH config
  src/server/game/World/World.cpp
  src/server/game/World/World.h
Labels: Branch-3.3.5a

#26612 Fix kick after map changed and speed changed
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#26586 Scripts/Commands: Minor improvements in .pinfo and .unban character commands
  sql/updates/world/3.3.5/2021_06_20_00_world.sql
  src/server/game/Miscellaneous/Language.h
  src/server/scripts/Commands/cs_ban.cpp
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a

#26613 Common/Misc: Replace old macros with modern C++ attributes
  src/common/Debugging/Errors.h
  src/common/Define.h
Labels: Branch-3.3.5a

#26616 Clear unused #undef leftover in a refactor
  src/server/game/Handlers/QuestHandler.cpp
Labels: Branch-3.3.5a

#25154 Scripts/SholazarBasin: Make quest "Engineering a Disaster" more retail-like
  sql/updates/world/3.3.5/2021_06_24_05_world.sql
  src/server/scripts/Northrend/zone_sholazar_basin.cpp
Labels: Branch-3.3.5a

#26608 Core/SAI: Add a warning when a boolean value is outside of [0,1] range
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#26625 CI/CircleCI: Force ccache directory
  .circleci/config.yml
Labels: Branch-3.3.5a

#26620 Core/Pools: Fix pools with 1 member never spawning anything anymore
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Maps/Map.cpp
  src/server/game/Pools/PoolMgr.cpp
  src/server/game/Pools/PoolMgr.h
Labels: Branch-3.3.5a

#26627 Build: Remove fine-grained CXX feature checks
  cmake/macros/ConfigureBaseTargets.cmake
Labels: Branch-3.3.5a

#26633 Scripts/Commands: Convert honor command table to new system
  src/server/game/Accounts/RBAC.h
  src/server/scripts/Commands/cs_honor.cpp
Labels: Branch-3.3.5a

#26634 Scripts/Commands: Convert misc command table to new system
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a

#26639 CI/GitHub: Use issue form and add contact links
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue.yml
Labels: Branch-master
