Repository TrinityCore/TrinityCore, pull requests merged in 2021-07, with the labels that each got.

#26648 Scripts/SholazarBasin: Fix a possible nullptr dereference issue found by coverity
  src/server/scripts/Northrend/zone_sholazar_basin.cpp
Labels: Branch-3.3.5a

#26651 CI/GitHub: Add issue form for SQL fixes
  .github/ISSUE_TEMPLATE/issue.yml
  .github/ISSUE_TEMPLATE/sql_fix.yml
  issue_template.md
Labels: Branch-master

#26644 Core/Movement: Fix movement handler crash during ReadMovementInfo check
  src/server/game/Server/WorldSession.cpp
Labels: Branch-3.3.5a

#26661 Scripts/Pet: Update pet scripts to new register model (1/2)
  src/server/scripts/Pet/pet_dk.cpp
  src/server/scripts/Pet/pet_generic.cpp
  src/server/scripts/Pet/pet_hunter.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#26662 Scripts/Pet: Update pet scripts to new register model (2/2)
  src/server/scripts/Pet/pet_mage.cpp
  src/server/scripts/Pet/pet_priest.cpp
  src/server/scripts/Pet/pet_shaman.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix

#26663 Scripts/Spells: Update death knight scripts to new register model
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#26664 Scripts/Spells: Update paladin scripts to new register model
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#26665 Scripts/Spells: Update mage scripts to new register model
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#26666 Scripts/Spells: Update warlock scripts to new register model
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#26667 Scripts/Spells: Update rogue scripts to new register model
  src/server/scripts/Spells/spell_rogue.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#26668 Scripts/Spells: Update Winter Veil holiday scripts to new register model
  src/server/scripts/Spells/spell_holiday.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Spells

#26669 Scripts/The Eye: Update Kael'thas to new register model
  src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26670 Scripts/BT: Remove unconfirmed parts of Teron's intro
  src/server/scripts/Outland/BlackTemple/black_temple.h
  src/server/scripts/Outland/BlackTemple/boss_teron_gorefiend.cpp
  src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-PatchFix, Sub-Instances

#26677 Scripts/SL: Update scripts to new register model
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_ambassador_hellmaw.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_blackheart_the_inciter.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_grandmaster_vorpil.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/shadow_labyrinth.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/shadow_labyrinth.h
Labels: Branch-3.3.5a

#26678 Scripts/SH: Update scripts to new register model
  src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_anzu.cpp
  src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_darkweaver_syth.cpp
  src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp
  src/server/scripts/Outland/Auchindoun/SethekkHalls/sethekk_halls.h
Labels: Branch-3.3.5a

#26679 Scripts/MT: Update scripts to new register model
  src/server/scripts/Outland/Auchindoun/ManaTombs/boss_nexusprince_shaffar.cpp
  src/server/scripts/Outland/Auchindoun/ManaTombs/boss_pandemonius.cpp
  src/server/scripts/Outland/Auchindoun/ManaTombs/mana_tombs.h
Labels: Branch-3.3.5a

#26680 Scripts/Obsidian Sanctum: Update instance scripts to new register model
  src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/obsidian_sanctum.cpp
  src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/obsidian_sanctum.h
Labels: Branch-3.3.5a

#26681 Scripts/Ruby Sanctum: Update Baltharus to new register model
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_baltharus_the_warborn.cpp
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/ruby_sanctum.h
Labels: Branch-3.3.5a

#26682 Scripts/FoS: Update Bronjahm to new register model
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/forge_of_souls.h
Labels: Branch-3.3.5a

#26684 Scripts/ZG: Update scripts to new register model (1/5)
  src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_gahzranka.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_grilek.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/zulgurub.h
Labels: Branch-3.3.5a

#26685 Scripts/SFK: Update Apothecary Hummel to new register model
  src/server/scripts/EasternKingdoms/ShadowfangKeep/boss_apothecary_hummel.cpp
  src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.h
Labels: Branch-3.3.5a

#26686 Scripts/BWL: Update scripts to new register model (1/3)
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/blackwing_lair.h
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_broodlord_lashlayer.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_chromaggus.cpp
Labels: Branch-3.3.5a

#26690 Scripts/BWL: Update scripts to new register model (2/3)
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_ebonroc.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_firemaw.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_flamegor.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp
Labels: Branch-3.3.5a

#26691 Scripts/BWL: Update scripts to new register model (3/3)
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_vaelastrasz.cpp
Labels: Branch-3.3.5a

#26692 Scripts/ZG: Update scripts to new register model (2/5)
  src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_hazzarah.cpp
Labels: Branch-3.3.5a

#26693 Scripts/ZG: Update scripts to new register model (3/5)
  src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_jindo.cpp
Labels: Branch-3.3.5a

#26694 Scripts/ZG: Update scripts to new register model (4/5)
  src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_marli.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_renataki.cpp
Labels: Branch-3.3.5a

#26695 Scripts/ZG: Update scripts to new register model (5/5)
  src/server/scripts/EasternKingdoms/ZulGurub/boss_thekal.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_venoxis.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/boss_wushoolay.cpp
Labels: Branch-3.3.5a

#26696 Scripts/Obsidian Sanctum: Update Sartharion to new register model
  src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp
Labels: Branch-3.3.5a

#26697 Scripts/Ruby Sanctum: Update Zarithrian to new register model
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_general_zarithrian.cpp
Labels: Branch-3.3.5a

#26698 Scripts/Ruby Sanctum: Update Saviana to new register model
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_saviana_ragefire.cpp
Labels: Branch-3.3.5a

#26699 Scripts/Ruby Sanctum: Update instance scripts to new register model
  src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/ruby_sanctum.cpp
Labels: Branch-3.3.5a

#26700 Scripts/FoS: Update remaining scripts to new register model
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_devourer_of_souls.cpp
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/forge_of_souls.cpp
Labels: Branch-3.3.5a

#26703 Scripts/Azjol Nerub: Update Hadronox to new register model
  src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
Labels: Branch-3.3.5a

#26704 Scripts/Azjol Nerub: Update Krik'thir to new register model
  src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_krikthir_the_gatewatcher.cpp
Labels: Branch-3.3.5a

#26705 Scripts/ToC: Update Anub'arak to new register model
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
Labels: Branch-3.3.5a

#26706 Scripts/ToC: Update Faction Champions to new register model
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp
Labels: Branch-3.3.5a

#26707 Scripts/ToC: Update remaining scripts of Beasts of Northrend to new register model
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp
Labels: Branch-3.3.5a

#26708 Scripts/ToC: Update Twin Val'kyr to new register model
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_twin_valkyr.cpp
Labels: Branch-3.3.5a

#26709 Scripts/Molten Core: Update remaining scripts to new register model (1/2)
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_baron_geddon.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_gehennas.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_lucifron.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_magmadar.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_majordomo_executus.cpp
Labels: Branch-3.3.5a

#26710 Scripts/Molten Core: Update remaining scripts to new register model (2/2)
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_ragnaros.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_shazzrah.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_sulfuron_harbinger.cpp
Labels: Branch-3.3.5a

#26628 Core/SAI: Warn when an unused parameter is set in the database
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
Labels: Branch-3.3.5a

#26674 Core/Pet: Don't allow to tame pets that have already a owner
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-3.3.5a

#26701 Core/Spells: PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW applies only with invisibility type INVISIBILITY_GENERAL (0)
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-3.3.5a

#26689 [Exploit/Dupe] Container item
  sql/base/characters_database.sql
  sql/updates/characters/3.3.5/2021_07_18_00_characters.sql
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Loot/Loot.cpp
  src/server/game/Loot/Loot.h
  src/server/game/Loot/LootItemStorage.cpp
  src/server/game/Loot/LootItemStorage.h
Labels: Branch-3.3.5a

#26724 Game/Event: zone_hellfire_peninsula.cpp
  sql/updates/world/3.3.5/2021_07_21_03_world.sql
  src/server/scripts/Outland/zone_hellfire_peninsula.cpp
Labels: Branch-3.3.5a

#26730 Cmake
  cmake/macros/FindOpenSSL.cmake
Labels: Branch-3.3.5a

#26742 Core/Spells: defined and implemented SPELL_ATTR7_CANT_DODGE, SPELL_ATTR7_CANT_PARRY and SPELL_ATTR7_CANT_MISS
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/shared/SharedDefines.h
  src/server/shared/enuminfo_SharedDefines.cpp
Labels: Branch-3.3.5a

#26711 Core/Spawns: prevent spawn groups from bypassing spawnMask restrictions
  src/server/game/Maps/Map.cpp
Labels: Branch-3.3.5a

#26733 Core/DBLayer: Add QueueSize() method
  contrib/grafana/4_Performance_profiling.json
  src/common/Threading/ProducerConsumerQueue.h
  src/server/database/Database/DatabaseWorkerPool.cpp
  src/server/database/Database/DatabaseWorkerPool.h
  src/server/scripts/Commands/cs_server.cpp
  src/server/worldserver/Main.cpp
Labels: Branch-3.3.5a

#26758 Core/Quests: Improve ItemRemovedQuestCheck logic
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#26723 Core/Network: Add option to allow/disallow saving IP addresses to database
  src/server/authserver/Server/AuthSession.cpp
  src/server/authserver/authserver.conf.dist
  src/server/game/Server/WorldSocket.cpp
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a

#26760 Core/Quest: When removing an item required for a quest, update every quest in the quest log instead of stopping at the first objective that matches the removed item.
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#26762 Core/Creature: rename CREATURE_FLAG_EXTRA_IGNORE_COMBAT into CREATURE_FLAG_EXTRA_CANNOT_ENTER_COMBAT
  src/server/game/Combat/CombatManager.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
Labels: Branch-3.3.5a
