Repository TrinityCore/TrinityCore, pull requests merged in 2021-10, with the labels that each got.

#26915 Core/AH: Add search delay to SMSG_AUCTION_BIDDER_LIST_RESULT and SMSG_AUCTION_OWNER_LIST_RESULT
  src/server/game/Handlers/AuctionHouseHandler.cpp
Labels: Branch-3.3.5a

#26911 Core/Misc: Improvement item durability repair logic.
  src/server/game/Entities/Item/Item.cpp
  src/server/game/Entities/Item/Item.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Guilds/Guild.cpp
  src/server/game/Guilds/Guild.h
  src/server/game/Handlers/NPCHandler.cpp
Labels: Branch-3.3.5a

#26886 Flash worldserver on taskbar on thread start
  src/server/worldserver/CommandLine/CliRunnable.cpp
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a

#26873 Core/Units: removed an incorrect addition of SPELL_AURA_MOD_CRIT_CHANCE_FOR_CASTER benefits
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-3.3.5a

#26859 Core/Combat Improve extra attacks handling
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-3.3.5a

#26949 Core/Globals: Fix repeat validate when the spell has multiple scripts
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#26987 Skip proccing Sheath of Light when at full health
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-3.3.5a

#26988 Core/Auras: Implemented SPELL_AURA_COSMETIC_MOUNTED
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#26906 Core/Gossip: Update GossipOptionIcon enum
  src/server/game/AI/ScriptedAI/ScriptedGossip.cpp
  src/server/game/AI/ScriptedAI/ScriptedGossip.h
  src/server/game/Entities/Creature/GossipDef.cpp
  src/server/game/Entities/Creature/GossipDef.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Server/Packets/NPCPackets.h
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_tomb_of_seven.cpp
  src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp
  src/server/scripts/EasternKingdoms/MagistersTerrace/magisters_terrace.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp
  src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp
  src/server/scripts/Kalimdor/zone_dustwallow_marsh.cpp
  src/server/scripts/Kalimdor/zone_thunder_bluff.cpp
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
  src/server/scripts/Northrend/Ulduar/HallsOfStone/halls_of_stone.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Northrend/zone_dragonblight.cpp
  src/server/scripts/Northrend/zone_howling_fjord.cpp
  src/server/scripts/Northrend/zone_storm_peaks.cpp
  src/server/scripts/Northrend/zone_wintergrasp.cpp
  src/server/scripts/Outland/zone_zangarmarsh.cpp
  src/server/scripts/World/go_scripts.cpp
  src/server/scripts/World/npc_innkeeper.cpp
  src/server/scripts/World/npc_professions.cpp
Labels: Branch-master

#27016 Core/Quest: Fill in data for QuestPackageID field SendQuestGiverQuest…
  src/server/game/Entities/Creature/GossipDef.cpp
Labels: Branch-master

#26985 Core/Spells: implemented Wind Rush Totem
  sql/updates/world/master/2021_10_03_06_world_shaman_wind_rush_totem.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master, hacktoberfest-accepted

#26990 Core/BattlePets: Misc fixes
  src/server/game/BattlePets/BattlePetMgr.cpp
  src/server/game/BattlePets/BattlePetMgr.h
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master, hacktoberfest-accepted

#27006 Core/Spells: Implemented Sigil of Silence/Misery/Flame/Chains
  sql/updates/world/master/2021_10_03_07_world_dh_sigils.sql
  src/server/scripts/Spells/spell_dh.cpp
Labels: Branch-master, hacktoberfest-accepted

#26895 Core/Vendors: Support for vendors with empty inventory list
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Handlers/ItemHandler.cpp
Labels: Branch-master

#26974 Core/Characters: Added allied race creation data, implemented intro s…
  sql/updates/world/master/2021_10_05_03_world_allied_races.sql
  src/server/game/Entities/Player/Player.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-master

#26975 Core/Scenes: defined flags and implemented some
  src/server/game/Entities/Player/SceneDefines.h
  src/server/game/Entities/Player/SceneMgr.cpp
  src/server/game/Entities/Player/SceneMgr.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Commands/cs_scene.cpp
Labels: Branch-master

#27005 Core/Spells: Fixed Consecration
  sql/updates/world/master/2021_10_05_04_world_pala_consecration.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master, hacktoberfest-accepted

#26997 Script/Commands: Allow to specify the target player in .additem command
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a, hacktoberfest-accepted

#27004 Scripts/Commands: account onlinelist
  src/server/scripts/Commands/cs_account.cpp
Labels: Branch-3.3.5a, hacktoberfest-accepted
