Repository TrinityCore/TrinityCore, pull requests merged in 2021-12, with the labels that each got.

#27274 Scripts/ZG: Improve High Priestess Jeklik
  sql/updates/world/3.3.5/2021_12_01_00_world.sql
  src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
Labels: Branch-3.3.5a

#27277 Scripts/Mechanar: Rework Nethermancer Sepethrea
  sql/updates/world/3.3.5/2021_12_01_01_world.sql
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp
Labels: Branch-3.3.5a

#27282 Scripts/Botanica: Rework Laj
  sql/updates/world/3.3.5/2021_12_01_02_world.sql
  src/server/scripts/Outland/TempestKeep/botanica/boss_laj.cpp
  src/server/scripts/Outland/TempestKeep/botanica/the_botanica.h
Labels: Branch-3.3.5a

#27304 Scripts/The Eye: Few updates to Kael'thas & Astromancer
  sql/updates/world/3.3.5/2021_12_01_03_world.sql
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
Labels: Branch-3.3.5a

#27305 Scripts/Spells: Generic spell script for quest portals
  sql/updates/world/3.3.5/2021_12_01_04_world.sql
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
  src/server/scripts/Spells/spell_quest.cpp
Labels: Branch-3.3.5a

#27313 Scripts/Crypts: Rework Exarch Maladaar
  sql/updates/world/3.3.5/2021_12_01_05_world.sql
  src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/auchenai_crypts.h
  src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_exarch_maladaar.cpp
Labels: Branch-3.3.5a

#27321 Core/Conditions: Added CONDITION_SOURCE_TYPE_TRAINER_SPELL
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Conditions/ConditionMgr.h
  src/server/game/Entities/Creature/Trainer.cpp
  src/server/game/Entities/Creature/Trainer.h
Labels: Branch-master

#27336 Core/SAI: Misc fixes
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Branch-master

#27357 Scripts/HoL: Update Sjonnir
  sql/updates/world/3.3.5/2021_12_09_05_world.sql
  src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_sjonnir.cpp
Labels: Branch-3.3.5a

#27360 Scripts/HoL: Update Maiden of Grief
  src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_maiden_of_grief.cpp
Labels: Branch-3.3.5a

#27367 Core/BattlePets: Improvements when enabling battle pets
  sql/updates/world/master/2021_12_10_00_world.sql
  src/server/game/BattlePets/BattlePetMgr.cpp
  src/server/game/BattlePets/BattlePetMgr.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Handlers/BattlePetHandler.cpp
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master

#27383 Core/BattlePets: Added default cooldown to revive battle pets. SpellHistory updates
  src/server/game/BattlePets/BattlePetMgr.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Spells/SpellHistory.cpp
  src/server/game/Spells/SpellHistory.h
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#27394 Scripts/Quest: Update 'It's All Fun and Games' (12887,12892)
  sql/updates/world/3.3.5/2021_12_13_03_world.sql
  src/server/scripts/Northrend/zone_icecrown.cpp
Labels: Branch-3.3.5a

#27280 Core/Battlegrounds: Avoid reset BG and Arena scoreboard stats and BG map achievement criterias when relogin if player was already in the BG
  src/server/game/Battlegrounds/Arena.cpp
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundAB.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundEY.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
Labels: Branch-3.3.5a

#27403 Scripts/Spells: Furious Rage & scripts for creatures who uses it
  sql/updates/world/3.3.5/2021_12_16_00_world.sql
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a

#27414 Core/Battlegrounds: Avoid teleport players when relogin inside Strand of the Ancients
  src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp
Labels: Branch-3.3.5a

#27415 Core/Spells: Fix priest Mind bomb
  sql/updates/world/master/2021_12_17_00_world_priest_mind_bomb.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#27412 Tools/MMAPs: Show an error when running mmaps_generator built in Debug mode
  src/tools/mmaps_generator/PathGenerator.cpp
Labels: Branch-3.3.5a

#27395 Core/Spells: Fix incanters flow
  sql/updates/world/master/2021_12_18_04_world_mage_incanters_flow.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-master

#27418 Add item xxxxx show to who was added item (one more time). Update cs_misc.cpp
  src/server/scripts/Commands/cs_misc.cpp
Labels: Branch-3.3.5a

#27413 Scripts/Quest: Rework 'The Cleansing' (11317,11322)
  sql/updates/world/3.3.5/2021_12_18_08_world.sql
  src/server/scripts/Northrend/zone_howling_fjord.cpp
  src/server/scripts/Spells/spell_generic.cpp
  src/server/scripts/World/go_scripts.cpp
Labels: Branch-3.3.5a

#27420 Spells/Priest: Fix masochism talent
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#27426 Spells/Paladin: Fix talent eye for an eye
  sql/updates/world/master/2021_12_19_00_world_paladin_eye_for_an_eye.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#27425 Core/Spells: Implemented spell effect 204 (SPELL_EFFECT_CHANGE_BATTLEPET_QUALITY)
  src/server/game/BattlePets/BattlePetMgr.cpp
  src/server/game/BattlePets/BattlePetMgr.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master

#27348 Core/Misc: Verify LFG role selections by class
  src/server/game/DungeonFinding/LFGMgr.cpp
  src/server/game/DungeonFinding/LFGMgr.h
Labels: Branch-3.3.5a

#27437 Scripts/Spells: Update Gordunni Trap spell script
  sql/updates/world/3.3.5/2021_12_23_02_world.sql
  src/server/scripts/Kalimdor/zone_feralas.cpp
Labels: Branch-3.3.5a

#27452 Core/SAI: Remove SMART_ACTION_SEND_GO_CUSTOM_ANIM, make SMART_ACTION_ADD_AURA & SMART_ACTION_SET_GO_FLAG deprecated
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-3.3.5a

#27457 Shaman new style scripts
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#27440 Spells/Warlock: Fix shadow bolt energize
  sql/updates/world/master/2021_12_25_00_world_warlock_shadow_bolt.sql
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-master

#27442 Spells/Paladin: Fix holy prism
  sql/updates/world/master/2021_12_25_01_world_paladin_holy_prism.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#27446 Core/BattlePets: Misc fixes
  sql/updates/world/master/2021_12_25_02_world.sql
  src/server/game/BattlePets/BattlePetMgr.cpp
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Entities/Creature/TemporarySummon.cpp
  src/server/game/Entities/Totem/Totem.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master

#27029 Core/SAI: added new action type SMART_ACTION_ADD_TO_STORED_TARGET_LIST
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#27455 Core/SpellAuras: Implemented SPELL_AURA_TRIGGER_SPELL_ON_HEALTH_PCT
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
Labels: Branch-master

#27461 Core/SAI: Use GetBaseObject as second param of SMART_ACTION_ACTIVATE_GAMEOBJECT & reorder GameObjectActions
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/Entities/GameObject/GameObject.cpp
Labels: Branch-3.3.5a

#26319 [WIP] Core/Spells: Implemented various rogue spells:
  sql/updates/world/master/2021_12_25_03_world_spells_rogue.sql
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellScript.cpp
  src/server/game/Spells/SpellScript.h
  src/server/scripts/Spells/spell_rogue.cpp
Labels: Branch-master

#27467 Spells/Shaman: Fix lightning bolt energize (elemental)
  sql/updates/world/master/2021_12_25_04_world_shaman_lightning_bolt.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#27468 Spells/Shaman: Fix chain lightning energize (elemental)
  sql/updates/world/master/2021_12_25_05_world_shaman_chain_lightning.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#25926 Core/Player: implement Stage 1 of WarMode
  sql/updates/world/master/2021_12_26_00_world.sql
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/database/Database/Implementation/CharacterDatabase.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/Packets/SystemPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/WorldSession.h
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/scripts/Commands/cs_debug.cpp
  src/server/scripts/Spells/spell_generic.cpp
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-master

#27469 Spells/Shaman: Fix talent aftershock
  sql/updates/world/master/2021_12_26_01_world_shaman_aftershock.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#27477 Spells/Shaman: Fix talent Downpour
  sql/updates/world/master/2021_12_26_02_world_shaman_downpour.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#27434 Core/AI: Fix crashes caused by charmed Creatures having null AI for 1 map update tick
  src/server/game/AI/CoreAI/ScheduledChangeAI.cpp
  src/server/game/AI/CoreAI/ScheduledChangeAI.h
  src/server/game/AI/CreatureAIRegistry.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
Labels: Branch-3.3.5a, Sub-AI

#24758 Core/ZoneScript: Add "invoker" param to ProcessEvent
  src/server/game/Battlefield/Zones/BattlefieldTB.cpp
  src/server/game/Battlefield/Zones/BattlefieldTB.h
  src/server/game/Battlefield/Zones/BattlefieldWG.cpp
  src/server/game/Battlefield/Zones/BattlefieldWG.h
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Maps/ZoneScript.h
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp
  src/server/scripts/EasternKingdoms/MagistersTerrace/instance_magisters_terrace.cpp
  src/server/scripts/EasternKingdoms/Uldaman/instance_uldaman.cpp
  src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/boss_horAI.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/instance_halls_of_reflection.cpp
  src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
  src/server/scripts/Northrend/Nexus/EyeOfEternity/instance_eye_of_eternity.cpp
  src/server/scripts/Northrend/Nexus/Oculus/instance_oculus.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
  src/server/scripts/Northrend/VioletHold/instance_violet_hold.cpp
Labels: Branch-master

#26345 Core/Phasing: Implemented personal phase with objects
  sql/updates/world/master/2021_12_28_00_world_trinity_string_phaseshift_status.sql
  src/server/game/Entities/Player/CinematicMgr.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Events/GameEventMgr.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Grids/ObjectGridLoader.cpp
  src/server/game/Grids/ObjectGridLoader.h
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
  src/server/game/Maps/MapObject.h
  src/server/game/Phasing/PersonalPhaseTracker.cpp
  src/server/game/Phasing/PersonalPhaseTracker.h
  src/server/game/Phasing/PhaseShift.cpp
  src/server/game/Phasing/PhaseShift.h
  src/server/game/Phasing/PhasingHandler.cpp
  src/server/game/Phasing/PhasingHandler.h
  src/server/game/Pools/PoolMgr.cpp
  src/server/scripts/Commands/cs_debug.cpp
  src/server/scripts/Commands/cs_gobject.cpp
  src/server/scripts/Commands/cs_misc.cpp
  src/server/scripts/Commands/cs_npc.cpp
Labels: Branch-master

#27482 Spells/Scripts: Fix nature's guardian proc (shaman)
  sql/updates/world/master/2021_12_28_01_world_shaman_natures_guardian.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#27491 Implement SPELL_AURA_MOD_MELEE_DAMAGE_FROM_CASTER (343)
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-master

#27488 Core/Spells: Implemented spell effect 286 (SPELL_EFFECT_GRANT_BATTLEPET_EXPERIENCE)
  src/server/game/Achievements/CriteriaHandler.cpp
  src/server/game/BattlePets/BattlePetMgr.cpp
  src/server/game/BattlePets/BattlePetMgr.h
  src/server/game/DataStores/DBCEnums.h
  src/server/game/DataStores/GameTables.cpp
  src/server/game/DataStores/GameTables.h
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Spell.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master
