Repository TrinityCore/TrinityCore, pull requests merged in 2022-10, with the labels that each got.

#28287 Fix *BSD compile errors
  dep/g3dlite/G3D-v9.0 hotfix16.diff
  dep/g3dlite/source/FileSystem.cpp
  src/common/Utilities/Util.cpp
  src/tools/vmap4_extractor/vmapexport.cpp
Labels: Branch-3.3.5a

#28286 Core/Spells: fixed up block mechanics
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Spell.cpp
  src/server/shared/SharedDefines.h
  src/server/shared/enuminfo_SharedDefines.cpp
Labels: Branch-3.3.5a

#28272 Zone/Silverpine: Added spawns in phase 169 in Forsaken High Command
  sql/updates/world/master/2022_10_01_00_world.sql
  src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp
Labels: Branch-master

#28273 Zone/Silverpine: Implemented Horde Hauler (npcId 44731)
  sql/updates/world/master/2022_10_01_01_world.sql
  src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master

#28297 Fix(Script/Quest): Unfit for Death
  sql/updates/world/3.3.5/2022_10_02_00_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a

#28300 Fix(Script/SAI) Quest "Aces High!"
  sql/updates/world/3.3.5/2022_10_02_01_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a

#28315 Core/Spells: make Spell::CheckMovement respect the current spell state
  src/server/game/Spells/Spell.cpp
Labels: Branch-master

#28308 Add(Script/Cosmetic) Add super awesome most needed party time script
  sql/updates/world/3.3.5/2022_10_04_00_world.sql
  src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
  src/server/scripts/EasternKingdoms/zone_eversong_woods.cpp
Labels: Branch-3.3.5a

#28343 Core/Game: Fix FlaggedValuesArray32 flags overflow for InvisibilityType because TOTAL_INVISIBILITY_TY…
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
Labels: Branch-master

#28333 Core/Spells: fixed Rime talent
  sql/updates/world/master/2022_10_07_01_world.sql
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-master

#28254 Core/Gossips: Drop OptionNpcFlag for gossip_menu_option
  sql/updates/world/master/2022_10_09_09_world.sql
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-master

#28345 Core/Spells: Take SummonProperties into account for SPELL_EFFECT_SUMMONs with default SummonTitle
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master, hacktoberfest-accepted

#28275 Zone/Silverpine: Implemented Waiting to Exsanguinate (questId 27045)
  sql/updates/world/master/2022_10_10_00_world.sql
  src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master

#28303 Scripts/Silverpine: quest fixes and spawns for Forsaken Rear Guard
  sql/updates/world/master/2022_10_11_00_world.sql
  src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master, hacktoberfest-accepted

#28356 Core/Spells: Move draenor spell to generic spell
  sql/updates/world/master/2022_10_11_01_world.sql
  src/server/scripts/Draenor/zone_draenor_shadowmoon_valley.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master

#28256 Core/Garrisons: Implement SMSG_GARRISON_OPEN_TALENT_NPC opcode
  sql/updates/hotfixes/master/2022_10_11_00_hotfixes.sql
  sql/updates/world/master/2022_10_11_04_world.sql
  src/server/database/Database/Implementation/HotfixDatabase.cpp
  src/server/database/Database/Implementation/HotfixDatabase.h
  src/server/game/DataStores/DB2LoadInfo.h
  src/server/game/DataStores/DB2Stores.cpp
  src/server/game/DataStores/DB2Stores.h
  src/server/game/DataStores/DB2Structure.h
  src/server/game/Entities/Creature/GossipDef.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Server/Packets/GarrisonPackets.cpp
  src/server/game/Server/Packets/GarrisonPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/World/World.cpp
Labels: Branch-master

#28347 Core/Game: Write directly to UpdateData's ByteBuffer
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Updates/UpdateData.cpp
  src/server/game/Entities/Object/Updates/UpdateData.h
Labels: Branch-3.3.5a, hacktoberfest-accepted

#28334 Scripts/Silverpine: fixed Fenris Isle quests
  sql/updates/world/master/2022_10_12_00_world.sql
  src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp
Labels: Branch-master, hacktoberfest-accepted

#28304 Fix(Script/Quest) Help Those That Cannot Help Themselves
  sql/updates/world/3.3.5/2022_10_14_00_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/World/item_scripts.cpp
Labels: Branch-3.3.5a, hacktoberfest-accepted

#28306 Fix(Script/Quest) Abduction
  sql/updates/world/3.3.5/2022_10_14_01_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a, hacktoberfest-accepted

#28328 fix(Script/Quest) Last Rites
  sql/updates/world/3.3.5/2022_10_14_02_world.sql
  src/server/scripts/Northrend/zone_borean_tundra.cpp
Labels: Branch-3.3.5a, hacktoberfest-accepted

#28386 Scripts/Durotar: Fix ship arrived gossip for Mith'aka
  sql/updates/world/master/2022_10_22_00_world.sql
  src/server/scripts/Kalimdor/zone_durotar.cpp
Labels: Branch-master

#28396 update conf: added missing conf
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-master

#28378 CI/AppVeyor: Upgrade image to Visual Studio 2022
  appveyor.yml
Labels: Branch-master

#28384 Core/POIs: Rename field Unknown905 to WMOGroupId
  sql/updates/world/master/2022_10_25_00_world.sql
  src/server/game/Entities/Creature/GossipDef.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Server/Packets/NPCPackets.cpp
  src/server/game/Server/Packets/NPCPackets.h
Labels: Branch-master

#28387 Core/Quests: Send Offer Reward Window for non-repeatable autocomplete quests
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#28414 Core/Gossip: Add/Remove spell for disable/enable experience in group
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#28410 Core/Object: Implement FindNearestCreatureWithAura
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Grids/Notifiers/GridNotifiers.h
Labels: Branch-master

#28417 Core/SAI: Move (any) value for SMART_EVENT_MOVEMENTINFORM to -1
  sql/updates/world/master/2022_10_31_03_world.sql
  src/server/game/AI/SmartScripts/SmartScript.cpp
Labels: Branch-master
