Repository TrinityCore/TrinityCore, pull requests merged in 2022-09, with the labels that each got.

#28224 Core/Gossip: Dropped HandleGossipOption and CanTalkTo from OutdoorPvP and move the related stuff to npc script
  sql/updates/world/master/2022_09_02_00_world.sql
  src/server/game/Entities/Player/Player.cpp
  src/server/game/OutdoorPvP/OutdoorPvP.cpp
  src/server/game/OutdoorPvP/OutdoorPvP.h
  src/server/game/OutdoorPvP/OutdoorPvPMgr.cpp
  src/server/game/OutdoorPvP/OutdoorPvPMgr.h
  src/server/scripts/OutdoorPvP/OutdoorPvPZM.cpp
  src/server/scripts/OutdoorPvP/OutdoorPvPZM.h
Labels: Branch-master

#28200 Core/Battlegrounds: Capture flag immediately when standing on capture point and your team's flag return due to drop timer ended
  src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundWS.h
Labels: Branch-3.3.5a

#28199 Core/Misc: Store vectors of abilities per skilline
  src/server/game/DataStores/DBCStores.cpp
  src/server/game/DataStores/DBCStores.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Commands/cs_learn.cpp
Labels: Branch-3.3.5a

#28227 Fix herbalism, mining and skinning failing at low levels
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#28189 Core/Creature: Name more static flags
  src/server/game/Entities/Creature/CreatureData.h
Labels: Branch-master

#28217 Core/Creatures: Don't remove hovering from creatures that can fly
  src/server/game/Entities/Creature/Creature.cpp
Labels: Branch-master

#28226 Core/Auras: Implement SPELL_AURA_MOD_BONUS_ARMOR_PCT and rename HandleModStatBonusArmor
  src/server/game/Entities/Unit/StatSystem.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
Labels: Branch-master

#28220 Core/Gossips: Drop OptionType for gossip_menu_option
  sql/updates/world/master/2022_09_08_00_world.sql
  src/server/game/AI/ScriptedAI/ScriptedGossip.cpp
  src/server/game/AI/ScriptedAI/ScriptedGossip.h
  src/server/game/Entities/Creature/GossipDef.cpp
  src/server/game/Entities/Creature/GossipDef.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Handlers/SkillHandler.cpp
  src/server/game/Server/Packets/NPCPackets.h
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_tomb_of_seven.cpp
  src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Northrend/zone_wintergrasp.cpp
  src/server/scripts/World/go_scripts.cpp
  src/server/scripts/World/npc_professions.cpp
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-master

#28234 fix (event): Hourly Bell Correction
  src/server/scripts/World/go_scripts.cpp
Labels: Branch-3.3.5a

#28240 Core/Gossips: Fixed loading of ActionPoiID data
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#28239 Core/Units: Update collision height calculation
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-master

#27910 Scripts/Battle for Mount Hyjal:Fix wrong npc text,trash movment,archimode last phase
  sql/updates/world/3.3.5/2022_09_11_00_world.sql
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.h
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp
  src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#28188 Core/World: Include more details about MaxCoreStuckTime asserts
  src/server/worldserver/Main.cpp
Labels: Branch-3.3.5a

#28247 Fix PLAYER_POSITION_UPDATE_INTERVAL
  src/server/game/Battlegrounds/Battleground.h
Labels: Branch-master

#28257 Core/Player: Allow companion action buttons to be saved
  sql/base/characters_database.sql
  sql/updates/characters/master/2022_09_18_00_characters.sql
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Server/Packets/SpellPackets.h
Labels: Branch-master

#28258 Core/Spells: Fix glyph of stars (druid)
  sql/updates/world/master/2022_09_19_00_world_druid_glyph_of_stars.sql
  src/server/game/Entities/Unit/Unit.cpp
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#28251 Zone/Silverpine: fixed quest The Warchief Cometh (26965)
  sql/updates/world/master/2022_09_21_00_world.sql
  src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
  src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp
Labels: Branch-master

#28280 Scripts/HoS: modernized Halls of Stone instance script
  src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_sjonnir.cpp
  src/server/scripts/Northrend/Ulduar/HallsOfStone/halls_of_stone.h
  src/server/scripts/Northrend/Ulduar/HallsOfStone/instance_halls_of_stone.cpp
Labels: Branch-3.3.5a

#28281 Core/Units: Set UNIT_FLAG2_UNTARGETABLE_BY_CLIENT as allowed flag
  src/server/game/Entities/Unit/UnitDefines.h
Labels: Branch-master

#28285 Core/Packets: Fixed load PreloadPos in enum charactes packet.
  src/server/game/Server/Packets/CharacterPackets.cpp
Labels: Branch-master

#28282 Reworked Volkhan Encounter
  sql/updates/world/3.3.5/2022_09_25_02_world.sql
  src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_volkhan.cpp
  src/server/scripts/Northrend/Ulduar/HallsOfLightning/halls_of_lightning.h
  src/server/scripts/Northrend/Ulduar/HallsOfLightning/instance_halls_of_lightning.cpp
Labels: Branch-3.3.5a

#28290 Core/Guilds: Improve `SMSG_GUILD_ROSTER` performance
  src/server/game/Guilds/Guild.cpp
Labels: Branch-3.3.5a
