Repository TrinityCore/TrinityCore, pull requests merged in 2022-05, with the labels that each got.

#27935 Core/GroupMgr: Execute all group related database cleanup at the beginning of LoadGroups.
  src/server/game/Groups/GroupMgr.cpp
Labels: Branch-master

#27937 Scripts/Naxxramas: Fix achievement The Immortal / The Undying
  src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp
Labels: Branch-3.3.5a

#27933 Core/Spells: Paladin's Judgements can be applied on different targets at the same time
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-3.3.5a

#27972 Core/SAI: Removed checker of Action id in SMART_EVENT_ACTION_DONE, this should not check what id choose the developer.
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
Labels: Branch-master

#27974 Core/Creature - correctly apply npc pvp flags
  src/server/game/Entities/Creature/Creature.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a
