Repository TrinityCore/TrinityCore, pull requests merged in 2022-12, with the labels that each got.

#28544 Core/Player: Vertical "Say" distance
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Grids/Notifiers/GridNotifiers.cpp
  src/server/game/Grids/Notifiers/GridNotifiers.h
Labels: Branch-3.3.5a

#28382 Core/Items: Dropped deprecated ItemFlag2 ITEM_FLAG2_DONT_IGNORE_BUY_PRICE
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Entities/Item/ItemTemplate.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Handlers/ItemHandler.cpp
Labels: Branch-master

#28411 Core/Creatures: Never enable gravity for creatures that can only fly
  src/server/game/Entities/Creature/Creature.cpp
Labels: Branch-master

#28448 Core/Units: Implemented UNIT_VIS_FLAGS_INVISIBLE
  src/server/game/Entities/Unit/UnitDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-master

#28545 Conversation: Implement Conversation::Start and added autoStart as pa…
  src/server/game/Entities/Conversation/Conversation.cpp
  src/server/game/Entities/Conversation/Conversation.h
Labels: Branch-master

#28611 GameObjects/CapturePoints: Update Map SpawnGroupConditions immediately after UpdateCapturePoint
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Maps/Map.h
Labels: Branch-master

#28489 [Core/Creatures]: Implement SummonPropertiesFlags::AttackableBySummoner
  src/server/game/Entities/Object/Object.cpp
Labels: Branch-master

#28555 Core/SAI: Added param PointId to SMART_ACTION_MOVE_OFFSET
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#28582 Core/Spells: resurrection after raise ally
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-3.3.5a

#28372 Core/Scripts: Implemented Zort's Protective Elixir
  sql/updates/world/3.3.5/2022_12_23_00_world.sql
  src/server/scripts/Northrend/zone_dragonblight.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#28488 [Scripting/Helper]: Implement FindNearestCreatureWithOptions
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Grids/Notifiers/GridNotifiers.h
  src/server/game/Phasing/PhasingHandler.cpp
  src/server/game/Phasing/PhasingHandler.h
Labels: Branch-master

#28500 [Creature/Scripting]: Implement StringId for Creatures, assigning a…
  sql/updates/world/master/2022_12_27_01_world.sql
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/game/AI/ScriptedAI/ScriptedCreature.h
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Grids/Notifiers/GridNotifiers.h
  src/server/game/Maps/SpawnData.h
  src/server/game/Miscellaneous/Language.h
  src/server/scripts/Commands/cs_npc.cpp
Labels: Branch-master

#28632 Core/Vmaps: Fix inconsistency of hitInstance and hitModel to cause wr…
  src/common/Collision/Maps/MapTree.h
  src/common/Collision/Models/GameObjectModel.cpp
  src/common/Collision/Models/ModelInstance.cpp
  src/common/Collision/Models/WorldModel.cpp
  src/common/Collision/Models/WorldModel.h
Labels: Branch-master

#28511 Core/Auras: Implement SPELL_AURA_MOD_STUN_DISABLE_GRAVITY
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
  src/server/game/Spells/Spell.cpp
Labels: Branch-master

#28517 Core/Auras: Implement SPELL_AURA_MOD_ROOT_DISABLE_GRAVITY
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
Labels: Branch-master

#28515 [Core/CrashFix] Fix crash in Unit::CalcHealAbsorb
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-master

#28519 Core/SAI: Add extra action param 7
  sql/updates/world/master/2022_12_30_01_world.sql
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScript.h
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#28547 Core/SAI: Improve SMART_ACTION_JUMP_TO_POS
  sql/updates/world/master/2022_12_30_02_world.sql
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#28548 Object/Visiblity: Dont check for IsObjectMeetingVisibilityByObjectIdC…
  src/server/game/Entities/Object/Object.cpp
Labels: Branch-master

#28556 Core/Movement: Don't compute orientation for vertical splines
  src/server/game/Movement/Spline/MoveSpline.cpp
Labels: Branch-master
