Repository TrinityCore/TrinityCore, pull requests merged in 2022-02, with the labels that each got.

#27677 Scripts/Quest: Rework Mystery of the Infinite & Mystery of the Infinite, Redux
  sql/updates/world/3.3.5/2022_02_01_02_world.sql
  src/server/scripts/Northrend/zone_dragonblight.cpp
  src/server/scripts/Spells/spell_generic.cpp
  src/server/scripts/Spells/spell_quest.cpp
Labels: Branch-3.3.5a

#27701 Core/Spells: Avoid leave combat with Invisibility (mage) in certain situations
  src/server/game/Spells/Auras/SpellAuras.cpp
Labels: Branch-3.3.5a

#27700 Core/Scripts/SAI: Fix Silithus Wind Stones
  sql/updates/world/3.3.5/2022_02_04_00_world.sql
  src/server/scripts/Kalimdor/zone_silithus.cpp
Labels: Branch-3.3.5a

#27669 Core/Opcodes: Basic implementation of SMSG_DISPLAY_TOAST
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Server/Packets/ItemPacketsCommon.cpp
  src/server/game/Server/Packets/MiscPackets.cpp
  src/server/game/Server/Packets/MiscPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
Labels: Branch-master

#27682 Script/Spells: fixed Ashen Hallow
  sql/updates/world/master/2022_02_06_00_world.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Sub-Spells, Branch-master

#27689 Core/Conditions: Implemented CONDITION_BATTLEPET_JOURNAL for know if …
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Conditions/ConditionMgr.h
Labels: Branch-master

#27693 Scripts/Spells: fixed Light's Hammer
  sql/updates/world/master/2022_02_06_01_world.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Sub-Spells, Branch-master

#27706 Core/BattlePets: Delete declined names of non-account battle pets
  src/server/database/Database/Implementation/LoginDatabase.cpp
  src/server/database/Database/Implementation/LoginDatabase.h
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#27695 Core/Spells: Fix shaman undulation talent
  sql/updates/world/master/2022_02_06_02_world_shaman_undulation.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#27699 Core/Spells: Fix icefury talent proc and energize
  sql/updates/world/master/2022_02_07_00_world_shaman_icefury.sql
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-master

#27708 [Transport/TempSummon]: Fixed if a TempSummon spawns that it gets add…
  src/server/game/Entities/Object/Object.cpp
Labels: Branch-master

#27710 Core/Spells: Fix mage Comet Storm
  sql/updates/world/master/2022_02_07_01_world_mage_comet_storm.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Sub-Spells, Branch-master

#27712 Scripts/Spells: fixed Art of War
  sql/updates/world/master/2022_02_07_02_world.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Sub-Spells, Branch-master

#27714 Core/Spells: Implement SPELL_ATTR7_BYPASS_NO_RESURRECT_AURA
  src/server/game/Handlers/SpellHandler.cpp
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Miscellaneous/enuminfo_SharedDefines.cpp
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-master

#27715 Core/Spells: Implement SPELL_ATTR7_CANT_DODGE, SPELL_ATTR7_CANT_PARRY…
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Miscellaneous/enuminfo_SharedDefines.cpp
Labels: Branch-master

#27717 Spells: Implement CAST_FLAG_EX_IGNORE_COOLDOWN
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/Spell.h
Labels: Sub-Spells, Branch-master

#27716 Core/SmoothPhasing: Instead of using the copied object as a summoner,…
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/Entities/Creature/TemporarySummon.cpp
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/scripts/Commands/cs_debug.cpp
Labels: Branch-master

#27718 Core/Scripts: Added script hook to execute actions after completing an achievement
  sql/updates/world/master/2022_02_08_00_world.sql
  src/server/game/Achievements/AchievementMgr.cpp
  src/server/game/Achievements/AchievementMgr.h
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/game/Scripting/ScriptMgr.h
  src/server/game/World/World.cpp
  src/server/scripts/World/achievement_scripts.cpp
Labels: Branch-master

#27749 Scripts/Items: Fix Goblin Bomb Dispenser
  sql/updates/world/3.3.5/2022_02_09_04_world.sql
  src/server/scripts/Spells/spell_item.cpp
Labels: Branch-3.3.5a

#27719 Scripts/Spells: fixed Divine Purpose
  sql/updates/world/master/2022_02_10_00_world.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#27721 Scripts/Spells: fixed Power Word: Shield
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#27722 Scripts/Spells: fixed Blizzard
  sql/updates/world/master/2022_02_10_02_world.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-master

#27723 Scripts/Spells: fixed Infusion of Light
  sql/updates/world/master/2022_02_13_00_world.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#27724 Core/BattlePets: Implemented CMSG_BATTLE_PET_UPDATE_NOTIFY
  src/server/game/BattlePets/BattlePetMgr.cpp
  src/server/game/BattlePets/BattlePetMgr.h
  src/server/game/Handlers/BattlePetHandler.cpp
  src/server/game/Server/Packets/BattlePetPackets.cpp
  src/server/game/Server/Packets/BattlePetPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/WorldSession.h
Labels: Branch-master

#27726 Core/spells: Fix presence of mind proc
  sql/updates/world/master/2022_02_13_01_world_mage_presence_of_mind.sql
Labels: Branch-master

#27767 Scripts/TK: Update remaining scripts to new register model 1
  src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.cpp
  src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.h
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_dalliah_the_doomsayer.cpp
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_harbinger_skyriss.cpp
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_wrath_scryer_soccothrates.cpp
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_zereketh_the_unbound.cpp
Labels: Branch-3.3.5a

#27768 Scripts/TK: Update remaining scripts to new register model 2
  src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
  src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
Labels: Branch-3.3.5a

#27730 Core/Spells: Fix priest Twist of Fate
  sql/updates/world/master/2022_02_13_02_world_priest_twist_of_fate.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#27732 Core/Spells: Fix priest talent power word solace
  sql/updates/world/master/2022_02_13_03_world_priest_power_word_solace.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#27736 Core/Spells: Fix monk roll
  sql/updates/world/master/2022_02_14_03_world_monk_roll.sql
  src/server/scripts/Spells/spell_monk.cpp
Labels: Branch-master

#27737 Scripts/Spells: updated Penance
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#27744 [Crash/ScriptMgr]: Fix Hotswap not reinitializing AIs after destroying them and then crashing due to unhandled AI checks
  src/server/game/Scripting/ScriptMgr.cpp
Labels: Branch-master

#27750 Core/Attributes: Implement SPELL_ATTR3_NO_DURABILITY_LOSS
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Miscellaneous/enuminfo_SharedDefines.cpp
Labels: Branch-master

#27752 Scripts/Spells: Convert rogue spell scripts to new script registrati…
  src/server/scripts/Spells/spell_rogue.cpp
Labels: Branch-master

#27759 Core/Spells: Fix rune of power
  sql/updates/world/master/2022_02_15_00_world_mage_rune_of_power.sql
Labels: Sub-Spells, Branch-master

#27781 Core/Auras: Implement SPELL_AURA_MOD_ENVIRONMENTAL_DAMAGE_TAKEN
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-master

#27784 Scripts/Spells: Scent of Blood (DK) shouldn't remove old buff before proccing again
  sql/updates/world/3.3.5/2022_02_16_02_world_335.sql
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-3.3.5a

#27783 Core/Auras: Fix SPELL_AURA_MOD_DAMAGE_DONE_FOR_MECHANIC for effects m…
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master

#25233 Switch from instance->GetPlayers loop to InstanceScript::DoOnPlayers
  src/server/game/Instances/InstanceScript.cpp
  src/server/game/Maps/Map.h
  src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/obsidian_sanctum.cpp
  src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_shirrak_the_dead_watcher.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_grandmaster_vorpil.cpp
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp
Labels: Branch-master

#27786 Core/Auras: Implement SPELL_AURA_IGNORE_DUAL_WIELD_HIT_PENALTY
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-master

#27765 Scripts/SL: Update Grandmaster Vorpil
  sql/updates/world/3.3.5/2022_02_17_00_world.sql
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_grandmaster_vorpil.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a

#27769 Scripts/TK: Few updates for Sepethrea
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp
Labels: Branch-3.3.5a

#27779 Scripts/Spells: Script A Mysterious Voice from Ahn'kahet
  sql/updates/world/3.3.5/2022_02_17_01_world.sql
  src/server/scripts/Northrend/AzjolNerub/Ahnkahet/ahnkahet.cpp
  src/server/scripts/Northrend/AzjolNerub/Ahnkahet/ahnkahet.h
  src/server/scripts/Northrend/AzjolNerub/Ahnkahet/instance_ahnkahet.cpp
  src/server/scripts/Northrend/northrend_script_loader.cpp
Labels: Branch-3.3.5a

#27782 Scripts/Quest: Update 'Torture the Torturer'
  sql/updates/world/3.3.5/2022_02_17_02_world.sql
  src/server/scripts/Northrend/zone_dragonblight.cpp
Labels: Branch-3.3.5a

#27815 Core/AI: Change m_originalCaster to m_caster when calling OnSpellStart
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#27817 Scripts/Antorus: updated Garothi Worldbreaker initialization and setup for dynamic spawns
  src/server/scripts/Argus/AntorusTheBurningThrone/boss_garothi_worldbreaker.cpp
Labels: Branch-master

#27799 Fix typos for auras
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-3.3.5a

#27812 Core/Spells: removed hackfix for Elemental Oath and replaced it with a proper implementation
  sql/updates/world/3.3.5/2022_02_22_00_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Spells/spell_shaman.cpp
Labels: Branch-3.3.5a

#27821 Scripts/Misc: Adjustments to previous fixes
  src/server/scripts/Northrend/AzjolNerub/Ahnkahet/boss_herald_volazj.cpp
  src/server/scripts/Northrend/DraktharonKeep/drak_tharon_keep.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Northrend/zone_dragonblight.cpp
  src/server/scripts/Northrend/zone_howling_fjord.cpp
  src/server/scripts/Northrend/zone_icecrown.cpp
  src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
  src/server/scripts/Outland/TempestKeep/botanica/boss_laj.cpp
  src/server/scripts/Outland/zone_netherstorm.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a

#27823 Scripts/Events: Update event scripts to new register model 1
  sql/updates/world/3.3.5/2022_02_25_00_world.sql
  src/server/scripts/Events/brewfest.cpp
  src/server/scripts/Events/hallows_end.cpp
  src/server/scripts/Events/love_is_in_the_air.cpp
  src/server/scripts/Events/lunar_festival.cpp
Labels: Branch-3.3.5a

#27824 Scripts/Events: Update event scripts to new register model 2
  sql/updates/world/3.3.5/2022_02_25_01_world.sql
  src/server/scripts/Events/operation_gnomeregan.cpp
  src/server/scripts/Events/pilgrims_bounty.cpp
  src/server/scripts/Events/winter_veil.cpp
  src/server/scripts/Events/zalazane_fall.cpp
Labels: Branch-3.3.5a

#27828 Scripts/Quest: Few updates to Zul'drak scripts
  sql/updates/world/3.3.5/2022_02_26_00_world.sql
  src/server/scripts/Northrend/zone_zuldrak.cpp
Labels: Branch-3.3.5a

#27790 Core/Auras: Implement SPELL_AURA_FORCE_BREATH_BAR
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Spells/Auras/SpellAuraDefines.h
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.h
Labels: Branch-master

#27808 Core/Quests: Fixes player choice response selection to use correct referenced ident…
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Handlers/QuestHandler.cpp
  src/server/game/Server/Packets/QuestPackets.cpp
  src/server/game/Server/Packets/QuestPackets.h
Labels: Branch-master

#27800 Scripts/Spells: fixed Rapture
  sql/updates/world/master/2022_02_26_00_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#27833 Tool/MMAP: Fixed invalid check causing certain tiles not to build
  src/tools/mmaps_generator/MapBuilder.cpp
Labels: Branch-3.3.5a

#27832 Scripts/Quest: Update 'Mounting Hodir's Helm'
  sql/updates/world/3.3.5/2022_02_27_00_world.sql
  src/server/scripts/Northrend/zone_storm_peaks.cpp
  src/server/scripts/Spells/spell_quest.cpp
Labels: Branch-3.3.5a
