Repository TrinityCore/TrinityCore, pull requests merged in 2022-06, with the labels that each got.

#28001 Scripts/Quest: Rework 'The Way to His Heart...' & make SAI's StopFollow work again
  sql/updates/world/3.3.5/2022_06_04_00_world.sql
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/scripts/Northrend/zone_howling_fjord.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a

#27962 Core/Items: Fix weapon transmogrification
  src/server/game/Handlers/TransmogrificationHandler.cpp
Labels: Branch-master

#27964 Core/SAI: Added Action SMART_ACTION_DO_ACTION for trigger DoAction on AI
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#27975 Core/PacketIO: Implement CMSG_CANCEL_MOD_SPEED_NO_CONTROL_AURAS
  src/server/game/Handlers/SpellHandler.cpp
  src/server/game/Server/Packets/SpellPackets.cpp
  src/server/game/Server/Packets/SpellPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/WorldSession.h
Labels: Branch-master

#27977 Core/Spells - correction for setting pvp flag for players
  src/server/game/Spells/Spell.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#28006 Creature Animation: Remove Set Facing Call
  src/server/game/Entities/Unit/Unit.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#27993 Tools/Extractors: Implement remote casc mode
  src/tools/extractor_common/CascHandles.cpp
  src/tools/extractor_common/CascHandles.h
  src/tools/map_extractor/System.cpp
  src/tools/vmap4_extractor/vmapexport.cpp
Labels: Branch-master

#28013 Scripts/Quest: Rework 'The Perfect Dissemblance' (12260) & 'A Fall From Grace' (12274) & Bombard the Ballistae (12232) & Without a Prayer (12254)
  sql/updates/world/3.3.5/2022_06_09_00_world.sql
  src/server/scripts/Northrend/zone_dragonblight.cpp
Labels: Branch-3.3.5a

#28015 Scripts/Quest: Migrate few quest spell scripts to zone files
  sql/updates/world/3.3.5/2022_06_09_01_world.sql
  src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
  src/server/scripts/EasternKingdoms/zone_eastern_plaguelands.cpp
  src/server/scripts/EasternKingdoms/zone_undercity.cpp
  src/server/scripts/Kalimdor/zone_azuremyst_isle.cpp
  src/server/scripts/Kalimdor/zone_dustwallow_marsh.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Spells/spell_quest.cpp
Labels: Branch-3.3.5a

#28025 Scripts/Spells: Rework Fire Bomb (Halaa)
  sql/updates/world/3.3.5/2022_06_12_00_world.sql
  src/server/scripts/Outland/zone_nagrand.cpp
Labels: Branch-3.3.5a

#28031 [3.3.5] MariaDB support for Ubuntu 22.04
  src/server/database/Database/DatabaseWorkerPool.cpp
Labels: Branch-3.3.5a

#28027 Core/Spells: Fix druid talent Lunar Inspiration
  sql/updates/world/master/2022_06_16_00_world_druid_lunar_inspiration.sql
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#28026 Core/Spells: Fix druid talent Warrior of Elune proc
  sql/updates/world/master/2022_06_16_01_world_druid_warrior_of_elune.sql
Labels: Branch-master

#28028 Core/Spells: Update some spell scripts (also fixes lifebloom final heal)
  src/server/scripts/Spells/spell_druid.cpp
Labels: Branch-master

#27992 Core/Player: GetWeaponForAttack ranged check
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#28019 Core/Scripts: Fix hunter talent Posthaste
  sql/updates/world/master/2022_06_16_03_world_hunter_posthaste.sql
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#28034 Scripts/Quest: Rework 'Mending Fences' (12915)
  sql/updates/world/3.3.5/2022_06_16_01_world.sql
  src/server/scripts/Northrend/zone_storm_peaks.cpp
Labels: Branch-3.3.5a

#28040 Scripts/UB: Rework The Black Stalker
  sql/updates/world/3.3.5/2022_06_20_01_world.sql
  src/server/scripts/Outland/CoilfangReservoir/TheUnderbog/boss_the_black_stalker.cpp
Labels: Branch-3.3.5a

#28011 Core/Conditions: Added CONDITION_SCENE_IN_PROGRESS, useful for cases where you need phase things when a scene is in progress.
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Conditions/ConditionMgr.h
Labels: Branch-master

#28048 Scripts/Spells: Get rid of several DB spell scripts
  sql/updates/world/3.3.5/2022_06_22_00_world.sql
  src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp
  src/server/scripts/Northrend/Nexus/Nexus/boss_ormorok.cpp
  src/server/scripts/Northrend/zone_dragonblight.cpp
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp
  src/server/scripts/Spells/spell_item.cpp
  src/server/scripts/Spells/spell_quest.cpp
Labels: Branch-3.3.5a

#28039 [3.3.5] Fixed MariaDB connector the easy way for the client version check
  src/server/database/Database/DatabaseWorkerPool.cpp
Labels: Branch-3.3.5a

#28053 Scripts/Oculus: Update Drakos the Interrogator
  sql/updates/world/3.3.5/2022_06_24_00_world.sql
  src/server/scripts/Northrend/Nexus/Oculus/boss_drakos.cpp
Labels: Branch-3.3.5a

#28058 Scripts/Spells: Correctly implement Murmur's Touch & Dire Brew
  sql/updates/world/3.3.5/2022_06_26_00_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
  src/server/scripts/Spells/spell_item.cpp
Labels: Branch-3.3.5a

#28059 Core/SAI: Rename LeavingWorld to OnDespawn & use it in SAI
  src/server/game/AI/CoreAI/UnitAI.h
  src/server/game/AI/SmartScripts/SmartAI.cpp
  src/server/game/AI/SmartScripts/SmartAI.h
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/scripts/Pet/pet_generic.cpp
Labels: Branch-3.3.5a
