Repository TrinityCore/TrinityCore, pull requests merged in 2023-05, with the labels that each got.

#28953 Core/Cinematic: Fix crash CinematicMgr::UpdateCinematicLocation
  src/server/game/Entities/Player/CinematicMgr.cpp
  src/server/game/Entities/Player/CinematicMgr.h
Labels: Branch-3.3.5a

#28943 Core/Spells: Implement SpellAuraInterruptFlags2::LeaveArenaOrBattleground
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Spells/SpellDefines.h
Labels: Branch-master

#28944 Core/Spells: Implement SpellAuraInterruptFlags2::AbandonVehicle
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/SpellDefines.h
Labels: Branch-master

#28942 Core/Spells: Implement SpellAuraInterruptFlags2::EnteringInstance
  src/server/game/Maps/Map.cpp
  src/server/game/Spells/SpellDefines.h
Labels: Branch-master

#28940 Core/Spells: Implement SpellAuraInterruptFlags2::DuelEnd
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Spells/SpellDefines.h
Labels: Branch-master

#28938 Core/Spells: Implement SpellAuraInterruptFlags2::StartOfEncounter
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Instances/InstanceScript.cpp
  src/server/game/Spells/SpellDefines.h
Labels: Branch-master

#28939 Core/Spells: Implement SpellAuraInterruptFlags2::EndOfEncounter
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Instances/InstanceScript.cpp
  src/server/game/Spells/SpellDefines.h
Labels: Branch-master

#28937 Core/Spells: Implement SpellAuraInterruptFlags2::WarModeLeave
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Spells/SpellDefines.h
Labels: Branch-master

#28941 Core/Spells: Implement SpellAuraInterruptFlags2::Falling
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Spells/SpellDefines.h
Labels: Branch-master

#28862 TaskScheduler cleanup
  src/common/Utilities/TaskScheduler.cpp
  src/common/Utilities/TaskScheduler.h
Labels: Branch-master

#28924 Spells/Priest: Update Halo
  sql/updates/world/master/2023_05_07_04_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#28962 CircleCI build fix
  sql/base/auth_database.sql
Labels: Branch-3.3.5a

#28925 Spells/Priest: Implement Dark Reprimand
  sql/updates/world/master/2023_05_07_05_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#28926 Spells/Priest: Implement Purge the Wicked
  sql/updates/world/master/2023_05_07_06_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#28928 Spells/Priest: Implement Painful Punishment
  sql/updates/world/master/2023_05_07_07_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#28508 Core/Battlegrounds: Move AreaSpiritGuides to script & spell system
  sql/updates/world/master/2023_mm_dd_xx_world_spirit_guides.sql
  src/server/game/Battlefield/Battlefield.cpp
  src/server/game/Battlefield/Battlefield.h
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Battlegrounds/Battleground.h
  src/server/game/Battlegrounds/BattlegroundMgr.cpp
  src/server/game/Battlegrounds/BattlegroundMgr.h
  src/server/game/Battlegrounds/Zones/BattlegroundAB.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Handlers/BattleGroundHandler.cpp
  src/server/game/Handlers/NPCHandler.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/SpellEffects.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/scripts/Battlefield/BattlefieldTB.cpp
  src/server/scripts/Battlefield/BattlefieldTB.h
  src/server/scripts/EasternKingdoms/zone_tol_barad.cpp
  src/server/scripts/Northrend/zone_wintergrasp.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master

#28897 Core/Creature: Allow any creature to update display power when created
  src/server/game/DataStores/DB2Structure.h
  src/server/game/DataStores/DBCEnums.h
Labels: Branch-master

#28979 Correct distance check in HandleAreaSpiritHealerQueryOpcode and Handl…
  src/server/game/Battlegrounds/Battleground.h
  src/server/game/Handlers/BattleGroundHandler.cpp
Labels: Branch-master

#28974 Scripts/Spells: Implement Shield Charge
  sql/updates/world/master/2023_05_15_00_world.sql
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#28987 Scripts/Spells: Implement Brutal Vitality
  sql/updates/world/master/2023_05_18_00_world.sql
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#28994 Scripts/Spells: Implement Warbreaker and In For The Kill
  sql/updates/world/master/2023_05_18_01_world.sql
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#29004 Scripts/Warrior: Implement Shield Block
  sql/updates/world/master/2023_05_18_02_world.sql
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#29008 Core/Areas: Update AreaFlags from EnumeratedStings values
  src/server/game/Achievements/CriteriaHandler.cpp
  src/server/game/DataStores/DB2Structure.h
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Handlers/BattleGroundHandler.cpp
  src/server/game/Maps/TerrainMgr.cpp
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/SpellEffects.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/scripts/Spells/spell_item.cpp
Labels: Branch-master

#29011 test fix docker
  .circleci/config.yml
  CMakeLists.txt
  contrib/Docker/Dockerfile
Labels: Branch-master

#29005 Scripts/Warrior: Implement Critical Thinking
  sql/updates/world/master/2023_05_21_00_world.sql
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#29003 Core/Graveyards: Fix graveyards in subzones when there is no valid graveyard in that subzone
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
Labels: Branch-master

#29009 Players/Dungeons&Raids: Respawn alive at graveyard
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#28883 Core/StatSystem: Fixed missing calls to set negative attack power mods
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/StatSystem.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#29032 Core/Spells: Implement SPELL_ATTR10_RESET_COOLDOWN_ON_ENCOUNTER_END
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-master

#29028 Spells/Priest: Implement Say Your Prayers
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master
