Repository TrinityCore/TrinityCore, pull requests merged in 2023-03, with the labels that each got.

#28829 Core/Misc: Update SkillLine and LockType definitions (Dragonflight)
  src/server/game/Miscellaneous/SharedDefines.h
Labels: Branch-master

#28810 Scripts/AV: Implement Leymor encounter
  sql/updates/world/master/2023_03_02_03_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/DragonIsles/AzureVault/azure_vault.h
  src/server/scripts/DragonIsles/AzureVault/boss_leymor.cpp
  src/server/scripts/DragonIsles/AzureVault/instance_azure_vault.cpp
  src/server/scripts/DragonIsles/dragon_isles_script_loader.cpp
Labels: Branch-master

#28802 Update (core\log): Log correction
  src/server/game/World/World.cpp
  src/server/scripts/Commands/cs_reload.cpp
Labels: Branch-3.3.5a

#28844 Core/Mail: Fix error handling with empty bag.
  src/server/game/Handlers/MailHandler.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#28836 Core/Item: Fixed incorrect damage mod for Heirloom 2H weapons
  src/server/game/Entities/Player/Player.cpp
  src/server/shared/DataStores/DBCStructure.h
Labels: Feedback-PatchFix, Branch-3.3.5a

#28853 Core/DataStores: Fixed loading CommonData when IdTable is present
  src/common/DataStores/DB2FileLoader.cpp
Labels: Branch-master

#28835 Core/Handlers: Remove player from group on Faction Change if two side interaction group is not allowed.
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/game/Handlers/CharacterHandler.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#28838 Core/Fishing: Update correct fishing skill according to area expansion
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Miscellaneous/SharedDefines.h
Labels: Branch-master

#28827 Core/Spells: Allow implicit targeting of serverside WorldObjects
  src/server/game/Entities/AreaTrigger/AreaTrigger.h
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/GameObject/GameObject.h
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Spells/SpellInfo.cpp
Labels: Branch-master

#28860 Core/Auras: Implement caster selection of SPELL_AURA_TRIGGER_SPELL_ON_EXPIRE (stored in MiscValue)
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
Labels: Branch-master

#28811 Implement group ready check response
  src/server/game/Handlers/GroupHandler.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#28861 Core/Skinning: Update correct skinning skill according to creature expansion
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Spells/Spell.cpp
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master

#28871 Core/Creatures: Compute the level from ContentTuning
  sql/updates/world/master/2023_03_31_00_world.sql
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Miscellaneous/SharedDefines.h
Labels: Branch-master

#28889 Scripts/Deepholm: Scripted quest "All Our Friends Are Dead"
  sql/updates/world/master/2023_03_31_02_world.sql
  src/server/scripts/Maelstrom/maelstrom_script_loader.cpp
  src/server/scripts/Maelstrom/zone_deepholm.cpp
Labels: Branch-master
