Repository TrinityCore/TrinityCore, pull requests merged in 2024-02, with the labels that each got.

#29639 Fix typo in worldstate expression execution
  src/server/game/Conditions/ConditionMgr.cpp
Labels: Branch-master

#29648 Core/Achievements: Fixed updating EarnAchievement criteria type for guilds and quest objectives
  src/server/game/Achievements/AchievementMgr.cpp
  src/server/game/Quests/QuestObjectiveCriteriaMgr.cpp
  src/server/game/Quests/QuestObjectiveCriteriaMgr.h
Labels: Branch-master

#29638 Fix typo in Player.cpp
  src/server/game/Entities/Player/Player.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#29668 DB/Channels: Allow name to be accent-sensitive
  sql/base/characters_database.sql
  sql/updates/characters/3.3.5/2024_02_05_00_characters.sql
Labels: Branch-3.3.5a

#29623 Re-sizing the Situation - Exile's Reach
  sql/updates/world/master/2024_02_05_00_world.sql
  src/server/scripts/ExilesReach/zone_exiles_reach.cpp
Labels: Branch-master

#29649 Scripts/Spells: Implemented Priest talent Blaze of Light
  sql/updates/world/master/2024_02_05_01_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29641 Scripts/Spells: Mind Blast procs auras
  sql/updates/world/master/2024_02_05_02_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29657 Scripts/Priest: Implemented Priest talent Surge of Light
  sql/updates/world/master/2024_02_05_03_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29671 Scripts/Spells: Implemented Priest talent Heaven's Wrath
  sql/updates/world/master/2024_02_07_00_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29645 Core/Spells: Immune a reflected spell if the original caster cannot be it's target.
  src/server/game/Spells/Spell.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#29683 Scripts/Spells: Implemented Priest talent Divine Aegis/ Fixed PW:S Crit
  sql/updates/world/master/2024_02_10_04_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29677 Scripts/Spells: Implemented Priest talent Crystalline Reflection
  sql/updates/world/master/2024_02_10_05_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29676 Scripts/Spells: Implemented Priest talent Train of Thought
  sql/updates/world/master/2024_02_11_00_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29665 Core/Quests: Don't send update of already completed CriteriaTree objectives to the client when accepting quests
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#29587 Restore old guild functionality
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Guilds/Guild.cpp
  src/server/game/Guilds/Guild.h
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Handlers/ChatHandler.cpp
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Server/Packets/BattlenetPackets.cpp
  src/server/game/Server/Packets/CharacterPackets.cpp
  src/server/game/Server/Packets/QueryPackets.cpp
  src/server/game/Server/WorldSession.h
  src/server/game/Services/ClubMembershipService.cpp
  src/server/game/Services/ClubMembershipService.h
  src/server/game/Services/ClubService.cpp
  src/server/game/Services/ClubService.h
  src/server/game/Services/ClubUtils.cpp
  src/server/game/Services/ClubUtils.h
  src/server/game/Services/WorldserverGameUtilitiesService.h
  src/server/game/Services/WorldserverServiceDispatcher.cpp
  src/server/game/Services/WorldserverServiceDispatcher.h
  src/server/proto/BattlenetRpcErrorCodes.h
Labels: Branch-master

#29691 Core/Gossips: Don't send NpcInteraction for GossipOptionNpc::None
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#29695 Core/Misc: Defined and implemented CHARACTER_FLAG_RESTING
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Server/Packets/CharacterPackets.cpp
Labels: Branch-master

#29730 Core/Spells: Fix SPELLVALUE_CRIT_CHANCE
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#29720 Scripts/Spells: Implemented Priest talent Pain Transformation
  sql/updates/world/master/2024_02_22_03_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29707 Core/Spells: allow players to absorb fire damage from environmental damage spell effects
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#29663 Scripts/Sunken Temple: fix Shade of Eranikus and Jammal'an the Prophet
  sql/updates/world/3.3.5/2024_02_23_00_world.sql
  src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
  src/server/scripts/EasternKingdoms/SunkenTemple/sunken_temple.h
Labels: Branch-3.3.5a

#29635 Core/Scripts: Implemented Elwynn Lamb minipet feature.
  sql/updates/world/3.3.5/2024_02_23_01_world.sql
  src/server/scripts/Pet/pet_generic.cpp
Labels: Branch-3.3.5a

#29593 Scripts/Zul'Gurub: Fixed Edge of Madness
  sql/updates/world/3.3.5/2024_02_23_02_world.sql
  src/server/scripts/EasternKingdoms/ZulGurub/zulgurub.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/zulgurub.h
  src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#29682 Scripts/ForbiddenReach: Added spawn handling for Intro personal summons
  sql/updates/world/master/2024_02_24_00_world.sql
  src/server/scripts/DragonIsles/zone_the_forbidden_reach.cpp
Labels: Branch-master

#29744 Core/Vehicle: Don't set movementInfo on vehicle dismiss
  src/server/game/Handlers/VehicleHandler.cpp
Labels: Branch-master

#29646 Core/Creatures: Implemented UNIT_NPC_FLAG_GOSSIP as viewer dependent …
  src/server/game/Entities/Object/Updates/ViewerDependentValues.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Handlers/QuestHandler.cpp
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Commands/cs_quest.cpp
Labels: Branch-master

#29743 Spells/Priest: Update Vampiric touch script implementing the talent M…
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29626 Core/PacketIO: Implemented CMSG_CHECK_IS_ADVENTURE_MAP_POI_VALID and ...
  src/server/game/Handlers/AdventureMapHandler.cpp
  src/server/game/Server/Packets/AdventureMapPackets.cpp
  src/server/game/Server/Packets/AdventureMapPackets.h
  src/server/game/Server/Protocol/Opcodes.cpp
  src/server/game/Server/WorldSession.h
Labels: Branch-master

#29670 Exile's Reach - Ride SE Boar, Re-Deather and Stocking Up quest
  sql/updates/world/master/2024_02_24_01_world.sql
  src/server/scripts/ExilesReach/zone_exiles_reach.cpp
Labels: Branch-master

#29596 Scripts/Stratholme: Portcullis Trap
  src/server/scripts/EasternKingdoms/Stratholme/instance_stratholme.cpp
  src/server/scripts/EasternKingdoms/Stratholme/stratholme.h
Labels: Feedback-PatchFix, Branch-3.3.5a

#29749 Scripts/Spells: Fix Shield of the Righteous armor bonus
  sql/updates/world/master/2024_02_25_00_world.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#29748 Scripts/Spells: Fix energize for spell Doom (Warlock)
  sql/updates/world/master/2024_02_25_01_world.sql
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-master

#29740 [BG] Alterac Valley: Remove Honorable Defender buff
  src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#29637 Update High Interrogator Gerstahn spell entries
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_high_interrogator_gerstahn.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#29494 Core/Units: update the splines that are being initialized in Unit::SetFacing methods right away
  src/server/game/Entities/Unit/Unit.cpp
Labels: Branch-master

#29755 Core/Characters: Fix error when changing race/faction with some races
  src/server/game/Handlers/CharacterHandler.cpp
Labels: Branch-master

#29582 Never save player's gold to db separately from their inventory.
  src/server/game/AuctionHouse/AuctionHouseMgr.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Guilds/Guild.cpp
  src/server/game/Handlers/MailHandler.cpp
Labels: Branch-master

#29573 Improvements for power regeneration.
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
Labels: Feedback-PatchFix, Branch-3.3.5a

#29687 Battlegrounds/Isle of Conquest: Rework
  sql/updates/world/master/2024_02_26_11_world.sql
  src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp
  src/server/game/Battlegrounds/Zones/BattlegroundIC.h
  src/server/game/Spells/SpellEffects.cpp
  src/server/scripts/Northrend/IsleOfConquest/isle_of_conquest.cpp
Labels: Branch-master

#29759 Spells/DK: Fix talent permafrost
  sql/updates/world/master/2024_02_27_00_world.sql
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-master

#29541 Core/Creatures: migrate creature_template_movement into static flags
  sql/updates/world/master/2024_02_29_00_world.sql
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/Creature.h
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Entities/Unit/UnitDefines.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
  src/server/game/Movement/PathGenerator.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/scripts/EasternKingdoms/zone_dun_morogh_area_coldridge_valley.cpp
  src/server/scripts/ExilesReach/zone_exiles_reach.cpp
  src/server/scripts/Kalimdor/zone_durotar.cpp
Labels: Branch-master

#29766 Core/Movement: require a minimum wander_distance value of 0.1
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
Labels: Branch-master

#29421 Core/Packets: Rename instance of `templat` to `templateInfo`.
  src/server/game/Server/Packets/AuthenticationPackets.cpp
Labels: Branch-master
