Repository TrinityCore/TrinityCore, pull requests merged in 2024-06, with the labels that each got.

#30019 Allow ESFW to be built independently of WITH_DYNAMIC_LINKING option
  cmake/options.cmake
  dep/CMakeLists.txt
  dep/efsw/CMakeLists.txt
  src/server/game/CMakeLists.txt
Labels: Branch-3.3.5a

#29920 Scripts/DK: Attempt to fix a Death Pact exploit
  src/server/scripts/Spells/spell_dk.cpp
Labels: Feedback-FixOutdatedMissingWIP, Branch-3.3.5a

#30013 Core/Misc: Added Loading.Locales to enable/disable the load of locales
  src/server/game/DataStores/DB2Stores.cpp
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Quests/QuestDef.cpp
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-master

#29997 Core/Disables: Added DISABLE_TYPE_PHASE_AREA
  src/server/game/Conditions/DisableMgr.cpp
  src/server/game/Conditions/DisableMgr.h
  src/server/game/Phasing/PhasingHandler.cpp
Labels: Branch-master

#30000 Scripts/StormsongValley-ish: Added scripts for old god forces for Kul Tiran unlock questline in Port Fogtide Part 1 / K'thir
  sql/updates/world/master/2024_06_04_01_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/World/areatrigger_scripts.cpp
Labels: Branch-master

#30026 Scripts/KingsRest: Implement Intro event
  sql/updates/world/master/2024_06_07_00_world.sql
  src/server/scripts/Zandalar/KingsRest/instance_kings_rest.cpp
  src/server/scripts/Zandalar/KingsRest/kings_rest.cpp
  src/server/scripts/Zandalar/KingsRest/kings_rest.h
  src/server/scripts/Zandalar/zandalar_script_loader.cpp
Labels: Branch-master

#30024 Move zone message handling to map
  src/server/game/Maps/Map.cpp
  src/server/game/Maps/Map.h
  src/server/game/Weather/Weather.cpp
  src/server/game/Weather/Weather.h
  src/server/game/World/World.cpp
  src/server/game/World/World.h
  src/server/scripts/OutdoorPvP/OutdoorPvPSI.cpp
Labels: Branch-3.3.5a

#30023 Core/Creatures: Validate creature.modelid on startup
  sql/updates/world/master/2024_06_08_00_world.sql
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#30027 Core/Spells: Fixed UnitData::ChannelObjects for channeled spells using dest targets
  src/server/game/Spells/Spell.cpp
Labels: Branch-master

#30037 Core/PacketIO: increase ByteBuffer append limit from ~10mb to ~100mb
  src/server/shared/Packets/ByteBuffer.cpp
Labels: Branch-master

#30031 Scripts/KingsRest: Added scripts for Animated Guardian and Minion of Zul
  sql/updates/world/master/2024_06_19_01_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Zandalar/KingsRest/kings_rest.cpp
Labels: Branch-master

#30050 Core/Spells: Don't return immune to reflected spells due to target aurastate
  src/server/game/Spells/Spell.cpp
Labels: Branch-3.3.5a

#30041 Core/Flags: Allow GMs to target npcs with UNIT_FLAG2_UNTARGETABLE_BY_CLIENT flag
  src/server/game/Entities/Object/Updates/UpdateFields.cpp
  src/server/game/Entities/Object/Updates/UpdateFields.h
  src/server/game/Entities/Object/Updates/ViewerDependentValues.h
Labels: Branch-master

#30043 Core/Commands: Allow to complete tracking quests with .quest complete command
  src/server/scripts/Commands/cs_quest.cpp
Labels: Branch-master

#30051 Core/Gameobjects: Fixed the interaction/highlight logic for GAMEOBJECT_TYPE_CHEST and quest objectives
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/GameObject/GameObject.h
  src/server/game/Entities/Object/Updates/ViewerDependentValues.h
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#30042 Core/AreaTriggers: Check actionset flags for client areatriggers
  sql/updates/hotfixes/master/2024_06_23_00_hotfixes.sql
  src/server/database/Database/Implementation/HotfixDatabase.cpp
  src/server/database/Database/Implementation/HotfixDatabase.h
  src/server/game/DataStores/DB2LoadInfo.h
  src/server/game/DataStores/DB2Stores.cpp
  src/server/game/DataStores/DB2Stores.h
  src/server/game/DataStores/DB2Structure.h
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Entities/AreaTrigger/AreaTriggerTemplate.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#30058 Core/Flags: Addition to the https://github.com/TrinityCore/TrinityCor…
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-master

#30055 Core/Spells: Allow get SpellDifficulty on battleground maps
  sql/updates/world/3.3.5/9999_99_99_99_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Northrend/IsleOfConquest/isle_of_conquest.cpp
Labels: Branch-3.3.5a

#30060 Cherry-pick Equipment Manager fix commit
  src/server/game/Entities/Player/Player.cpp
Labels: Branch-3.3.5a

#30057 Core: Add some blizzlike level restrictions while using changefaction
  sql/updates/world/3.3.5/2024_06_27_01_world.sql
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Miscellaneous/Language.h
  src/server/scripts/Commands/cs_character.cpp
Labels: Branch-3.3.5a

#30032 Core/Players: Improve reset spell cooldowns when entering arenas
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Spells/SpellHistory.h
Labels: Branch-3.3.5a

#30066 Scripts/KingsRest: Implement Serpent pre boss event
  sql/updates/world/master/2024_06_29_01_world.sql
  src/server/scripts/Zandalar/KingsRest/instance_kings_rest.cpp
  src/server/scripts/Zandalar/KingsRest/kings_rest.cpp
  src/server/scripts/Zandalar/KingsRest/kings_rest.h
Labels: Branch-master

#30059 Scripts/Kultiras: Implement Heartsbane Triad encounter (All Difficulties)
  sql/updates/world/master/2024_06_29_02_world.sql
  src/server/scripts/KulTiras/WaycrestManor/boss_heartsbane_triad.cpp
  src/server/scripts/KulTiras/WaycrestManor/instance_waycrest_manor.cpp
  src/server/scripts/KulTiras/WaycrestManor/waycrest_manor.h
  src/server/scripts/KulTiras/kultiras_script_loader.cpp
Labels: Branch-master
