Repository TrinityCore/TrinityCore, pull requests merged in 2024-03, with the labels that each got.

#29771 Add macOS arm64 CI (github actions) support.
  .github/workflows/macos-arm-build.yml
  README.md
Labels: Branch-master

#29779 Core/Locales: Fix crash of uninitialized value for empty texts
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#29767 Core/Player: fix incorrect Warrior Block Value calculations
  src/server/game/Entities/Player/Player.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#29808 Core/Pets: Fix warlocks pet character selection screen and Soul Shard return reagent logout exploit
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Server/WorldSession.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#29804 Spells/Priest: Fix rhapsody talent
  sql/updates/world/master/2024_03_18_01_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29828 Core/Player: Fix console errors of wrong teamid for neutral pandaren race
  src/server/game/Achievements/AchievementMgr.cpp
  src/server/game/Battlefield/Battlefield.h
  src/server/game/Battlegrounds/Battleground.cpp
  src/server/game/Battlegrounds/Battleground.h
  src/server/game/Chat/Channels/ChannelMgr.cpp
  src/server/game/Chat/Channels/ChannelMgr.h
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Entities/Taxi/TaxiPathGraph.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/World/World.cpp
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
  src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp
  src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/instance_forge_of_souls.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp
  src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/instance_halls_of_reflection.cpp
  src/server/scripts/Northrend/FrozenHalls/PitOfSaron/instance_pit_of_saron.cpp
  src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
  src/server/scripts/OutdoorPvP/OutdoorPvPHP.cpp
  src/server/scripts/OutdoorPvP/OutdoorPvPNA.cpp
  src/server/scripts/OutdoorPvP/OutdoorPvPTF.cpp
  src/server/scripts/OutdoorPvP/OutdoorPvPZM.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master

#29825 Core/Gameobjects: Added dynamic highlight for GAMEOBJECT_TYPE_SPELL_FOCUS
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/GameObject/GameObject.h
  src/server/game/Entities/GameObject/GameObjectData.h
  src/server/game/Entities/Object/Updates/ViewerDependentValues.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#29776 Scripts/Spells: Implemented Priest talent Whispering Shadows
  sql/updates/world/master/2024_03_24_00_world.sql
  src/server/scripts/Spells/spell_priest.cpp
Labels: Branch-master

#29780 Scripts/Stormwind: Implement RP Event for Quest: "Ancient Curses"
  sql/updates/world/master/2024_03_25_03_world.sql
  src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
Labels: Branch-master

#29795 Only initialize memory for inds mesh in case they will be read.
  src/tools/mmaps_generator/MapBuilder.cpp
Labels: Branch-master

#29833 DB/Mardum: Implement Quest "Give Me Sight Beyond Sight"
  sql/updates/world/master/2024_03_25_04_world.sql
  src/server/scripts/BrokenIsles/zone_mardum.cpp
Labels: Branch-master

#29831 Fix Linux aarch64 GCC build
  cmake/macros/CheckPlatform.cmake
  dep/argon2/CMakeLists.txt
  src/common/Utilities/SFMTRand.cpp
Labels: Branch-3.3.5a

#29836 Core/GameObjects: Implement destructible_hitpoint table
  sql/updates/world/master/2024_03_27_00_world.sql
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/GameObject/GameObject.h
  src/server/game/Entities/GameObject/GameObjectData.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Globals/ObjectMgr.h
  src/server/game/World/World.cpp
  src/server/scripts/Battlefield/BattlefieldTB.cpp
Labels: Branch-master

#29832 Core/Conditions: Added CONDITION_SOURCE_TYPE_PLAYER_CONDITION
  src/server/game/Achievements/CriteriaHandler.cpp
  src/server/game/Conditions/ConditionMgr.cpp
  src/server/game/Conditions/ConditionMgr.h
  src/server/game/Entities/GameObject/GameObject.cpp
  src/server/game/Entities/Item/AzeriteItem/AzeriteItem.cpp
  src/server/game/Entities/Item/Item.cpp
  src/server/game/Entities/Item/ItemBonusMgr.cpp
  src/server/game/Entities/Object/Updates/ViewerDependentValues.h
  src/server/game/Entities/Player/CollectionMgr.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Taxi/TaxiPathGraph.cpp
  src/server/game/Entities/Unit/StatSystem.cpp
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Vignette.cpp
  src/server/game/Globals/ObjectMgr.cpp
  src/server/game/Handlers/ArtifactHandler.cpp
  src/server/game/Handlers/CharacterHandler.cpp
  src/server/game/Handlers/ItemHandler.cpp
  src/server/game/Handlers/MiscHandler.cpp
  src/server/game/Handlers/TaxiHandler.cpp
  src/server/game/Handlers/TransmogrificationHandler.cpp
  src/server/game/Quests/QuestDef.cpp
  src/server/game/Spells/Auras/SpellAuraEffects.cpp
  src/server/game/Spells/SpellInfo.cpp
  src/server/scripts/Commands/cs_debug.cpp
Labels: Branch-master

#29801 Core/Creatures: Changed the spawn health field to a percentage
  sql/updates/world/master/2024_03_30_00_world.sql
  src/server/database/Database/Implementation/WorldDatabase.cpp
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Entities/Creature/Creature.cpp
  src/server/game/Entities/Creature/CreatureData.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
  src/server/game/Globals/ObjectMgr.cpp
  src/server/scripts/Commands/cs_npc.cpp
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_vaelastrasz.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
  src/server/scripts/Spells/spell_generic.cpp
  src/server/scripts/World/npcs_special.cpp
Labels: Branch-master
