Repository TrinityCore/TrinityCore, pull requests merged in 2025-07, with the labels that each got.

#31119 Scripts/GruulsLair: Create base AI for Maulgar's ogres
  src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp
  src/server/scripts/Outland/GruulsLair/instance_gruuls_lair.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#31110 Scripts/Tirisfal: Implement Quest: "A Legend You Can Hold"
  sql/updates/world/master/2025_07_06_01_world.sql
  src/server/scripts/EasternKingdoms/zone_tirisfal_glades.cpp
Labels: Branch-master

#31109 Scripts/HallsOfStone: Modernize scripts
  src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_krystallus.cpp
  src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_maiden_of_grief.cpp
  src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_sjonnir.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#31127 Scripts/Mechanar: Update scripts
  sql/updates/world/3.3.5/2025_07_08_00_world.sql
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_gyrokill.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_ironhand.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/boss_pathaleon_the_calculator.cpp
  src/server/scripts/Outland/TempestKeep/Mechanar/instance_mechanar.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#31124 Scripts/Arcatraz: Update Dalliah & Soccothrates
  sql/updates/world/3.3.5/2025_07_08_01_world.sql
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_dalliah_the_doomsayer.cpp
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_wrath_scryer_soccothrates.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#31096 Scripts/Spells: Implement mage talent Flame Patch
  sql/updates/world/master/2025_07_12_01_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-master

#31100 Scripts/Spells: Migrate & update non-generic quest spell scripts to zone files
  sql/updates/world/3.3.5/2025_07_12_00_world.sql
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
  src/server/scripts/EasternKingdoms/eastern_kingdoms.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Northrend/zone_dragonblight.cpp
  src/server/scripts/Northrend/zone_grizzly_hills.cpp
  src/server/scripts/Northrend/zone_howling_fjord.cpp
  src/server/scripts/Northrend/zone_icecrown.cpp
  src/server/scripts/Northrend/zone_sholazar_basin.cpp
  src/server/scripts/Northrend/zone_storm_peaks.cpp
  src/server/scripts/Northrend/zone_zuldrak.cpp
  src/server/scripts/Outland/zone_blades_edge_mountains.cpp
  src/server/scripts/Outland/zone_terokkar_forest.cpp
  src/server/scripts/Spells/spell_quest.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#31097 Scripts/BloodFurnace: Update Broggok
  sql/updates/world/3.3.5/2025_07_12_01_world.sql
  src/server/scripts/Outland/HellfireCitadel/BloodFurnace/blood_furnace.h
  src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp
  src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp
Labels: Branch-3.3.5a

#31114 Scripts/SholazarBasin: Update several quest scripts
  sql/updates/world/3.3.5/2025_07_12_02_world.sql
  src/server/scripts/Northrend/zone_sholazar_basin.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#31126 Scripts/DalaranLegion: Implement Quest "Call of the Uncrowned"
  sql/updates/world/master/2025_07_12_02_world.sql
  src/server/scripts/BrokenIsles/Orderhalls/zone_orderhall_rogue.cpp
  src/server/scripts/BrokenIsles/broken_isles_script_loader.cpp
  src/server/scripts/BrokenIsles/zone_dalaran_broken_isle.cpp
Labels: Branch-master

#31079 Core/GameObjects: Allow reset for GAMEOBJECT_TYPE_GOOBER without lockId or autoCloseTime
  src/server/game/Entities/GameObject/GameObject.cpp
Labels: Branch-master

#31093 Scripts/Spells: Fix mage talent Feel the Burn proc
  sql/updates/world/master/2025_07_13_11_world.sql
Labels: Branch-master

#31091 Scripts/Spells: Implement mage talent Molten Fury
  sql/updates/world/master/2025_07_13_12_world.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-master

#31133 Core/SAI: Implemented action type SMART_ACTION_DESTROY_CONVERSATION
  src/server/game/AI/SmartScripts/SmartScript.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
  src/server/game/AI/SmartScripts/SmartScriptMgr.h
Labels: Branch-master

#31088 Scripts/Spells: Implement mage talent Improved Combustion
  sql/updates/world/master/2025_07_17_01_world.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-master

#31086 Scripts/Spells: Implement mage talent Scald
  sql/updates/world/master/2025_07_18_00_world.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-master

#31067 Scripts/Spells: Implement Unbridled Ferocity
  sql/updates/world/master/2025_07_19_03_world.sql
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#31064 Scripts/Spells: Implement Improved Whirlwind & Whirlwind target cap
  sql/updates/world/master/2025_07_19_05_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#31065 Script/Spells: Implement Sudden Death & Juggernaut (Fury)
  sql/updates/world/master/2025_07_19_06_world.sql
  src/server/scripts/Spells/spell_warrior.cpp
Labels: Branch-master

#31085 Scripts/Spells: Implement mage talent Improved Scorch
  sql/updates/world/master/2025_07_19_07_world.sql
  src/server/scripts/Spells/spell_mage.cpp
Labels: Branch-master

#31149 Core/Quests: Port "Reset seasonal quests based on saved completion time and intended holiday start time" to 3.3.5
  sql/base/characters_database.sql
  sql/updates/characters/3.3.5/2025_07_20_00_characters_2022_07_03_00_characters.sql
  src/server/database/Database/Implementation/CharacterDatabase.cpp
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Events/GameEventMgr.cpp
  src/server/game/Events/GameEventMgr.h
  src/server/game/World/World.cpp
  src/server/game/World/World.h
Labels: Branch-3.3.5a

#31021 Scripts/ShatteredHalls: Update scripts
  sql/updates/world/3.3.5/2025_07_22_00_world.sql
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_warbringer_omrogg.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_warchief_kargath_bladefist.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.cpp
  src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.h
Labels: Feedback-PatchFix, Branch-3.3.5a

#31163 Core/Pools: Fix handle respawning for nested pools
  src/server/game/Pools/PoolMgr.cpp
Labels: Branch-3.3.5a

#31146 Scripts/ReturnToKarazhan: Implement The Curator encounter
  sql/updates/world/master/2025_07_26_00_world.sql
  src/server/scripts/EasternKingdoms/ReturnToKarazhan/boss_the_curator_rtk.cpp
  src/server/scripts/EasternKingdoms/ReturnToKarazhan/instance_return_to_karazhan.cpp
  src/server/scripts/EasternKingdoms/ReturnToKarazhan/return_to_karazhan.h
  src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
Labels: Branch-master

#31136 Scripts/SerpentshrineCavern: Rewrite Karathress
  sql/updates/world/3.3.5/2025_07_27_00_world.sql
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
  src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/serpent_shrine.h
Labels: Feedback-PatchFix, Branch-3.3.5a
