Repository TrinityCore/TrinityCore, pull requests merged in 2025-03, with the labels that each got.

#30709 Scripts/Scarlet Monastery: Do not start path for npc_scarlet_trainee if combat
  src/server/scripts/EasternKingdoms/ScarletMonastery/boss_herod.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30731 Scripts/BlackrockDepths: In the Lyceum both braziers have to be used in order to open both doors.
  src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30721 Spells/DH: Rewrite Cycle of Hatred talent for patch 11.1
  sql/updates/world/master/2025_03_11_00_world.sql
  src/server/scripts/Spells/spell_dh.cpp
Labels: Branch-master

#30695 Core/Spells: Updates autoshoot spell target in case of client-side target change
  src/server/game/Handlers/MiscHandler.cpp
Labels: Feedback-FixOutdatedMissingWIP, Branch-3.3.5a

#30748 DB/Spawns: Add initial spawns of Liberation of Undermine for first boss
  sql/updates/world/master/2025_03_23_02_world.sql
Labels: Branch-master

#30786 Core/Auth: Do not close Authserver at startup when no valid realms found
  src/server/authserver/Main.cpp
Labels: Branch-3.3.5a

#30790 Core/Spells: Updating script of hunter spell Steady Shot to 11.1
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#30796 Core/Transport: Fixed events not triggering when timestamp matches path progress
  src/server/game/Entities/Transport/Transport.cpp
Labels: Branch-master

#30794 Scripts/Drustvar: Implement Take a seat event for Quest: "Witch Hunt"
  sql/updates/world/master/2025_04_01_01_world.sql
  src/server/scripts/KulTiras/Drustvar/drustvar_chapter_1_the_final_effigy.cpp
  src/server/scripts/KulTiras/kultiras_script_loader.cpp
Labels: Branch-master

#30773 Scripts/Spells: Fix druid talent Raze target cap
  src/server/game/Spells/SpellMgr.cpp
Labels: Branch-master

#30802 Scripts/Drustvar: Added combat script for Helena Gentle
  sql/updates/world/master/2025_04_01_02_world.sql
  src/server/scripts/KulTiras/Drustvar/drustvar_chapter_1_the_final_effigy.cpp
Labels: Branch-master
