Repository TrinityCore/TrinityCore, pull requests merged in 2025-05, with the labels that each got.

#30866 Scripts/DireMaul: Allow players to open The Prince's Chest if Prince Tortheldrin is killed
  src/server/scripts/Kalimdor/DireMaul/diremaul.h
  src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp
Labels: Branch-3.3.5a

#30856 Spells/Hunter: Implement talent Implosive Trap
  sql/updates/world/master/2025_05_04_00_world.sql
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#30848 Spells/Hunter: Implement talent Wilderness Medicine
  sql/updates/world/master/2025_05_04_01_world.sql
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#30846 Spells/Hunter: Implement talent Tar Trap
  sql/updates/world/master/2025_05_04_02_world.sql
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#30841 Spells/Hunter: Implement talent Scout's Instincts
  sql/updates/world/master/2025_05_05_00_world.sql
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#30914 Scripts/Spells: Implement Putrid Mushroom Primer spell
  sql/updates/world/3.3.5/2025_05_08_00_world.sql
  src/server/scripts/Outland/CoilfangReservoir/TheUnderbog/boss_hungarfen.cpp
  src/server/scripts/Outland/CoilfangReservoir/TheUnderbog/boss_the_black_stalker.cpp
Labels: Branch-3.3.5a

#30917 Core/Misc: Misc small updates
  src/common/Banner.cpp
  src/server/authserver/Main.cpp
  src/server/database/Database/DatabaseLoader.cpp
  src/server/game/Miscellaneous/Language.h
  src/server/game/Scripting/ScriptMgr.cpp
  src/server/game/World/World.cpp
  src/server/worldserver/worldserver.conf.dist
Labels: Branch-3.3.5a

#30915 Scripts/Spells: Get rid of some database spell scripts
  sql/updates/world/3.3.5/2025_05_08_01_world.sql
  src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
  src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
  src/server/scripts/EasternKingdoms/ZulGurub/zulgurub.cpp
  src/server/scripts/EasternKingdoms/eastern_kingdoms.cpp
  src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
  src/server/scripts/Events/brewfest.cpp
  src/server/scripts/Events/lunar_festival.cpp
  src/server/scripts/Events/midsummer.cpp
  src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.cpp
  src/server/scripts/Kalimdor/kalimdor_script_loader.cpp
  src/server/scripts/Northrend/zone_borean_tundra.cpp
  src/server/scripts/Northrend/zone_dalaran.cpp
  src/server/scripts/Northrend/zone_dragonblight.cpp
  src/server/scripts/Northrend/zone_grizzly_hills.cpp
  src/server/scripts/Northrend/zone_icecrown.cpp
  src/server/scripts/Northrend/zone_zuldrak.cpp
  src/server/scripts/Outland/Auchindoun/ManaTombs/mana_tombs.cpp
  src/server/scripts/Outland/outland_script_loader.cpp
  src/server/scripts/Outland/zone_blades_edge_mountains.cpp
  src/server/scripts/Outland/zone_hellfire_peninsula.cpp
  src/server/scripts/Outland/zone_shadowmoon_valley.cpp
  src/server/scripts/Outland/zone_terokkar_forest.cpp
Labels: Branch-3.3.5a

#30908 Scripts/Spells: Implement generic spell script to cancel aura
  sql/updates/world/3.3.5/2025_05_09_00_world.sql
  src/server/scripts/Events/love_is_in_the_air.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp
  src/server/scripts/Northrend/zone_storm_peaks.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-3.3.5a

#30832 Core/AreaTrigger: Implement AreaTriggerActionSetFlag::DontDespawnWith…
  src/server/game/DataStores/DBCEnums.h
  src/server/game/Entities/Unit/Unit.cpp
  src/server/game/Entities/Unit/Unit.h
Labels: Branch-master

#30932 Scripts/Spells: Implement spell no NPC damage below Override Points
  sql/updates/world/master/2025_05_11_02_world.sql
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master

#30933 Build: MySQL search path cherry picks
  cmake/macros/FindMySQL.cmake
Labels: Branch-3.3.5a

#30882 Core/Misc: Added new CanSeeOrDetectExtraArgs to CanSeeOrDetect
  src/server/game/AI/CoreAI/TotemAI.cpp
  src/server/game/Entities/Object/Object.cpp
  src/server/game/Entities/Object/Object.h
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
  src/server/game/Grids/Notifiers/GridNotifiers.cpp
  src/server/game/Miscellaneous/SharedDefines.h
  src/server/game/Spells/SpellInfo.cpp
  src/server/game/Spells/SpellInfo.h
Labels: Branch-master

#30878 Core/Vehicles: Added field to set a default pitch
  sql/updates/world/master/2025_05_11_03_world.sql
  src/server/game/Entities/Vehicle/Vehicle.cpp
  src/server/game/Entities/Vehicle/Vehicle.h
  src/server/game/Entities/Vehicle/VehicleDefines.h
  src/server/game/Globals/ObjectMgr.cpp
Labels: Branch-master

#30788 Core/Spells: Fix proc of hunter talent Bullseye
  sql/updates/world/master/2025_05_12_01_world.sql
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master

#30927 Core/Network: Update LoginRESTService to check all addresses together
  src/server/bnetserver/REST/LoginRESTService.cpp
  src/server/bnetserver/REST/LoginRESTService.h
Labels: Branch-master

#30939 Scripts/Drustvar: Implement Quest: "Really Big Problem"
  sql/updates/world/master/2025_05_14_01_world.sql
  src/server/scripts/KulTiras/Drustvar/zone_drustvar.cpp
  src/server/scripts/KulTiras/kultiras_script_loader.cpp
Labels: Branch-master

#30884 Scripts/TheJadeForest: Implement quest "Paint it Red!" (31765)
  sql/updates/world/master/2025_05_16_00_world.sql
  src/server/game/Spells/SpellMgr.cpp
  src/server/scripts/Pandaria/zone_the_jade_forest.cpp
  src/server/scripts/Spells/spell_generic.cpp
Labels: Branch-master

#30920 Scripts/Scholomance: Update scripts
  src/server/scripts/EasternKingdoms/Scholomance/boss_darkmaster_gandling.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_death_knight_darkreaver.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_doctor_theolen_krastinov.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_illucia_barov.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_instructor_malicia.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_jandice_barov.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_kirtonos_the_herald.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_kormok.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_lord_alexei_barov.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_lorekeeper_polkelt.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_ras_frostwhisper.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_the_ravenian.cpp
  src/server/scripts/EasternKingdoms/Scholomance/boss_vectus.cpp
  src/server/scripts/EasternKingdoms/Scholomance/scholomance.h
Labels: Branch-3.3.5a

#30948 Scripts: Update a couple Steam Vault scripts
  sql/updates/world/3.3.5/2025_05_17_00_world.sql
  src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_hydromancer_thespia.cpp
  src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_mekgineer_steamrigger.cpp
  src/server/scripts/Outland/CoilfangReservoir/SteamVault/steam_vault.h
Labels: Feedback-PatchFix, Branch-3.3.5a

#30945 Scripts: Update a couple Arcatraz scripts
  sql/updates/world/3.3.5/2025_05_17_01_world.sql
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_harbinger_skyriss.cpp
  src/server/scripts/Outland/TempestKeep/arcatraz/boss_zereketh_the_unbound.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30943 Scripts: Update Thorngrin's script
  sql/updates/world/3.3.5/2025_05_17_02_world.sql
  src/server/scripts/Outland/TempestKeep/botanica/boss_thorngrin_the_tender.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30935 Scripts: Update Sethekk Halls scripts
  sql/updates/world/3.3.5/2025_05_17_03_world.sql
  src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_anzu.cpp
  src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_darkweaver_syth.cpp
  src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30938 Scripts: Update Shirrak's script
  sql/updates/world/3.3.5/2025_05_17_06_world.sql
  src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_shirrak_the_dead_watcher.cpp
Labels: Branch-3.3.5a

#30923 Core/SpawnTracking: Check if the objective is completable to get correct spawn tracking state
  src/server/game/Entities/Player/Player.cpp
  src/server/game/Entities/Player/Player.h
Labels: Branch-master

#30544 Scripts/Spells: Implement demon hunter talent "Demonic"
  sql/updates/world/master/2025_05_17_02_world.sql
  src/server/scripts/Spells/spell_dh.cpp
Labels: Branch-master

#30756 Core/Spells: Fix hunter pets not losing happiness when dismissed
  src/server/game/Spells/SpellEffects.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30928 Core/Spells: Properly retrieve pet to dismiss for spells with SPELL_ATTR1_DISMISS_PET
  src/server/game/Spells/Spell.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30955 Spells/DK: Implement talent Sanguine Ground
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-master

#30956 Spells/DK: Implement talent Blooddrinker
  sql/updates/world/master/2025_05_20_00_world.sql
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-master

#30959 Scripts/AuchenaiCrypts: Small corrections to scripts
  src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_exarch_maladaar.cpp
  src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_shirrak_the_dead_watcher.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30960 Scripts/Spells: Implement death knight talent Voracious
  sql/updates/world/master/2025_05_20_01_world.sql
  src/server/scripts/Spells/spell_dk.cpp
Labels: Branch-master

#30982 Core/Misc: Properly teleport player outside of the instance
  src/server/game/Server/WorldSession.cpp
Labels: Branch-3.3.5a

#30979 Scripts/Spells: Implement rogue talent Shot in the dark
  sql/updates/world/master/2025_05_25_00_world.sql
  src/server/scripts/Spells/spell_rogue.cpp
Labels: Branch-master

#30972 Scripts/Spells: Implement rogue talent Shuriken Tornado
  sql/updates/world/master/2025_05_25_04_world.sql
  src/server/scripts/Spells/spell_rogue.cpp
Labels: Branch-master

#30969 Scripts/Spells: Implement demon hunter talent Violent Transformation
  sql/updates/world/master/2025_05_25_05_world.sql
  src/server/scripts/Spells/spell_dh.cpp
Labels: Branch-master

#30953 Core/Procs: Implement PROC_FLAG_2_SUCCESSFUL_DISPEL
  src/server/game/Spells/SpellEffects.cpp
Labels: Branch-master

#30981 DB/Dungeons: Fix area triggers and add cosmetic portals for vanilla dungeons
  sql/updates/world/master/2025_05_26_01_world.sql
Labels: Branch-master

#30999 DB/Dungeons: Add instance portals for WotLK dungeons
  sql/updates/world/master/2025_05_27_02_world.sql
Labels: Branch-master

#31000 Scripts/IcecrownCitadel: Modernize scripts
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_festergut.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_sister_svalna.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
  src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
  src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#31001 Core/Misc: Fix player outdoor status after leaving an instance
  src/server/game/Handlers/MovementHandler.cpp
Labels: Branch-master

#30993 Scripts/DraktharonKeep: Modernize scripts
  sql/updates/world/3.3.5/2025_05_27_00_world.sql
  src/server/scripts/Northrend/DraktharonKeep/boss_king_dred.cpp
  src/server/scripts/Northrend/DraktharonKeep/boss_novos.cpp
  src/server/scripts/Northrend/DraktharonKeep/boss_tharon_ja.cpp
  src/server/scripts/Northrend/DraktharonKeep/boss_trollgore.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30997 DB/Dungeons: Remove deprecated The Black Morass attunement
  sql/updates/world/master/2025_05_27_04_world.sql
Labels: Branch-master

#30965 Scripts/Dalaran: Replace TeleportTo function with spells
  sql/updates/world/3.3.5/2025_05_28_00_world.sql
  src/server/scripts/Northrend/zone_dalaran.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30957 Scripts/TheSlavePens: Modernize Kalithresh script
  sql/updates/world/3.3.5/2025_05_28_02_world.sql
  src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_warlord_kalithresh.cpp
  src/server/scripts/Outland/CoilfangReservoir/SteamVault/instance_steam_vault.cpp
Labels: Feedback-PatchFix, Branch-3.3.5a

#30954 Spells/Paladin: Implement talent A just reward
  sql/updates/world/master/2025_05_28_00_world.sql
  src/server/scripts/Spells/spell_paladin.cpp
Labels: Branch-master

#30947 Scripts/Redridge: Implement Quest "Saving Foreman Oslow"
  sql/updates/world/master/2025_05_30_01_world.sql
  src/server/scripts/EasternKingdoms/zone_redridge_mountains.cpp
Labels: Branch-master

#30951 Scripts/Warlock: Fix talent Shadowburn
  sql/updates/world/master/2025_05_30_02_world.sql
  src/server/scripts/Spells/spell_warlock.cpp
Labels: Branch-master

#30967 Scripts/Boralus: Implement Quest: "Daughter of the Sea"
  sql/updates/world/master/2025_05_31_00_world.sql
  src/server/scripts/KulTiras/zone_boralus.cpp
Labels: Branch-master

#30941 Scripts/Spells: Implement hunter talent Streamline
  sql/updates/world/master/2025_05_31_02_world.sql
  src/server/scripts/Spells/spell_hunter.cpp
Labels: Branch-master
